intel/BigDL

pyzoo/zoo/examples/autograd/customloss.py, pyzoo/zoo/models/recommendation/neuralcf.py, pyzoo/zoo/models/recommendation/recommender.py, pyzoo/zoo/models/recommendation/wide_and_deep.py, pyzoo/zoo/models/textclassification/text_classifier.py
This is actually not a problem for recommender but for all python warps that involve `numpy.int64` will have this error http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Python-AppTests/46/consoleFull 
This PR fixes this for recommender and corresponding APIs; namely cast input to int.
So that Python notebooks for recommenders can pass jenkins.
https://github.com/intel-analytics/zoo/issues/222
=> Fix recommender for Python 3

pyzoo/zoo/models/image/common/image_config.py, pyzoo/zoo/models/image/imageclassification/image_classification.py, pyzoo/zoo/models/image/objectdetection/object_detector.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/ObjectDetectionConfig.scala
Currently in our code, there is "from bigdl.util.common import *". It may overwrite the class defined in zoo(eg, Brightness) when loading. It would be better if we can explictly declare what's needed from BigDL,
=> Explicitly claim imported library

pyzoo/dev/release/release.sh, pyzoo/setup.py, zoo/pom.xml
Fix https://github.com/intel-analytics/zoo/issues/226
cc @jason-dai 
I try if we remove bigdl in our package, and add bigdl as a dependency, it can work and the whl file size will definitely be smaller.
I test using the following code after pip install the whl file and start python REPL:
```
from zoo.common.nncontext import *
sc = get_nncontext()
from zoo.pipeline.api.keras.layers import *
from zoo.pipeline.api.keras.models import *
model = Sequential()
model.add(Dense(3, input_shape=(10, )))
```
My preference is to use `bigdl==0.5.0` as a dependency and in this case we don't need to worry anything about the pypi file size. Moreover, if we use the current way, there will possibly be potential problem if users have already install bigdl.
Possibly we need a jar that includes all other …
=> Remove bigdl in jar and add it as a pip dependency

pyzoo/zoo/util/engine.py
Before appending to environment variables, check if it already exists.
Fix this in Analytics Zoo. But as BigDL also has such code, print "Adding ... to ..." multiple times is still unavoidable unless we fix in BigDL.
As far as I test, now even if the message is printed multiple times, `BIGDL_JARS` only has one jar as we desire. Without the check, there will be two duplicate jars.
=> Check environment variable/sys.path when adding

pyzoo/test/zoo/pipeline/api/keras/test_net.py, pyzoo/zoo/pipeline/api/net.py
A bug brought by https://github.com/intel-analytics/analytics-zoo/pull/132
Need to add `return`, otherwise the return result is None.
=> Fix Net.load_keras()

pyzoo/zoo/pipeline/api/keras/engine/topology.py
cc @JasonChu1313
A typo just noticed... should be `distributed`...
=> fix a typo in predict

apps/anomaly-detection/anomaly-detection-nyc-taxi.ipynb
Even though the code could run flawlessly, the error info would confuse users when no data found.
=> Fix Print info

.gitignore, .gitmodules, make-dist.sh, pyzoo/dev/prepare_env.sh, scripts/get_bigdl_python, zoo/pom.xml, zoo/src/assembly/dist-all.xml, zoo/src/assembly/dist.xml, zoo/src/assembly/python-zip.xml
With this Patch, Analytics-Zoo can pull python dependency from Maven directly and build the whole project base on the given bigdl version.
Commands:
`./make-dist.sh -Pspark_2.x -DskipTests` or specify an alternative bigdl version.
`./make-dist.sh -Pspark_2.x -Dbigdl.version=0.6.0-SNAPSHOT -DskipTests`
=> Support pulling python dependency from maven

pyzoo/zoo/examples/tfnet/predict.py, zoo/src/main/scala/com/intel/analytics/zoo/examples/tfnet/Predict.scala
After @dding3 's fix on get_predict(), remove SelectTable() layer in the example.
BTW, tensorflow has updated the download link from 20171117 to 20180128
=> Update python tfnet predict example

docs/docs/PythonUserGuide/install.md, pyzoo/setup.py
Fix https://github.com/intel-analytics/zoo/issues/336
As this example will fail for spark 2.3.1.
=> Restrict pyspark version for pip install; doc update

pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py, pyzoo/zoo/pipeline/nnframes/nn_classifier.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNClassifier.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNClassifierSpec.scala
Allow  NNClassifier to support model with a single scalar output, like a model with single sigmoid output.
=> support model with single output for NNClassifier.

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/WordEmbedding.scala
Not sure why previous `SerializationUtils.deserialize(weight)` will throw exception:
```
Caused by: org.apache.commons.lang.SerializationException: java.lang.ClassNotFoundException: com.intel.analytics.bigdl.tensor.DenseTensor$mcF$sp
at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:166)
at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:193)
at com.intel.analytics.zoo.pipeline.api.keras.layers.WordEmbedding$EmbeddingMatrixHolder$$anonfun$5.apply(WordEmbedding.scala:295)
at com.intel.analytics.zoo.pipeline.api.keras.layers.WordEmbedding$EmbeddingMatrixHolder$$anonfun$5.apply(WordEmbedding.scala:283)
at com.intel.analytics.zoo.pipeline.api.net.RegistryMap.getOrCreate(NetUtils.scala:386)
at …
```
=> Fix textclassification example running on cluster

pyzoo/zoo/pipeline/api/keras/objectives.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/objectives/LossFunction.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/objectives/SparseCategoricalCrossEntropy.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
Due to the inconsistency of implementations of criterions in BigDL, directly assign the value of `updateOutput` to output in LossFunction instead of getting `loss.output`
=> Fix LossFunction updateOutput

zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/NeuralCF.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/WideAndDeep.scala
Changed Recommender models(NCF and WideAndDeep) from private to public.
Currently, features of recommender models are well fixed according to the papers and blogs, customers might want to add different features in different formats. For example, NCF only uses userId and itemId as features, but jobs2career wants to have features of vectors. 
https://github.com/intel-analytics/Jobs2Careers/blob/master/src/main/scala/com/intel/analytics/bigdl/apps/recommendation/NCFJob2Career.scala
Public NCF/WideAndDeep gives customers flexibility to build different recommender models with different features.
=> ncf goes public

zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/FeatureSpec.scala
Support imageset constructor accepts array[Bytes] (or RDD of array bytes)
Fix https://github.com/intel-analytics/zoo/issues/354#event-1771881130
=> bytes array to imageset

docker/Dockerfile
fix a error:
http://10.239.47.211:18888/job/ZOO-NB-Deploy-Docker/21/console
[91mE: There are problems and -y was used without --force-yes
[0mThe command '/bin/sh -c apt-get install -y software-properties-common python-software-properties python-pkg-resources &&     add-apt-repository -y ppa:jonathonf/python-2.7 &&     apt-get update &&     apt-get install -y build-essential python python-setuptools python-dev &&     wget https://bootstrap.pypa.io/get-pip.py &&     python2 get-pip.py &&     pip2 install --upgrade setuptools &&     pip2 install numpy scipy pandas scikit-learn matplotlib seaborn jupyter wordcloud moviepy requests opencv-python tensorflow &&     python2 -m pip install ipykernel &&     python2 -m ipykernel install --user' returned a non-zero code: 100
---
This change …
=> fix a error caused by force yes

pyzoo/test/zoo/pipeline/api/keras/test_layer.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Reshape.scala
nonBatchInput could contain -1 in it and breaks the require constraint. The following code (same as in unit test) fails with the original code
```
from zoo.pipeline.api.keras.layers import *
from zoo.pipeline.api.keras.models import Model
from zoo.common.nncontext import *
import numpy as np
sparkConf = create_spark_conf().setMaster("local[1]").setAppName("testNNClassifer")
sc = init_nncontext(sparkConf)
a = np.random.random((2, 2, 3, 4))
i1 = Input(shape = (2, 3, 4))
s = Reshape((-1, 2, 12))(i1)
m = Model(i1, s)
y = m.predict(a, distributed=False)
print(y)
```
=> remove unnecessary require in Reshape

zoo/src/main/scala/com/intel/analytics/zoo/feature/image/BufferedImageResize.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/FeatureSpec.scala
Bug fix for https://github.com/intel-analytics/zoo/issues/379
=> Imageset.read with resize keep the same channel with original image

pyzoo/test/zoo/pipeline/nnframes/test_nn_image_reader.py, pyzoo/zoo/pipeline/nnframes/nn_image_reader.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNImageReader.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNImageReaderSpec.scala
Since ImageSet.read already creates Mat from image bytes, NNImageReader now can just save the converted mat in DataFrame, and original files bytes are no longer useful and is removed from generated imageFeature.
=> replace bytes with mat in nnframes

docs/docs/PythonUserGuide/install.md
In the case that README links to the python install page of master branch, it is not reasonable if we specify `==0.3.0.dev0` (an unreleased version)
=> Remove pip install version in python guide

pyzoo/zoo/pipeline/api/keras/metrics.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/Accuracy.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/AccuracySpec.scala
A bug for zero-based label Accuracy.
In the case of binary classification, zero-based label shouldn't take effect.
Only to add 1 if it is a multiclass problem.
=> Fix Accuracy for binary classification

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
if we fist test if the key is in the map then retrieve the key, there is a chance that the key got garbage collected right after the test, thus result in a KeyNotFound exception.
=> Fix RegistryMap key not found bug

docs/docs/PythonUserGuide/install.md, docs/docs/PythonUserGuide/run.md, scripts/README.md
- In README under scripts, directly link to website doc so that we don't need to maintain the same instructions in two places.
- Style of website generated fixed.
=> Update README for yarn guide and fix website style

pyzoo/setup.py
http://10.239.47.211:18888/view/ZOO-NB/job/ZOO-NB-Deploy-PYTHON/238/console
Previously get the version need to execute the python file, which will throw the exception that bigdl hasn't been installed.
Now just read the lines and get the version.
=> Fix pip install release issue in setup.py

pyzoo/test/zoo/feature/text/test_text_set.py, pyzoo/test/zoo/models/textclassification/test_textclassifier.py, pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py, pyzoo/test/zoo/pipeline/utils/test_utils.py, pyzoo/zoo/models/common/zoo_model.py, pyzoo/zoo/models/textclassification/text_classifier.py, pyzoo/zoo/pipeline/api/keras/engine/topology.py, zoo/src/main/scala/com/intel/analytics/zoo/models/common/ZooModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/textclassification/TextClassifier.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextSetSpec.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/ZooSpecHelper.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/DropoutSpec.scala
Previously, `self.model.compile/fit/predict`, this will cause an error if the TextClassifier is directly loaded instead of initialized. Wrap the method from Scala side in this PR.
Add more unit tests for predict after model loading.
Add `setEvaluateStatus()` in KerasNet/ZooModel, which will be clearer than the previous `evaluate()` and also for Python use. Added unit tests.
=> Fix TextClassifier methods and add setEvaluateStatus

zoo/src/main/scala/com/intel/analytics/zoo/common/PythonZoo.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextPredictor.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Predictor.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
1. move predict methods to a trait so that other mode (like TFNet)l can use these methods
2. create a new predictor for the use of analytics-zoo
3. fix memory leak when using TFNet (create a Iterator that will call a shutdown hook when hasNext return false)
=> Move predict methods to a trait and fix tfnet memory leak

pyzoo/zoo/pipeline/nnframes/nn_classifier.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
This PR is to refine the API for NNEstimator/NNClassifier.
NNEstimator and NNClassifier now supports setting learning rate via setLearningRate, yet users can also set learning rate (and learning rate decay) with OptimMehod, which can lead to confusion. Deprecate setLearningRate and setLearningRateDecay.
=> deprecate lr

pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py, pyzoo/zoo/feature/common.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/common/MLlibVectorToTensor.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
The PR leverages the Spark-version projects in BigDL to process both MLlib and ML Vectors, thus to allow NNEstimator and NNClassifier to use ML Vectors as features and labels.
=> Support ML Vector for NNFrames.

pyzoo/test/zoo/models/textmatching/test_knrm.py, pyzoo/zoo/feature/text/text_feature.py, pyzoo/zoo/models/textmatching/knrm.py, pyzoo/zoo/models/textmatching/text_matcher.py, pyzoo/zoo/pipeline/api/keras/layers/embeddings.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextFeature.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/textmatching/KNRM.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/WordEmbedding.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
Keep consistent with Scala, use embedding_file and word_index to construct a KNRM model.
For QARanker Python side, will split into several PRs to finish.
=> Update KNRM Python

pyzoo/zoo/pipeline/api/net.py, pyzoo/zoo/util/tf.py
after this pr, user can use our variable_creator_scope do workaround the ResourceVariable problem
```    
from zoo.util.tf import variable_creator_scope
with variable_creator_scope():
model = MultiTaskIntentModel(use_cudnn=args.use_cudnn)
model.build(dataset.word_len,
dataset.label_vocab_size,
dataset.intent_size,
dataset.word_vocab_size,
dataset.char_vocab_size,
word_emb_dims=args.token_emb_size,
tagger_lstm_dims=args.lstm_hidden_size,
dropout=args.tagger_dropout)
```
=> add variable creator scope to disable use_resource

zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/RNNDecoder.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seq.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InternalTimeDistributed.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala, zoo/src/test/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seqSpec.scala
This PR includes several seq2seq bug fix which included in https://github.com/intel-analytics/analytics-zoo/pull/1062/files. Just in case PR #1062 cannot be merged before 0.4 release.
1. RNNDecoder should not update input
2. seq2seq infer should take into account `generator` is null
3. InternalTimeDistributed should compute `outputsize` in each `forward`
=> seq2seq and InternalTimeDistributed bug fix

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Embedding.scala
An error brought by PR #1062 
In the factory method Scala, default should be true. @dding3
=> Fix default value of zeroBasedId in Embedding

docker/Dockerfile
this pr is to update docker parent image from ubuntu 14.04 to 18.04
the reason is the latest pandas(0.24.1) requires gcc 4.9+, ubuntu 14's gcc is 4.8
so update to ubuntu 18.04
has built and tested the apps running in the generated container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1144)
=> update docker from ubuntu 14 to 18

zoo/src/main/scala/com/intel/analytics/zoo/examples/qaranker/QARanker.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/qaranker/README.md, zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/common/ArrayLike.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/pmem/FeatureSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/pmem/NativeSpec.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/pmem/PersistentMemorySpec.scala
Persist memory support in TextSet
User could set memoryType to `PMEM` to cache train dataset to Persist Memory.
=> Persist memory support in TextSet

docs/docs/ProgrammingGuide/run-on-dataproc.md, docs/mkdocs.yml, zoo/pom.xml
This PR adds some important details to deploy jobs with Zoo on Google Dataproc. It is mostly based on the description from current BigDL docs.
The details here:
https://groups.google.com/forum/#!topic/bigdl-user-group/6hD1pz18968
And here:
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/469
=> Google Dataproc support description in docs

pyzoo/zoo/models/anomalydetection/anomaly_detector.py, pyzoo/zoo/models/seq2seq/seq2seq.py, pyzoo/zoo/models/textclassification/text_classifier.py, pyzoo/zoo/pipeline/api/keras/engine/topology.py, pyzoo/zoo/pipeline/api/keras/metrics.py, pyzoo/zoo/pipeline/api/keras/utils.py, pyzoo/zoo/pipeline/api/net.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/Accuracy.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/AccuracySpec.scala
In order to consistent with the loss function, this patch would introduce CategoricalAccuracy, BinaryAccuracy, and SparseCategoricalAccuracy and deprecate the `Accuracy` class.
=> Add CategoricalAccuracy, BinaryAccuracy, and SparseCategoricalAccuracy

pyzoo/dev/release/release.sh
- Support custom profile options
- Remove unnecessary quick install option
- Put without_bigdl as default
- Update some typos.
Usage:
```
bash release.sh linux -Dspark.version=2.3.2 -Dbigdl.artifactId=bigdl-SPARK_2.3 -P spark_2.x
```
This command is the same as Scala's release command.
=> Update pip release script

pyzoo/zoo/pipeline/api/net.py, pyzoo/zoo/tfpark/model.py
- Modify predict result if input is ndarray to keep aligned with Keras,
Output now should be (batch, ...) [single output] or [(batch, ...), (batch, ...), ...] [multiple outputs]
- Some minor modifications: change get_spark_context() in bigdl to getOrCreateSparkContext() in Zoo.
Will add some ut to cover multiple output case.
=> Update tfpark API

pyzoo/test/zoo/feature/text/test_text_set.py, pyzoo/zoo/feature/common.py, pyzoo/zoo/feature/text/text_set.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/common/Relations.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonTextFeature.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextSet.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextSetSpec.scala
Especially for the convenience of inference:
- Refactor saveWordIndex method to support HDFS.
- Add loadWordIndex method.
- Add more docs for word2idx.
- Add missing Python wrap.
- Add uts to cover the changes.
Will add examples and update website doc gradually in the future.
=> Enhance TextSet wordIndex API

pyzoo/zoo/tfpark/estimator.py
Adjusted the place to create `tf.train.Saver()`. There would be no parameters when using `tf.import_graph_def` to restore the model to evaluate or predict. In such a case, a `ValueError` would occur because there are no parameters to save or restore when creating `tf.train.Saver()`
=> support TFEstimator for model without parameters

pyzoo/test/zoo/pipeline/api/keras/test_layer.py, pyzoo/zoo/pipeline/api/keras/layers/normalization.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BatchNormalization.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BatchNormalizationSpec.scala
Batch normalization to support 2D input and normalize the second dimension.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/1222
=> Modify keras batch normalization to support 2D input

.gitignore, pyzoo/dev/prepare_env.sh, scripts/get_python_packages, zoo/pom.xml, zoo/src/assembly/python-zip.xml
Fix #1236 
- Previously all python packages will be downloaded to analytics-zoo/zoo/target/python, which will be cleaned when rebuilding the project.
- Now put external python packages under analytics-zoo/zoo/python_packages and do the check to prevent re-downloading the packages when building the project.
Remark: GitHub server seems doesn't control timestamp well, thus upon my test `wget -N` doesn't work and will still download again. I use `wget -nc` and in this case but it seems if the file isn't fully downloaded with the same name it will also not download. Since this is for our internal use mainly, first merge it and once we successfully download once, it will not re-download.
=> Fix re-download nlp-architect every time when make_dist

docs/docs/ProgrammingGuide/seq2seq.md
A small doc update for `numLayers` parameter in Seq2Seq (`numLayer` doesn't exist)
=> Seq2seq doc fix for numLayers parameter

zoo/src/main/scala/com/intel/analytics/zoo/common/Utils.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/streaming/objectdetection/ImagePathWriter.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/streaming/objectdetection/StreamingObjectDetection.scala, zoo/src/test/scala/com/intel/analytics/zoo/common/UtilsSpec.scala
Add remote file system support for Utils
* Add `listPaths` for listing file paths on both local and remote file system.
* Add `writeLines` for saving `String` to file.
* Add `readBytes` (based on `bigdl.utils.File`) for reading all bytes of given file.
* Add `open` and `create` methods for handling large files.
=> Add remote file system support for Utils

pyzoo/test/zoo/pipeline/api/keras/test_net.py, pyzoo/zoo/pipeline/api/keras/engine/topology.py, pyzoo/zoo/pipeline/api/net.py, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/DenseSpec.scala
1)  User should use `model.saveModel` and exception would be raised if they use `model.save` accidentally.
2) `Net.load` should return a correct python class(Model or Sequential) rather than `KerasLayer` as we cannot use `fit` or `compile` for this type.
=> Fix Net.load

pyzoo/zoo/feature/image/imagePreprocessing.py, zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/ImageNetInference.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/Perf.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/Predict.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageChannelScaledNormalizer.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageRandomCropper.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageRandomResize.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSetToSample.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/image/common/ImageModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassifier.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/LabelOutput.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/Reflection.scala, zoo/src/test/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationSpec.scala
- Run calcScales with `resnet-50.bigdl` to get `resnet-50.quantized.bigdl`
- Convert to ZooModel `analytics-zoo_resnet-50-int8_imagenet_0.5.0.model` and add corresponding preprocessor in ImageClassifier.
- ImageNetInference example for accuracy test.
- Perf for performance test. Throughput should be correct accoriding to @i8run 
- Predict example, which is the same as ImageClassification except here we use int8 model.
Here for BigDL int8 example: https://github.com/intel-analytics/BigDL/tree/branch-0.8/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/mkldnn/int8
=> Support ResNet50-int8 model in ImageClassifier

zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala
Top1Accuracy is Accuracy(correct: 37902, count: 50000, accuracy: 0.75804)
Top5Accuracy is Accuracy(correct: 46357, count: 50000, accuracy: 0.92714)
Overall preprocessing latency is <2ms around 1.8ms.
=> Change RandomResize to Resize in ResNet50 preprocessor

zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/ImageNetEvaluation.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/Predict.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageResize.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala
- In ImageResize, resizeMode and useScaleFactor don't take effect.
- Change back to RandomResize... since @wzhongyuan said there's accuracy difference.
- Change Imagecodec to LOAD_IMAGE_COLOR so that both RGB and gray images can be supported by the model.
=> Bug fix for Resize and change imagecodec in vnni predict

zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/Predict.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/README.md
If use localMode, batch size is always 4, which is too small.
Opened an issue in BigDL: https://github.com/intel-analytics/BigDL/issues/2820
=> Add sc to VNNI predict example

pyzoo/test/zoo/tfpark/test_tfpark_estimator.py, pyzoo/test/zoo/tfpark/test_tfpark_model.py, pyzoo/zoo/pipeline/api/net/tf_optimizer.py, pyzoo/zoo/tfpark/estimator.py, pyzoo/zoo/tfpark/model.py
fixed #1281
In the keras case, if user set `clipNorm` and/or `clipValue` in tf.keras.Optimizers, these values will be set automatically.
In the estimator case, user use
```
estimator.set_constant_gradient_clipping(min, max)
estimator.set_gradient_clipping_by_l2_norm(clip_norm)
```
=> Support gradient clipping in TFPark

docs/docs/APIGuide/Ray/rayonspark.md, docs/docs/PythonUserGuide/install.md, docs/docs/PythonUserGuide/run.md, docs/mkdocs.yml, pyzoo/dev/release/release.sh, pyzoo/setup.py, pyzoo/test/zoo/ray/integration/ray_on_yarn.py, pyzoo/test/zoo/ray/test_ray_on_local.py, pyzoo/zoo/common/nncontext.py, pyzoo/zoo/ray/util/raycontext.py, pyzoo/zoo/ray/util/spark.py
- Add more doc
- Add spark_conf to init_spark_on_yarn to append more options for the sparkcontext creation.
- Add extra_paras to RayContext to append more options for the raylets creation.
=> Enhance Ray on spark

pyzoo/test/zoo/pipeline/api/test_torch_net.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchNet.scala
BigDL Tensor offset starts from 1 by default.
fix issue https://github.com/intel-analytics/analytics-zoo/issues/1477
=> [Pytorch] correct offset for inference

docs/docs/DeveloperGuide/python.md, docs/docs/PythonUserGuide/install.md, docs/docs/PythonUserGuide/run.md, docs/mkdocs.yml, pyzoo/dev/build.sh, pyzoo/dev/release.sh
- Add local build pip script and website guide.
- Add IDE development guide.
- Update some style errors in Python User Guide.
Fix #1447
=> Add Developer Guide for Python users

pyzoo/test/zoo/common/__init__.py, pyzoo/test/zoo/common/test_util.py, pyzoo/zoo/common/utils.py, pyzoo/zoo/pipeline/api/net/tf_optimizer.py, zoo/src/main/scala/com/intel/analytics/zoo/common/PythonZoo.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/Reflection.scala
Setting core number in Engine can control the number of model replica in each node.
This is a temporary support and more user friendly api will be added after pr #1488 
Example Usage:
Say you running on a spark cluster with executor core number is 28, and you want to run two tensorflow model on each executor and each of the model using 14 threads.
Then you can you can do the following to achieve this:
1. export OMP_NUM_THREADS=14 before submitting spark job
2. set core number to change the value in engine and make DistriOptimizer only copy 2 model in each executor.
```python
from zoo.common import set_core_number
set_core_number(core_num)
```
3. set the session_config parameter in TFOptimizer to make each model using 14 threads
```
TFOptimizer.from_loss(..., …
```
=> Support setting core number from python side

zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala
fix #1511 
As cdh will convert the spark env to shell script, but we set a illegal name.
Manual test on CDH 6.2.
=> fix cdh6.2 on yarn

zoo/src/main/scala/com/intel/analytics/zoo/models/image/common/ImageModel.scala, zoo/src/test/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationSpec.scala
If the input is empty, throw an error message before calling model.predictImage.
=> Clarify errormsg in ImageModel.scala

pyzoo/zoo/feature/common.py, zoo/src/main/scala/com/intel/analytics/zoo/common/Optim.scala, zoo/src/main/scala/com/intel/analytics/zoo/common/ZooTrigger.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/ImageNet2012.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/Options.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/README.md, zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/Train.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/CensusWideAndDeep.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/WideAndDeepExample.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/pmem/NativeArray.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/Estimator.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/estimator/DistriEstimatorSpec.scala
With incremental training, we can use less DRAM during the training.
The training workload is like this:
1. Persist origin data on disk
2. Sample a piece of data to memory
3. train these cached samples
4. unpersist these cached samples
5. Goto 2.
=> Incremental Training for imagenet

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
Unit Tests of this fix should be implemented mocking HDFS or other FileSystem. For now, this feature its not implemented in any test and do it in this fix its out of task scope. In a future it should be tested propertly.
=> Fix storage of Preprocessing objects in other filesystems

docs/docs/ProgrammingGuide/pytorch.md, pyzoo/test/zoo/pipeline/api/test_torch_net.py, pyzoo/zoo/examples/pytorch/inference/README.md, pyzoo/zoo/examples/pytorch/inference/__init__.py, pyzoo/zoo/examples/pytorch/inference/predict.py, pyzoo/zoo/examples/pytorch/train/Lenet_mnist.py, pyzoo/zoo/examples/pytorch/train/SimpleTrainingExample.py, pyzoo/zoo/examples/pytorch/train/resnet_finetune/resnet_finetune.py, pyzoo/zoo/pipeline/api/net/torch_criterion.py, pyzoo/zoo/pipeline/api/net/torch_net.py
Add doc for Pytorch, and update an example.
=> pytorch doc and example update.

pyzoo/zoo/pipeline/api/net/tf_optimizer.py
Gives more flexibility if the mapping from keras optimizer to bigdl optimizer is not totally complete.
For example, learning rate scheduler can't be handled by `TFOptimizer.to_bigdl_optim_method(optim_method)`, and in this case, alternatively, users can directly pass in a BigDL optim_method as a workaround.
=> Option to add optim_method when creating TFOptimizer from_keras

zoo/pom.xml, zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/resnet/TrainImageNet.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/resnet/Utils.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/common/MTSampleToMiniBatch.scala
1. add multi thread sample to minibatch
2. apply MTSampleToMiniBatch to resnet50
=> add multi thread sample to minibatch

apps/anomaly-detection/anomaly-detection-nyc-taxi.ipynb
The notebook uses StandardScaler and stores it under variable name min_max_scaler, which is confusing.
=> Fix confusing scaler variable name

docs/docs/APIGuide/PipelineAPI/nnframes.md, pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py, pyzoo/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearningExample.py, pyzoo/zoo/pipeline/nnframes/nn_classifier.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/pmem/NativeArray.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/python/PythonNNFrames.scala
Could be very helpful for training with enormous training data, before this we always cache data in mem.
=> NNFrames: support caching training data on Disk

pyzoo/zoo/examples/pytorch/train/resnet_finetune/README.md, pyzoo/zoo/examples/pytorch/train/resnet_finetune/resnet_finetune.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextPredictor.scala, zoo/src/main/scala/com/intel/analytics/zoo/models/common/Ranker.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Predictor.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchNet.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
ModelBroadcast will set weights to empty tensor(not null).
When clone model in executor, this unnecessary updateWeightNative will lead to out of bound access as this weights is an empty tensor. Just remove it to fix the NaN problem.
=> fix pytroch on yarn model output is NaN

docs/docs/ProgrammingGuide/image-classification.md
Change the link
"https://github.com/intel-analytics/zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala" to "https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala" in analytics-zoo/docs/docs/ProgrammingGuide/image-classification.md.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/1569
=> Update doc link of image classification documentation

pyzoo/zoo/examples/streaming/objectdetection/README.md, pyzoo/zoo/examples/streaming/objectdetection/image_path_writer.py, zoo/src/main/scala/com/intel/analytics/zoo/common/Utils.scala, zoo/src/main/scala/com/intel/analytics/zoo/examples/streaming/objectdetection/README.md
* Fix Invalid cross-device link in image_path_writer.py.
* Fix HDFS filesystem closed issue in ImagePathWriter and StreamingObjectDetection.
* Modify document.
=> [Backport] Fix invalid cross-device and filesystem closed issues in Streaming examples

pyzoo/zoo/examples/tensorflow/tfpark/README.md
=> improve TFPark readme

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
* Replace OpenVINO related decompression output with one line log info.
* Remove unnecessary `ls`.
=> [Backport] Reduce openvino debug logs

docs/docs/PythonUserGuide/install.md, pyzoo/setup.py
Also update doc to guide users to install bigdl 0.9.1 manually as a fix.
=> [backport 0.6] Upgrade bigdl python dependency to 0.9.1

scripts/analytics-zoo-base.sh, scripts/jupyter-with-zoo.sh, scripts/pyspark-shell-with-zoo.sh, scripts/spark-shell-with-zoo.sh, scripts/spark-submit-python-with-zoo.sh, scripts/spark-submit-scala-with-zoo.sh
Support adding option which is a string with spaces, e.g. `--option "a b c"`.
Iterating $* will result
```
--option
a
b
c
```
Iterating $@ will result
```
--option
a
b
c
```
Iterating "$*" will result
```
--option a b c
```
Iterating ”$@" will result
```
--option
a b c
```
=> Start script support adding option which is a string with spaces

pyzoo/zoo/feature/common.py, zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/pmem/FeatureSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonFeatureSet.scala, zoo/src/test/scala/com/intel/analytics/zoo/feature/FeatureSetSpec.scala
It is more common to iterate a dataset in sequential order than to random sample with replacement.
=> Support iterate a dataset in sequential order when training

pyzoo/test/zoo/automl/model/test_Seq2Seq.py, pyzoo/test/zoo/automl/model/test_VanillaLSTM.py, pyzoo/test/zoo/automl/pipeline/test_time_sequence.py, pyzoo/zoo/automl/feature/time_sequence.py, pyzoo/zoo/automl/model/Seq2Seq.py, pyzoo/zoo/automl/model/VanillaLSTM.py, pyzoo/zoo/automl/model/abstract.py, pyzoo/zoo/automl/model/time_sequence.py, pyzoo/zoo/automl/pipeline/time_sequence.py
- fix bug of predict_with_uncertainty: uncertainty value is not reverse transformed.
- add MCDropout for seq2seq model and UTs
- change interface for model.predict and pipeline.fit: add mc option
- fix bug of test pipeline predict function while input a list of data frames: sometimes UT fails on pd.Dataframe.equals(). And it works well with assert_frame_equal()
=> [Automl]fix bug of predict_with_uncertainty and add MCDropout for seq2seq model

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/python/PythonEstimator.scala
It wrong to use `Some.apply` to construct a `Option` if the value might be a `null`.
`val a = Some[SomeType](null)` will return a Some with value null. `a.get` will not throw an exception, but `a.map(_.someAction)` will throw a NPE.
The correct way is to use `Option.appy`
=> [Bug Fix] Fix estimator NPE problem

pyzoo/setup.py
Restrict to 0.6.6 may be too much.
According to @respecteverything the problem of 0.7.4 is not reproduce-able.
=> Relax ray version for pip

zoo/src/main/scala/com/intel/analytics/zoo/common/PythonZoo.scala
reuse jtensor's float array.
To float tensor, `map` will clone a new float array, we can reuse the origin float array rather than clone a new one.
=> reuse Jtensor's float array

zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala
use rng instead of Random in itemid's random.
Current random `val iid = Math.max(ran.nextInt(itemCount), 1)` is not a uniform distribution, one has `2/itemCount`'s possibility and, itemCount's possibility is 0%.
=> use rng instead of Random in itemid's random and fix the distribution.

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
* Replace zoo.common.Utils.readBytes with java.nio.file.Files.readAllBytes.
=> Avoid Distributed OpenVINO from reading from HDFS

apps/recommendation-wide-n-deep/wide_n_deep.ipynb
This is unnecessary and may cause performance overhead.
repartition(4) the assumption of 4 cores locally is also not reasonable.
=> Remove repartition in wide and deep notebook

scripts/cluster-serving/cluster-serving-start
=> [backport] Fix yarn cluster serving bigdl.jar missing error (#1940)

docs/docs/APIGuide/TFPark/tf-dataset.md, pyzoo/test/zoo/tfpark/test_tf_dataset.py, pyzoo/zoo/tfpark/tf_dataset.py
Fix #1898 
Usage
```python
rdd = sc.range(0, 1000)
df = rdd.map(lambda x: (DenseVector(np.random.rand(20).astype(np.float)),
x % 10)).toDF(["feature", "label"])
train_df, val_df = df.randomSplit([0.7, 0.3])
dataset = TFDataset.from_dataframe(train_df,
feature_cols=["feature"],
labels_cols=["label"],
batch_size=32,
validation_df=val_df)
model = KerasModel(get_keras())
model.fit(dataset)
```
Limitations:
1. only support scalar or vector types
2. only support numeric types
=> Support pyspark.sql.Dataframe in TFDataset

pyzoo/test/zoo/ray/integration/ray_on_yarn.py, pyzoo/test/zoo/ray/integration/test_yarn_reinit_raycontext.py, pyzoo/test/zoo/ray/test_ray_on_local.py, pyzoo/test/zoo/ray/test_reinit_raycontext.py
The previous code is not running in parallelism, as ray.get is a blocking operation.
Update in this PR in order not to mislead others.
=> Fix ray get in related unit tests

pyzoo/zoo/util/engine.py
Fix #1991 
This is unnecessary as discussed in the above issue.
=> Remove warning for finding jar

docs/docs/DockerUserGuide/index.md
I think most user would not need to build the docker image from scratch, so I **1. move "How to use docker image" section to the front** and **2. add a section describing how to pull the image from docker hub**.
=> Restructure analytics zoo docker document

zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/PostProcessing.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/TensorUtils.scala, zoo/src/test/scala/com/intel/analytics/zoo/serving/PostProcessingSpec.scala
This PR outputs the ndarray type of Tensor, e.g. [[1,2],[3,4]]
For object detection, we can use this type of output. But..
We are currently use top-N 1D Tensor filter by default, if using this one by default, we have to modify our quick start example, and add that filter in config file.
Thus I only updated the API but have not given entrance to this method. Maybe when we have more types of output and we can review how to set the entrance here.
=> Cluster Serving output Tensor to ndarray string

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetSpec.scala
Currently, there are three ways to load a savedmodel into TFNet.
1. providing both input and output names
2. providing the tag and signature defined in the savedmodel
3. using default tag and signature defined in the savdemodel
Sometimes, user only know the input or only know the output names.
Support passing only input or only output, and find the other one in the default signature
```scala
TFNet.fromSavedModel(modelPath, inputs=null, outputs=Array("output:0"))
```
or
```scala
TFNet.fromSavedModel(modelPath, inputs=Array("input:0"), outputs=null)
```
Minor modifications in the TFNet loading code.
=> Support loading savedmodel by only providing inputs or outputs

pyzoo/zoo/ray/util/raycontext.py
Currently, `RayContext.init()` will wait at least 13 seconds before start. The current flow is
1. if `task_id == 0`, first sleep 5 seconds, then start ray master, then sleep 8 seconds.
2. if `task_id != 0`, first sleep 8 seconds, then start ray slaves, then sleep 5 seconds.
So, there is a 3 seconds gap to make sure ray slaves is started after ray master is started. 
This 3 seconds gay might be too long for a small cluster and might not be enough for a large cluster. And there are also 10 seconds sleep time does not seem to be useful.
We can put a barrier between master start and slave start, e.g.
```python
def map_func(iter):
if task_id == 0:
start_ray_master()
tc.barrier()
if task_id != 0:
start_ray_slave()
```
1. existing unit tests
2. manually tested it on yarn cluster
=> [Fix issue #2150] Remove waiting in Ray init

pyzoo/zoo/examples/tensorflow/freeze_saved_model/README.md, pyzoo/zoo/examples/tensorflow/freeze_saved_model/__init__.py, pyzoo/zoo/examples/tensorflow/freeze_saved_model/freeze.py
This example demonstrates how to transform a TensorFlow saved model into a frozen model that can be used by TFNet.
```bash
python freeze.py --saved_model_path /path/to/saved_model --output_path /path/to/tfnet
```
=> Add example for transform a saved model to a frozen model

pyzoo/test/zoo/automl/regression/test_time_sequence_predictor.py, pyzoo/test/zoo/ray/mxnet/test_mxnet_gluon.py, pyzoo/test/zoo/ray/test_ray_on_local.py, pyzoo/test/zoo/ray/test_util.py, pyzoo/test/zoo/zouwu/test_auto_ts.py, pyzoo/zoo/ray/util/raycontext.py, pyzoo/zoo/ray/util/utils.py
Fix #2154
1. Use ray.init() and ray.shutdown() directly for spark local. Spark only restricts cpu resources in this case,
2. Some code clean and refactor. Previously the code is too messy. For example, labels and extra-params overlap, API not clear, etc.
=> Refactor RayContext

pyzoo/dev/release.sh
@jason-dai as @yangw1234 meets error in #2204 
Cluster Serving will switch to flink in few days and new summary would be support, so I think we could use this old version, and write new summary support for cluster serving.
=> pip install deleted tensorflow dependency tmp fix

pyzoo/zoo/util/engine.py
This PR improves the error message when the files specified in BIGDL_JRAS does not exists.
This error is not uncommon when developing using IDE.
=> Raise exception when the files in BIGDL_JRAS does not exist

pyzoo/zoo/common/nncontext.py, pyzoo/zoo/util/spark.py
Sometimes we need to upload other files besides a virtual environment package, such as config files, data files, and others. 
This PR make init_spark_on_yarn support this requirement.
```
sc = init_spark_on_yarn(
hadoop_conf="/opt/work/hadoop-2.7.2/etc/hadoop",
conda_name="yang-horovod",
additional_archive="/opt/work/client/yang/hyperseg.zip#hyperseg",
extra_executor_memory_for_ray="2g", **other_args)
```
=> Support adding additional archives in init_spark_on_yarn

make-dist.sh
java version check will throw "Require a java version not lower than 1.7" when java version is not in form 1.x, e.g. java 11.0.7.
=> fix java version check failure when java version is not in format 1.x,e.g java 11.01

pyzoo/test/zoo/orca/data/test_spark_pandas.py, pyzoo/zoo/examples/orca/data/spark_pandas.py, pyzoo/zoo/orca/data/shard.py
In RayDataShard, `transform_shard` requires a function whose first argument is the data and return new data, e.g.
```
def func(data, *args):
data['count'] += 1
return data
```
In SparkDataShard, `transform_shard` requires a function that return a single argument function to make the transform.
```
def func(*args):
def transform(data):
data['count'] += 1
return data
return transform
```
I think the ray version is easier to use.
=> align tranform_shard api between spark and ray

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchLoss.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModelSpec.scala
Because TorchLoss's input from scala are Float tensor currently, so for the loss like CrossEntropyLoss who require long-type target, we can use a lossFunction to wrap the Loss:
```
def lossFunc(input, target):
return nn.CrossEntropyLoss().forward(input, target.flatten().long())
```
=> remove long in torchloss

docs/docs/DockerUserGuide/index.md
fix #2365
The default memory for container on windows and mac is 2g, this might be too small for many example and notebooks.
=> remind user to increase docker memory

pyzoo/zoo/serving/server.py, zoo/src/test/resources/serving/cluster-serving-enqueue-test, zoo/src/test/resources/serving/offline-benchmark
code is mainly clean up, which need no focus, basic logic is as following.
push 1 image to trigger lazy loading, then push 10000
to get benchmark in one query (not including time window), check output log in taskmanager
to get benchmark across multiple queries (including time window), check the time elapsed from first query to the last.
=> Cluster Serving benchmark throughput ready for Int8

pyzoo/test/zoo/orca/data/test_spark_pandas.py, pyzoo/zoo/orca/data/__init__.py, pyzoo/zoo/orca/data/shard.py
Implement save_pickle and load_pickle for SparkXShards.
Related Issue: https://github.com/analytics-zoo/orca/issues/29
=> Orca save_pickle and load_pickle for XShards on Spark

pyzoo/test/zoo/orca/learn/mxnet/test_mxnet_gluon.py, pyzoo/zoo/ray/raycontext.py
RayContext.get() to retrieve the current active RayContext.
@jason-dai The OrCreate part is not necessary for now and I don't include it here.
Get the RayContext is enough for usage.
=> Get the current RayContext

pyzoo/test/zoo/orca/learn/spark/test_estimator_for_spark.py, pyzoo/zoo/orca/learn/tf/estimator.py
Usage:
```python
data_shard = data_shard.transform_shard(transform)
est = Estimator.from_graph(
inputs=[model.user, model.item],
labels=[model.label],
loss=model.loss,
optimizer=tf.train.AdamOptimizer(),
metrics={"loss": model.loss})
result = est.evaluate(data_shard)
assert "loss" in result
print(result)
```
Fix https://github.com/analytics-zoo/orca/issues/51
=> support evaluate in orca tf estimator

pyzoo/zoo/serving/client.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkInference.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/preprocessing/PreProcessing.scala, zoo/src/test/scala/com/intel/analytics/zoo/serving/InferenceSpec.scala, zoo/src/test/scala/com/intel/analytics/zoo/serving/PreProcessingSpec.scala
One feature lost for this PR, inferenceModel could not print batchSize anymore, user should print them by themselves before input the Tensor to model.
=> Infernce Model string support of TFNet

pyzoo/test/zoo/orca/data/test_ray_pandas.py, pyzoo/test/zoo/orca/data/test_spark_pandas.py, pyzoo/zoo/orca/data/pandas/preprocessing.py
Fix Xshards on Ray test case, add required options for read_json.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/2438
For read_csv/read_json, add path empty/invalid handling.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/2436
=> Fix read_json arguments in Xshards Ray test and add path empty/invalid handling

pyzoo/test/zoo/orca/learn/mxnet/test_mxnet_spark_xshards.py, pyzoo/zoo/orca/learn/mxnet/mxnet_runner.py, pyzoo/zoo/orca/learn/mxnet/mxnet_trainer.py
Previously using kv.rank to get the data doesn't mean the worker ips are sorted.
Tested on YARN cluster.
=> Fix MXNet data locality

pyzoo/zoo/common/nncontext.py, pyzoo/zoo/util/spark.py
Usage:
```python
from zoo import ZooContext, init_nncontext
ZooContext.log_output = True
sc = init_nncontext()  # or init_spark_on_local, init_spark_on_yarn
```
Then training logs will be printed to the current notebook.
Tested manually:
=> Support redirecting jvm output to python process (when using notebook)

pyzoo/zoo/examples/tensorflow/tfpark/keras/keras_ndarray.py, pyzoo/zoo/tfpark/__init__.py
It is not uncommon for our users to install a incorrect version of TensorFlow and face some weird error message. This PR tries to solve this problem.
If users install TF 1.x, they will receive an warning such as
```
######################### WARNING ##########################
Analytics Zoo TFPark has only been tested on TensorFlow 1.15.0, but your current TensorFlow installation is 1.14.0.
##############################################################
```
If users install TF 2.x, they will receive an error, e.g.
```
RuntimeError: Analytics Zoo TFPark only supports TensorFlow 1.15.0, but your current TensorFlow installation is 2.2.0
You can export ANALYTICS_ZOO_TF_CHECK=false to disable this check.
```
Users can export ANALYTICS_ZOO_TF_CHECK=false to disable this check
Fix #2456 
manually …
=> Add tensorflow version check

pyzoo/test/zoo/pipeline/utils/test_utils_onnx.py
UT random fails due to small tolerance while comparing array values
=> Fix UT random fails

pyzoo/zoo/orca/data/shard.py
Previously if putting into plasma tasks fail, each spark retrial would create a new object id to put the data. This would lead to memory leak if only some tasks fail.
Generate an ObjectID for each partition beforehand for plasma.
In case tasks fail, spark would retry to put into plasma. If the target id already exists, we suppose that the task on that partition succeeds and does nothing. Otherwise, still use this id to put into plasma.
=> Generate object ids for plasma error handling

zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/AUC.scala
Same as https://github.com/intel-analytics/BigDL/pull/3011
AUC would change the output and target, which would influence other validation metrics.
=> Fix AUC changing output and target

pyzoo/test/zoo/pipeline/api/torch/test_torch.py, pyzoo/zoo/pipeline/api/torch/torch_model.py, zoo/src/main/resources/spark-analytics-zoo.conf, zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonFeatureSet.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModelSpec.scala
support bn when TorchModel export model to pure pytorch
As setExtraParameters is final in BigDL's AbstractModule, so I find a way to walk around.
We can remove this walk around when update to bigdl 0.11.0.(https://github.com/intel-analytics/BigDL/pull/3014 remove the final)
=> support bn when TorchModel export model to pure pytorch

pyzoo/zoo/pipeline/api/keras/optimizers.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/optimizers/Adam.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/optimizers/AdamWeightDecay.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
add weightdecay to adam, this implement is similiar with [pytorch adam](https://pytorch.org/docs/stable/_modules/torch/optim/adam.html#Adam)
=> add weightdecay to Adam

pyzoo/test/zoo/orca/data/test_pandas_backend.py, pyzoo/test/zoo/orca/data/test_spark_backend.py, pyzoo/zoo/orca/data/pandas/preprocessing.py, pyzoo/zoo/orca/data/utils.py
- Fix #2521 do not use Scala HadoopFS API to list local file paths.
- Do not filter files by its suffix as neither Spark or Pandas does this. We just pass all the files to Spark or Pandas and let them handle or raise an error. For pandas during read time error would be raised if the file format is wrong. For spark seems it can read anything, but when you do transformation on the resulting DataFrame, the error would be raised if the file format is not as expected.
=> Fix Orca read file path

pyzoo/test/zoo/orca/data/test_spark_backend.py, pyzoo/zoo/orca/data/pandas/preprocessing.py
Support read_csv/read_json with 'names' of partial columns. If 'names' is not for all columns, it should be of the same length of 'usecols'.
Change 'dtype' type conversion from spark dataframe to pandas dataframe in mapPartitions to support numpy types.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/2569
Tested on mastercard code.
=> Support read_csv/read_json with 'names' of partial columns

pyzoo/test/zoo/orca/data/conftest.py, pyzoo/test/zoo/orca/data/test_pandas_backend.py, pyzoo/test/zoo/orca/data/test_spark_backend.py, pyzoo/test/zoo/orca/learn/ray/mxnet/test_mxnet_spark_xshards.py, pyzoo/test/zoo/zouwu/test_model_forecast.py, pyzoo/zoo/common/nncontext.py, pyzoo/zoo/orca/__init__.py, pyzoo/zoo/orca/common.py, pyzoo/zoo/orca/data/pandas/preprocessing.py, pyzoo/zoo/orca/data/shard.py
- Move properties to OrcaContext.
@jason-dai Since log_output is used in init_nncontext, it can't be moved to OrcaContext?
- Make spark the default backend for reading csv/json files.
- When error occurs, add a message to hint users to switch backend.
=> Add OrcaContext and make spark default read file backend

docs/docs/ClusterServingGuide/ProgrammingGuide.md, scripts/cluster-serving/cluster-serving-start
I am considering use 2 scripts (for deploy-start and inference-only), provided on github, that user could run this script and the script will download, initialize.. to get all env prepared.
=> Cluster Serving install doc

pyzoo/test/zoo/ray/test_ray_on_local.py, pyzoo/zoo/ray/raycontext.py
Fix https://github.com/intel-analytics/analytics-zoo/issues/2594
num of executors and executor cores may not be detected in spark conf; allow users to input manually.
=> Fix Spark configurations in RayContext

zoo/src/main/scala/com/intel/analytics/zoo/serving/http/FrontEndApp.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/http/actors.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/http/domains.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/Conventions.scala
update http to add pass secret and salt to cluster serving
user can put secret and salt to redis without redis-cli
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2747)
=> update http to add pass secret and salt to cluster serving

pyzoo/test/zoo/orca/data/test_spark_backend.py, pyzoo/test/zoo/orca/learn/spark/test_estimator_keras_for_spark.py, pyzoo/zoo/orca/data/pandas/__init__.py, pyzoo/zoo/orca/data/pandas/preprocessing.py
Read parquet files and return xshards of Pandas dataframe.
Related issue: https://github.com/analytics-zoo/orca/issues/65
=> Orca add read_parquet support

pyzoo/zoo/ray/raycontext.py
Workers' output is duplicated n times if n ray nodes are started on the same machine.
See ray issue https://github.com/ray-project/ray/issues/10392 for details.
This pr works around it by killing the redundant log_monitor processes.
=> fix duplicated ray worker logs

pyzoo/test/zoo/orca/data/test_spark_backend.py, pyzoo/zoo/orca/data/pandas/preprocessing.py
Add columns options in read_parquet if user only needs a few columns among so many columns.  Load all columns and cache to xshards may have memory issue.
Add repartition option if user does not want to repartition when num_partition on xshards < node_number. For big dataset, repartition may take a lot effort if users just do prediction/evaluation.
=> Add columns and repartition parameter in read_parquet

pyzoo/zoo/pipeline/api/torch/torch_model.py, pyzoo/zoo/pipeline/api/torch/zoo_pickle_module.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModel.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModelSpec.scala
TorchModel add load inference only model from scala
And change model serialization from CloudPickleSerializer to `Torch.save` and `Torch.load`.
=> TorchModel add load inference only model from scala

pyzoo/zoo/automl/config/recipe.py
AutoML: LSTMGridRandomRecipe is not considering all the features combination. #2840
LSTMGridRandomRecipe (in recipe.py) is not considering all the features combination as np.random.randint method's upper(high) limit is non-inclusive. This is causing the exclusion of all-features combination.
np.random.randint method's upper(high) limit is non-inclusive, so adding one to high, to make it inclusive
=> #2840 - AutoML: LSTMGridRandomRecipe is not considering all the features combination

pyzoo/test/zoo/orca/learn/ray/mxnet/conftest.py, pyzoo/test/zoo/orca/learn/ray/pytorch/conftest.py, pyzoo/zoo/common/nncontext.py, pyzoo/zoo/orca/common.py, pyzoo/zoo/ray/raycontext.py, pyzoo/zoo/util/spark.py
- Fix issues for running RayOnSpark on k8s cluster (described below). (Tested on PyTorchTrainer and MXNet Estimator)
- Add inline docs for init_spark_on_k8s.
- Some code updates of Ray related. Move init_executor_gateway to ray_ctx.init().
- Wrap k8s into init_orca_context.
=> Fix RayOnSpark for k8s and add docs

pyzoo/zoo/serving/client.py, scripts/cluster-serving/cluster-serving-cli, scripts/cluster-serving/cluster-serving-start, scripts/cluster-serving/cluster-serving-stop, scripts/cluster-serving/config.yaml, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/SparkStreamingClusterServing.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/SparkStructuredStreamingClusterServing.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkRedisSink.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/pipeline/RedisIO.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingManager.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/Conventions.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/SerParams.scala, zoo/src/test/scala/com/intel/analytics/zoo/serving/InferenceSpec.scala
The most want-to in this PR is to remove the `running` flag, often when the error is raised, the flag is not removed, and next time we have to manually remove the flag, otherwise serving could not start. This is bad.
could use `cluster-serving-cli list` to list jobs
use `cluster-serving-stop jobname` to stop specific job
use `cluster-serving-stop` to stop all jobs
add shutdown hook and `running` flag is not used anymore
=> Cluster Serving multiple model management

pyzoo/zoo/util/spark.py
Fix 
```
jep.JepExecption:ImportError: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found(required by libtorch_python.so)
```
Add executor env LD_LIBRARY_PATH to use libstdc++.so in conda.
=> add ld_library_path to init spark on yarn

pyzoo/dev/run-pytests-jep.sh, pyzoo/test/zoo/pipeline/api/torch/test_torch.py, pyzoo/test/zoo/pipeline/api/torch/test_torch_optim.py, pyzoo/zoo/common/nncontext.py, pyzoo/zoo/examples/pytorch/train/mnist/main.py, pyzoo/zoo/pipeline/api/torch/__init__.py, pyzoo/zoo/pipeline/api/torch/torch_optim.py, pyzoo/zoo/util/utils.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModel.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchOptim.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TorchOptimSpec.scala
1. Add TorchOptim who wraps pytorch optimizer to bigdl's optimmethod.
2. Change init_spark_on_yarn's conda-pack to  shell command `conda pack` , as we can unset PYTHONHOME in the subprocess.
3. set pythonhome in driver when `init_nncontext()`, `init_spark_on_yarn()`, `init_spark_on_standalone()` and `init_spark_on_k8s()`
=> Torchoptim, wrap pytorch optimizer to bigdl's optimmethod

pyzoo/zoo/orca/common.py
Since stop_orca_context is added at exit time, if the user program finishes successfully and they manually call stop_orca_context, stop_orca_context would be called for one more time at exit time. So we shouldn't call `sc.getOrCreate()` all the time as this would create a new sc.
For yarn mode, it would through the following error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.io.FileNotFoundException: File file:/tmp/tmptoj600uh/python_env.tar.gz#python_env does not exist
```
As the tmp conda file is removed when sc is created for the first time.
=> Fix stop_orca_context

pyzoo/zoo/automl/config/recipe.py, pyzoo/zoo/automl/impute/__init__.py, pyzoo/zoo/automl/impute/abstract.py, pyzoo/zoo/automl/impute/impute.py, pyzoo/zoo/automl/regression/xgbregressor_predictor.py, pyzoo/zoo/automl/search/RayTuneSearchEngine.py
1. add LastFillImpute
2. add FillzeroImpute
3. initial version of support ray tune imputation
=> support ray tune imputer

pyzoo/zoo/common/nncontext.py
https://github.com/intel-analytics/analytics-zoo/issues/2899
As used by a community user, init_spark_standalone can also work with multiple nodes cluster if the environment is ready on all nodes. Update the docs to clarify this.
=> Update doc for init_spark_standalone

pyzoo/test/zoo/zouwu/autots/test_auto_ts.py, pyzoo/test/zoo/zouwu/model/forecast/test_lstm_forecaster.py, pyzoo/test/zoo/zouwu/model/forecast/test_mtnet_forecaster.py
=> add predict and evaluate result check in zouwu tests

pyzoo/zoo/orca/learn/tf2/tf_runner.py
TF distributed will try to sent data through proxy, this may result an error.
Add cluster nodes to no_proxy env.
=> Add cluster node ip to no_proxy env for tf2 backend

docs/docs/ProgrammingGuide/pytorch.md
Two issues are fixed:
1. The example code previously could not run since `TorchModel.from_pytorch` does not accept a `loss` parameter
[Source code](https://github.com/intel-analytics/analytics-zoo/blob/b246b435923ef1a1cbdf1f191d5087cd155aa00a/pyzoo/zoo/pipeline/api/torch/torch_loss.py#L42)
2. Previously the code blocks are horribly indented -- every line had four spaces at the beginning so they could not run under a naive copy and paste. **This might exist in other places and I would suggest creating a script to check!!!**
=> Fix example code

pyzoo/dev/run-pytests-horovod-pytorch, pyzoo/dev/run-pytests-ray, pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_horovod_backend.py, pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py, pyzoo/test/zoo/orca/learn/ray/pytorch/test_pytorch_trainer.py, pyzoo/zoo/orca/learn/pytorch/training_operator.py
- If target is of size (batch, 1) and predicted of size (batch, ), the accuracy calculation `target == predicted` would result in a tensor of size (batch, batch), which is wrong.
- Also accuracy for binary classification is not supported previously.
- Handle cases where output or target has extra singleton dimensions.
- Add unit tests to cover this.
=> Fix validate in Orca PyTorch Estimator

docs/docs/ProgrammingGuide/AutoML/forecasting.md, docs/docs/Zouwu/tutorials/Autots.md
=> Add automl installation doc

apps/image-similarity/image-similarity.ipynb
To fix https://github.com/intel-analytics/analytics-zoo/issues/2563
=> image-similarity notebook dimension match error when core_num equals to batch_size

pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_horovod_backend.py, pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py, pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py, pyzoo/zoo/orca/data/ray_rdd.py, pyzoo/zoo/orca/data/shard.py, pyzoo/zoo/orca/data/utils.py, pyzoo/zoo/orca/learn/mxnet/mxnet_runner.py, pyzoo/zoo/orca/learn/mxnet/mxnet_trainer.py, pyzoo/zoo/orca/learn/pytorch/estimator.py, pyzoo/zoo/orca/learn/pytorch/pytorch_ray_estimator.py, pyzoo/zoo/orca/learn/pytorch/torch_runner.py
Similar to MXNet, support SparkXShards of RDD[dict of numpy] where each records contains 'x'  for features and 'y' for labels. Features and labels can be ndarray, list/dict/tuple of ndarrays.
This PR first focuses on training fit. If the implementation is OK, then I will modify validate as well.
Also fixes #3048 Add documentation that batch size should be batch size per worker.
=> Support SparkXShards for PyTorch Ray Estimator

docs/docs/ClusterServingGuide/APIGuide.md, docs/docs/ClusterServingGuide/ProgrammingGuide.md, zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/ClusterServingInference.scala
@jason-dai I have updated the dependencies and configuration in this PR.
For example to provide, we currently have only one example, which is a TF ResNet50 example in docker quick start.
To add Pytorch example, we could add it in docker quick start, or provide a separate directory with all examples including TF, OpenVINO, Pytorch?
=> Cluster Serving doc update for pytorch and API update

pom.xml, zoo/pom.xml
When set `-P spark_2.4+`, our build will include some useless jars.
=> cleanup jar-with-dependency.jar 

docs/docs/ClusterServingGuide/OtherFrameworkUsers/README.md, docs/docs/ClusterServingGuide/OtherFrameworkUsers/l08c08_forecasting_with_lstm.py, docs/docs/ClusterServingGuide/OtherFrameworkUsers/l10c03_nlp_constructing_text_generation_model.py, docs/docs/ClusterServingGuide/OtherFrameworkUsers/transfer_learning.py
add tf input examples of converting TFDataSet and Tokenizer to ndarray
TFDataSet example url: https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l08c08_forecasting_with_lstm.ipynb
Tokenizer example url: https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l10c03_nlp_constructing_text_generation_model.ipynb
ImageDataGenerator example url: https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/images/transfer_learning.ipynb
=> add tf input examples of converting TFDataSet, Tokenizer and ImageDataGenerator to ndarray

pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py, pyzoo/zoo/orca/learn/pytorch/torch_runner.py, pyzoo/zoo/orca/learn/pytorch/training_operator.py
#3184 
Fix for torch_distributed backend.
=> Fix missing DDP in torch distributed

pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_horovod_backend.py, pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py, pyzoo/zoo/orca/learn/horovod/horovod_ray_runner.py
=> fix horovod pytorch estimator

pyzoo/zoo/examples/orca/learn/pytorch/cifar10/README.md, pyzoo/zoo/examples/orca/learn/pytorch/cifar10/__init__.py, pyzoo/zoo/examples/orca/learn/pytorch/cifar10/cifar10.py, pyzoo/zoo/examples/run-example-tests-jep.sh
This is the example of Pytorch Cifar10 tutorial. Follow the original logic, there are sampled graphs showing training data and testing data, trainning on Orca bigdl backend and calculating test accuracy on test data. The part for test accuracy on every class is currently unsupported. The evaluation function in estimator only returns a total accuracy and the predict function in estimator is not implement yet
=> Orca Pytorch cifar10 example bigdl backend

pyzoo/zoo/automl/feature/time_sequence.py
**Goal**:
Fix issue #2623.
**Change log**:
I add the conditional attribute `n_features_in_` setting in `_scale` function.
**Reason**:
This might be faster and better for future support.
**Reference**:
In sklearn version 0.23.X, it set a strict check on the attribute `n_features_in_`, while we only save `mean_` and `scale_` for the `StandardScaler`. This is the main reason for issue #2623.   
In sklearn version 0.24.X, this strict check is eliminated for stateless estimator(e.g. `StandardScaler`), still it might be added back later. see discussions sklearn pr 18011 and [here](https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep010/proposal.html)
=> automl feature transform sklearn >=0.23 support

pyzoo/zoo/common/nncontext.py
Fix #3365 
Change to something like this:
=> update the message when setting log_output after init context and change it to a warning

readthedocs/source/doc/Orca/QuickStart/orca-pytorch-quickstart.md
According to previous changes of orca pytorch,  validation metrics should be specified in the `Estimator.from_torch` function instead of the `fit` or `evaluate` function. The quick start document is updated in this PR to align with the [notebook](https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist.ipynb).
=> Update orca pytorch quick start

scripts/cluster-serving/cluster-serving-start, scripts/cluster-serving/config.yaml, zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/InferenceBaseline.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/MockSinglePipelineBaseline.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/OpenVINOBaseline.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkInference.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkRedisSource.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala, zoo/src/test/scala/com/intel/analytics/zoo/serving/models/OpenVINOModelSpec.scala, zoo/src/test/scala/com/intel/analytics/zoo/serving/models/TensorflowModelSpec.scala
@jason-dai user can just set `model_num`, model number in serving pipeline  and `core_num`, core number each model would use.
To make this more readable, in code, `coreNum` is renamed to `thrdPerModel`
The whole pipeline parallelism will be controlled by `model_num`, this would be consistent with inference model design
=> Cluster Serving auto set flink parallelism

docs/docs/Orca/orca-pytorch-estimator.md, docs/docs/Orca/orca-pytorch-quickstart.md, pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py, pyzoo/zoo/automl/model/tcmf/local_model_distributed_trainer.py, pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py, pyzoo/zoo/examples/orca/learn/pytorch/fashion_mnist/fashion_mnist.py, pyzoo/zoo/examples/orca/learn/pytorch/super_resolution/super_resolution.py, pyzoo/zoo/orca/learn/pytorch/estimator.py, pyzoo/zoo/orca/learn/pytorch/pytorch_ray_estimator.py, pyzoo/zoo/orca/learn/pytorch/torch_runner.py, readthedocs/source/doc/Orca/Overview/data-parallel-processing.md
This PR relates to issue #3446 
Similar to `TF2`, after the changes, the program expects users to input `batch_size` in `fit`, `evaluate` and `predict` functions instead of in `config`. I also removed 
```py
if "batch_size" not in config:
```
in `torch_runner.py` because this may lead the program to ignore the input `batch_size`, for example, in the `validate` function.
In addition, the `data_creator` function should now expect 2 inputs: `config` and `batch_size`. Please have a look if the changes are ok. Thanks
=> batch_size related changes for Orca PyTorch

pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py, pyzoo/zoo/orca/learn/bigdl/estimator.py, pyzoo/zoo/orca/learn/metrics.py, pyzoo/zoo/orca/learn/pytorch/estimator.py, pyzoo/zoo/orca/learn/pytorch/pytorch_metrics.py, pyzoo/zoo/orca/learn/pytorch/pytorch_ray_estimator.py, pyzoo/zoo/orca/learn/pytorch/torch_runner.py, pyzoo/zoo/orca/learn/pytorch/training_operator.py
For pytorch and bigdl estimators, they both use a unified orca metrics interface specified at estimator construction. Inside estimator, each estimator will get the implementation metrics class according to their backend ("pytorch" or "bigdl" currently).
For pytorch ray estimators, currently we use the pytorch lightning implementation. **Users need to install pytorch lightning package to use this feature.**
```python
from zoo.orca.learn.metrics import Accuracy
estimator = Estimator.from_torch(model=model_fn,
optimizer=get_optimizer,
loss=nn.BCELoss(),
metrics=Accuracy(),
config={"lr": 1e-2},
workers_per_node=workers_per_node,
backend="torch_distributed")
```
=> Implement metrics for pytorch ray estimator

pyzoo/zoo/common/nncontext.py
When submitting orca tf2 tasks to spark, the system gives error as follows:
```py
Traceback (most recent call last):
File "/home/jinglei/zoo-tutorials/orca/tf2/tmp_test.py", line 183, in <module>
init_orca_context(cluster_mode="local", cores=4)  # run in local mode
File "/home/jinglei/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/common.py", line 194, in init_orca_context
File "/home/jinglei/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/common/nncontext.py", line 53, in init_spark_on_local
File "/home/jinglei/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/util/spark.py", line 57, in init_spark_on_local
File …
```
=> Fix orca initialization issue in spark

pyzoo/test/zoo/automl/model/test_tcn.py, pyzoo/zoo/automl/model/base_pytorch_model.py, pyzoo/zoo/automl/model/model_builder.py, pyzoo/zoo/automl/search/ray_tune_search_engine.py, pyzoo/zoo/examples/automl/plugin_model_demo.py, pyzoo/zoo/zouwu/model/forecast/tcn_forecaster.py
Major changes:
1. When RaySearcher find out that a customized model is used, then it will call the save directly.
2. Add a restore method for modelbuilder, so that user can restore easily from the checkpoint even if they stop the search midway.
3. Change the plugin model demo and show the usage of this new easy save/load
Some minor changes:
1. Change base_pytorch_model's evaluation method's param from metric to metrics
2. Add a comparation between searched model and manually fixed hyperparam model, which demos that searched model has a better result.
=> Give the plug-in customized model a better way to save/load

docs/readthedocs/source/doc/Orca/QuickStart/orca-keras-quickstart.md, docs/readthedocs/source/doc/Orca/QuickStart/orca-pytorch-quickstart.md, docs/readthedocs/source/doc/Orca/QuickStart/orca-tf-quickstart.md, docs/readthedocs/source/doc/Orca/QuickStart/orca-tf2keras-quickstart.md, docs/readthedocs/source/doc/UserGuide/notebooks.md
before use remote image links in quick start pages, which may cause connection errors if no VPN.
now use local image instead( readthedocs/image)
demo: https://testhelendoc.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf-quickstart.html
and 2 images shows correct in the page if without VPN
=> use local images in quick start pages

pyzoo/test/zoo/orca/learn/spark/test_estimator_for_bigdl.py, pyzoo/zoo/orca/learn/bigdl/estimator.py, pyzoo/zoo/pipeline/nnframes/nn_classifier.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/python/PythonNNFrames.scala, zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimatorSpec.scala
Related issue: #3507
When call `estimator.evaluate` to deal with a dataFrame, it will call scala method `internalEval` to process data.
Usage:
```python
result = est.evaluate(data=validationDF, batch_size=16, feature_cols="image")
```
As a result it returns a Jlist of EvaluatedResult, which will be converted to a python dict like:
```
2021-03-16 00:04:27 INFO  DistriOptimizer$:1759 - Top1Accuracy is Accuracy(correct: 8, count: 26, accuracy: 0.3076923076923077)
{'Top1Accuracy': 0.3076923191547394}
```
Working Progress:
And if there is any spark official evaluating trait or base class you know, pls leave your comments, thanks!
=> Implement nn_estimator evaluating method in Orca Bigdl estimator

pyzoo/test/zoo/orca/learn/test_metrics.py, pyzoo/zoo/orca/learn/pytorch/pytorch_metrics.py
Modify MAE and MSE to support float labels.
Remove the line making the type of `preds` the same as `target`. (reference: https://pytorch.org/docs/stable/generated/torch.sub.html#torch.sub
https://pytorch.org/docs/stable/tensor_attributes.html#type-promotion-doc
)
Add and run unit test.
=> Fix Orca pytorch metrics MAE and MSE

docs/docs/Orca/orca-pytorch-estimator.md, docs/docs/Orca/orca-tf-estimator.md, pyzoo/test/zoo/orca/learn/spark/test_estimator_for_spark.py, pyzoo/test/zoo/orca/learn/spark/test_estimator_keras_for_spark.py, pyzoo/zoo/orca/learn/tf/estimator.py
This PR relates to issue #3345. Current modification logic for tf estimator:
1. Add `load_tf_checkpoint` 
2. Remove implementation of `load` in super class; implement `load` in `TensorFlowEstimator` and `KerasEstimator` seperately
3. Change `load_orca_checkpoint` and remove `load_latest_orca_checkpoint`
Other things to be changed related to orca `save` and `load` methods:
1. Update `zoo.orca.learn.bigdl.estimator` and `zoo.orca.learn.openvino.estimator`
2. Add tests for `save` and `load` (tf estimator)
=> save and load methods for orca tf estimator

docs/docs/Orca/orca-pytorch-estimator.md, pyzoo/test/zoo/orca/learn/jep/test_pytorch_estimator_for_spark.py, pyzoo/zoo/orca/learn/pytorch/estimator.py
After the issue #3606 is fixed, the model returned by `bigdl.nn.layer.Model.load` can be converted back to `TorchModel` now. So we can now update the function `load_orca_checkpoint` to load `self.model` as a `TorchModel` type. In this way the `get_model` method will no longer be influenced by `load_orca_checkpoint`.
Summary of changes:
1. Update `load_orca_checkpoint` for Orca PyTorch estimator
2. Update `load` related document (according to discussion in the previous PR)
3. Fix a minor typo: `_hanle_data_loader`
4. Update test for `load_orca_checkpoint`
=> Orca PyTorch estimator update (fix `load_orca_checkpoint`)

pyzoo/zoo/orca/learn/bigdl/estimator.py, pyzoo/zoo/orca/learn/openvino/estimator.py, pyzoo/zoo/orca/learn/pytorch/estimator.py
Remove `load_latest_orca_checkpoint` and modify `load_orca_checkpoint` to include the functionality of loading the latest checkpoint. Main modifications in this PR is related to Orca BigDL estimator.
There's also a minor update in the comment of orca pytorch estimator for consistency.
=> `load_orca_checkpoint` related updates for Orca BigDL / OpenVINO estimator

pyzoo/test/zoo/zouwu/model/forecast/test_tcn_forecaster.py
`mse_onnx = forecaster.evaluate(test_data[0], test_data[1])`
on https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/zouwu/model/forecast/test_tcn_forecaster.py#L86
=> TCNForecaster test bugfix

docs/readthedocs/source/doc/Ray/Overview/ray.md
The directory structure changed and makes the link invalid.
=> Fix link in RayOnSpark user guide

docs/docs/Zouwu/API/TCNForecaster.md, pyzoo/test/zoo/zouwu/model/forecast/test_tcn_forecaster.py, pyzoo/zoo/zouwu/model/forecast/model/base_pytorch_model.py, pyzoo/zoo/zouwu/model/forecast/model/tcn.py, pyzoo/zoo/zouwu/model/forecast/tcn_forecaster.py
1. Add a `PYTORCH_REGRESSION_LOSS_MAP` for future use in built-in model
2. add loss option for TCNForecaster
=> add loss option for TCNForecaster

docs/readthedocs/source/conf.py, docs/readthedocs/source/index.rst
enable python API doc in readthedocs website after passing test
1) update index.rst
2) update conf.py
test demo: https://testhelendoc.readthedocs.io/en/latest/doc/PythonAPI/Orca/orca.html
=> enable python API doc in readthedocs website after passing test

pyzoo/zoo/orca/learn/mpi/__init__.py, pyzoo/zoo/orca/learn/mpi/mpi_estimator.py, pyzoo/zoo/orca/learn/mpi/mpi_runner.py, pyzoo/zoo/orca/learn/mpi/mpi_train.py, pyzoo/zoo/orca/learn/mpi/utils.py
@jason-dai Take a look at the initial implementation.
__MPIRunner__ is a general class for running any mpi script. (Probably we can support some optimized configurations in the later stage, refer to https://github.com/intel/intel-extension-for-pytorch/blob/master/intel_pytorch_extension_py/launch.py
__MPIEstimator__ is an Estimator for Pytorch distributed training with MPI. (No extra Python script is needed in this case) Fit accepts Spark DataFrames and put into plasma, and would create a dataloader based on numpy for users to iterate. Users have the flexibility to define init_func, train_func and validate_func, if not specified there are default ones. Users can also input data_creator if they wish.
Verified on dlrm e2e workload on clx cluster and 4-socket cpx.
=> Add MPI support for Pytorch distributed training

pyzoo/zoo/automl/model/base_pytorch_model.py
if onnx/onnxruntime is not installed, the error message will show through a runtime error.
=> Change automl onnx import error message to runtime error

pyzoo/test/zoo/automl/model/test_base_pytorch_model.py, pyzoo/zoo/automl/model/base_pytorch_model.py
Fixed bug detail:
In base pytorch model, `fit_eval` method failed to set self.onnx_model_built to False，if user call fit_eval -> [any onnx method] -> fit_eval -> [any onnx method]，the second onnx method call will use the old onnx model build for the first onnx method call.
=> Onnx pytorch base incremental training bug

pyzoo/test/zoo/automl/searcher/test_ray_tune_search_engine.py, pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_keras.py, pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_pytorch.py, pyzoo/test/zoo/zouwu/config/test_recipe.py, pyzoo/zoo/automl/recipe/base.py, pyzoo/zoo/automl/regression/base_predictor.py, pyzoo/zoo/automl/search/ray_tune_search_engine.py, pyzoo/zoo/examples/automl/plugin_model_demo.py, pyzoo/zoo/examples/orca/automl/autoxgboost/AutoXGBoostRegressor.py, pyzoo/zoo/zouwu/config/recipe.py, pyzoo/zoo/zouwu/feature/time_sequence.py
User used to need including `all_available_features` in `search_space` while customizing a `recipe`. It might be a little confusing since users may only search with their customized models and don't need feature at all.
To improve usability, we remove the parameter and disable feature selection for now. And we will enable feature selection later with a better way to pass necessary parameters to search space in recipe.
=> Remove feature selection and use all features as default

pyzoo/test/zoo/automl/searcher/test_ray_tune_search_engine.py, pyzoo/zoo/automl/common/parameters.py, pyzoo/zoo/automl/logger/tensorboardxlogger.py, pyzoo/zoo/automl/regression/base_predictor.py, pyzoo/zoo/automl/search/ray_tune_search_engine.py
Changes in this PR:
- pyzoo/test/zoo/automl/searcher/test_ray_tune_search_engine.py:
1. Test if specified metric name is used in results
2. Test if metrics' mode (max/min) is correctly handled in `stop`, `_get_sorted_trials ` and `_get_best_result`
- pyzoo/zoo/automl/common/parameters.py:
1. No need for fixed `REWARD_METRIC`
- pyzoo/zoo/automl/logger/tensorboardxlogger.py:
1. Add a `logo_str` param to decoupling AutoTS and AutoML
- pyzoo/zoo/automl/regression/base_predictor.py:
1. Change all the mode parameters from "max" to specified metric's mode
- pyzoo/zoo/automl/search/ray_tune_search_engine.py:
1. Change all the metric name from "reward_metric" to specified metric name
2. Change `tune.track` to `tune.report`
3. Make sure the `best.ckpt` is saved for the iteration with best metric
4. …
=> Automl Searcher metric refactor

docs/docs/release-docs.md, docs/docs/release-download.md, docs/readthedocs/source/doc/release.md
update 0.10.0 release download links in 
1.  readthedocs website: update docs/readthedocs/source/doc/release.md
2. github.io: update /docs/docs/release-download.md and  /docs/docs/release-docs.md
PS: This PR also need be backport to branch 0.10.0
=> update 0.10.0 release download links for doc websites(readthedocs and github.io)

pyzoo/zoo/zouwu/config/recipe.py
Add a build-in recipe for Seq2SeqPytorch model for third party search.
Since it is a recipe for third party model search, input_feature_num, output_feature_num and future_seq_len is required.(#3497)
=> Add lstms2s recipe for third-party search

zoo/src/main/scala/com/intel/analytics/zoo/common/PythonInterpreter.scala, zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
disable message like:
```
2021-04-23 01:43:37 INFO  DistriOptimizer$:651 - Cache thread models... done
2021-04-23 01:43:37 INFO  DistriOptimizer$:161 - Count dataset
[Stage 7:>                                                          (0 + 1) / 1]Warn: jep.JepException: <class 'StopIteration'>
at jep.Jep.exec(Native Method)
at jep.Jep.exec(Jep.java:478)
at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:108)
at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:107)
at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:107)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
at …
```
=> disable exception jep

pyzoo/test/zoo/zouwu/model/anomaly/test_model_anomaly.py
related to #3933 
It seems that we compare the estimators' value to a theoretical value. Relaxing the threshold will significantly reduce the random fail.
=> relax the threshold to fix anomaly detection ut random fail

zoo/src/main/scala/com/intel/analytics/zoo/serving/http/FrontEndApp.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/http/domains.scala, zoo/src/main/scala/com/intel/analytics/zoo/serving/http/serializers.scala
Add support of multi-model HTTP serving.
- route GET "/models": return JSON list of all model meta info with all versions
- route GET "/models/[MODEL_NAME]": return JSON list of models with all versions with model name [MODEL_NAME]
- route GET "/models/[MODEL_NAME]/versions/[MODEL_VERSION]": return JSON of model info with name [MODEL_NAME] and version [MODEL_VERSION]
- route POST "/models/[MODEL_NAME]/versions/[MODEL_VERSION]/predict": request body should be in JSON format.  See examples below. Result is also returned in JSON format.
**Sample output format of model info:**
```
[ {
"modelName" : "second-model",
"modelVersion" : "1.0",
"redisHost" : "localhost",
"redisPort" : "6381",
"redisInputQueue" : "serving_stream",
"redisOutputQueue" : "cluster-serving_serving_stream:",
"timeWindow" : …
```
=> add support of multi-model

docker/hyperzoo/README.md, docs/readthedocs/source/doc/UserGuide/k8s.md
add k8s configuration in the readme of hyperzoo
add 7 notes of run az examples on k8s:
1. user can use NFS to save local files
2. user can add temp-dir to get worker log
3. user should specify "step-per-epoch" and "validation-steps" when run more then one executor
4. add memory when "RayActorError" occurs
5. "spark.kubernetes.container.image.pullPolicy" needs to be specified as "Always"
6. when use NFS in k8s cluster, NFS should be set in driver and executor
7.  if more than 1 executor, remove extra_params = {"temp-dir": "/tmp/ray/"}
=> update hyperzoo doc and k8s doc

docs/readthedocs/requirements-doc.txt, docs/readthedocs/source/conf.py, docs/readthedocs/source/doc/Chronos/Overview/chronos.md, docs/readthedocs/source/doc/PythonAPI/AutoML/automl.rst, docs/readthedocs/source/doc/PythonAPI/Chronos/forecasters.rst, docs/readthedocs/source/doc/PythonAPI/Friesian/feature.rst, docs/readthedocs/source/doc/PythonAPI/Zouwu/forecasters.rst, docs/readthedocs/source/index.rst, pyzoo/zoo/chronos/model/forecast/lstm_forecaster.py, pyzoo/zoo/chronos/model/forecast/mtnet_forecaster.py, pyzoo/zoo/chronos/model/forecast/seq2seq_forecaster.py, pyzoo/zoo/chronos/model/forecast/tcmf_forecaster.py, pyzoo/zoo/chronos/model/forecast/tcn_forecaster.py, pyzoo/zoo/chronos/model/forecast/tfpark_forecaster.py, pyzoo/zoo/orca/automl/auto_estimator.py, pyzoo/zoo/orca/learn/pytorch/estimator.py, pyzoo/zoo/orca/learn/tf/estimator.py
- Add two sections **AutoML API** and **ChronosForecasters API** in  readthedocs
- Make sure all parameters and return values has a description
- Add a code example for each class
- Add an intro for each class
You can preview the doc [here](https://yuyin-analytics-zoo.readthedocs.io/en/latest/doc/PythonAPI/AutoML/automl.html)
=> Add Python api docs for Auto ML and Chronos Forecasters

pyzoo/test/zoo/chronos/data/test_tsdataset.py, pyzoo/test/zoo/chronos/data/utils/test_roll.py, pyzoo/zoo/chronos/data/tsdataset.py, pyzoo/zoo/chronos/data/utils/roll.py
add rolling feature rather than global feature for each rolling sample. The method should be called after scale and before roll. And window_size should be the same as lookback.
```python
tsdata.gen_dt_feature()\
.scale(scaler)\
.gen_rolling_feature(settings="minimal", window_size=5)\
.roll(lookback=5, horizon=4, id_sensitive=True)
```
Need huge amount of testing and code cleaning
=> Add rolling feature by tsfresh in TSDataset

docker/hyperzoo/Dockerfile, docker/zoo/Dockerfile
=> fixed 4086 and 4083 issues

pyzoo/test/zoo/automl/model/test_base_keras_model.py, pyzoo/test/zoo/automl/model/test_base_pytorch_model.py, pyzoo/test/zoo/chronos/autots/test_auto_ts.py, pyzoo/test/zoo/chronos/model/test_Seq2Seq_pytorch.py, pyzoo/test/zoo/chronos/model/test_tcn.py, pyzoo/zoo/automl/model/abstract.py, pyzoo/zoo/automl/model/base_keras_model.py, pyzoo/zoo/automl/model/base_pytorch_model.py, pyzoo/zoo/automl/search/ray_tune_search_engine.py, pyzoo/zoo/chronos/model/MTNet_keras.py, pyzoo/zoo/chronos/model/Seq2Seq.py, pyzoo/zoo/chronos/model/VanillaLSTM.py, pyzoo/zoo/chronos/model/prophet.py, pyzoo/zoo/chronos/model/tcmf_model.py, pyzoo/zoo/orca/automl/xgboost/XGBoost.py
This PR includes
- Change return value from `eval_result` value to dictionary of {`metric_name`: `eval_result`} in `fit_eval` for all `automl.BaseModel` inheritors 
- Change default `metric` value in `BaseKerasModel` from "mse" to `None`. If use leaves the `metric` in `fit_eval` as default, we will use the compiled metric name and value as evaluation result if user only used one metric to compile the model. We will raise error if user used multiple metrics in `model_creator` and didn't specify a specific target metric for `AutoEstimator` to optimize.
- Change default `metric` value in `BasePytorchModel` from "mse" to `None`.
=> Change return value of fit_eval and change default metric values in automl.BaseModel

pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_keras.py, pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_pytorch.py, pyzoo/test/zoo/orca/automl/xgboost/test_auto_xgb.py, pyzoo/test/zoo/orca/automl/xgboost/test_xgbregressor.py, pyzoo/zoo/automl/model/base_keras_model.py, pyzoo/zoo/automl/model/base_pytorch_model.py, pyzoo/zoo/automl/search/ray_tune_search_engine.py, pyzoo/zoo/orca/automl/auto_estimator.py, pyzoo/zoo/orca/automl/xgboost/XGBoost.py
User customized metric function support for `AutoEstimator.from_keras`, `AutoEstimator.from_torch`, `AutoXGBClassifier`, `AutoXGBRegressor`
Support input function for `metric` in `AutoEstimator.fit()`, `AutoXGBClassifier.fit()`, `AutoXGBRegressor.fit()`
```python
def pyrmsle(y_true, y_pred):
y_pred[y_pred < -1] = -1 + 1e-6
elements = np.power(np.log1p(y_true) - np.log1p(y_pred), 2)
return float(np.sqrt(np.sum(elements) / len(y_true)))
auto_est = AutoEstimator.from_keras(model_creator=model_creator)
auto_est.fit(data=data,
validation_data=validation_data,
search_space=search_space,
n_sampling=4,
epochs=1,
metric=pyrmsle,
metric_mode="min")
auto_est.get_best_model()
```
=> Support customized metric function in AutoEstimtor and AutoXGBoost

pyzoo/test/zoo/chronos/data/test_tsdataset.py, pyzoo/zoo/chronos/data/tsdataset.py
since user need to call this function now. We will make it to be `unscale_numpy` rather than internal version
=> Rename tsdataset unscale_numpy function

pyzoo/test/zoo/chronos/autots/model/test_auto_arima.py, pyzoo/test/zoo/chronos/model/test_arima.py
Add Random Seed for Generating ARIMA Unittest Data.
Work-around solution to irregular random data that leads to LU Decomposition Error as in #4170.
=> Add Random Seed for Generating ARIMA Unittest Data

pyzoo/test/zoo/orca/data/test_ray_xshards.py, pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py, pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py, pyzoo/zoo/orca/data/ray_xshards.py, pyzoo/zoo/orca/learn/pytorch/pytorch_ray_estimator.py, pyzoo/zoo/orca/learn/tf2/estimator.py, pyzoo/zoo/orca/learn/utils.py
This PR also removes `process_spark_xshards` in tf2 estimator and use `zoo.orca.data.utils.process_spark_xshards` for both pytorch estimator and tf2 estimator.
=> Support numPartition < num workers for RayXShards

pyzoo/test/zoo/chronos/autots/experimental/test_autotstrainer.py, pyzoo/zoo/chronos/autots/experimental/__init__.py, pyzoo/zoo/chronos/autots/experimental/autotsestimator.py, pyzoo/zoo/chronos/autots/experimental/tspipeline.py
1. Rename AutoTSTrainer to AutoTSEstimator and other changes
2. Simplify imports namespace, anyone who wants to use AutoTSEstimator will only import
- `from zoo.chronos.data import TSDataset`
- `from zoo.chronos.autots.experimental import AutoTSEstimator, TSPipeline` (experimental will be removed later)
=> Rename experimental AutoTSTrainer to AutoTSEstimator and corr uts

pyzoo/zoo/ray/raycontext.py
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/ray/raycontext.py#L394-L429
@jason-dai When user input num_ray_nodes and ray_node_cpu_cores do not match spark, we are already reporting a warning.
=> Add assert error message when launching Ray for non-barrier mode

docs/readthedocs/source/doc/Chronos/Overview/chronos.md
We need an ugly workaround to include a .md link in sphinx document.
Please refer to https://github.com/miyakogi/m2r/issues/41 and https://stackoverflow.com/questions/52496591/sphinx-and-markdown-md-links
Thus I currently use our old document link and a warning text to workaround.
We will add the page to readthedoc later.
The pr is related to #4095.
=> Chronos user guide broken link fix

pyzoo/zoo/chronos/data/tsdataset.py, pyzoo/zoo/chronos/data/utils/roll.py
1. Change rolling kernal from ~O(time series length) to ~O(lookback)
2. Use group by to speed up the code
3. speed up ~250X on baidu traffic dataset
related to #4186
=> TSDataset rolling method speed up

pyzoo/zoo/orca/common.py
If start ray on driver with more than 0 cores, the TFRunner or other actors would run on driver which is not expected.
So not pass driver cores values when calling ray_context.init()
=> Always keep driver core as 0 when start ray on driver in cluster mode

pyzoo/zoo/friesian/feature/table.py, pyzoo/zoo/friesian/feature/utils.py, zoo/src/main/scala/com/intel/analytics/zoo/friesian/python/PythonFriesian.scala, zoo/src/test/scala/com/intel/analytics/zoo/friesian/FriesianSpec.scala
Used by recsys preprocessing and it is probably a useful feature to assign more frequent values smaller ids.
=> Add order_by_freq for generate_string_idx

pyzoo/zoo/friesian/feature/table.py
Default to be Long, change to int
=> Fix datatype when creating stringindex from dict

pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py, pyzoo/zoo/orca/learn/openvino/estimator.py, pyzoo/zoo/orca/learn/tf2/estimator.py, pyzoo/zoo/orca/learn/utils.py, pyzoo/zoo/util/utils.py
Logically, only tf2 estimator and pytorch ray estimator can support string input. BigDL backends use Sample and string is not supported.
=> Add string type option in convert_row_to_numpy

pyzoo/zoo/automl/model/base_pytorch_model.py
This will give a 1.15X speed up for the pytorch prediction.
=> Chronos: change inference code in pytorch base model to use no_grad

zoo/pom.xml
Reverts intel-analytics/analytics-zoo#4410
=> Revert "grpc pom fix to exclude scala2.11 only support 2.12(spark 3.0)"

pyzoo/test/zoo/chronos/data/test_tsdataset.py, pyzoo/test/zoo/chronos/data/utils/test_roll_dataset.py, pyzoo/zoo/chronos/data/tsdataset.py, pyzoo/zoo/chronos/data/utils/roll_dataset.py, pyzoo/zoo/chronos/data/utils/utils.py
This PR implements a more convenient and memory-friendly API: `to_torch_loader` for the case of `TSDataset` rolling and convert to `PyTorch DataLoader`.
```python
tsdata.roll(lookback=320, horizon=40)
x, y = tsdata.to_numpy()
dataloader = DataLoader(TensorDataset(torch.from_numpy(x).float(), torch.from_numpy(y).float()),
batch_size=32,
shuffle=True)
```
The rolled numpy (x, y) must be hold in memory. 
However, the rolled numpy could be much time bigger than the original df. In baidu traffic dataset's case (lookback=96, horizon=16), the original df is ~6G and the output numpy is ~100G.
```python
dataloader = tsdata.to_torch_loader(batch_size=32, roll=True, look_back=320, horizon=40)
```
We use customized torch `Dataset`, which is lazy, so it doesn't require much memory.
If user have …
=> Add TSDataset.to_torch_data_loader

pyzoo/test/zoo/friesian/feature/test_table.py, pyzoo/zoo/friesian/feature/table.py
Add union column support for generate string index.
The column input for generate string index can include {'src_cols": [xx, yy], 'col_name': zz}
=> Add union column support for generate string index

pyzoo/zoo/ray/raycontext.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala
This PR is mainly aimed at solving the issue of the zombie processes on worker nodes in cluster mode after being interrupted. related issue #4487 
This PR has been tested on yarn with ctrl + C in different stages, and no zombie processes are founded again.
=> Kill process group instead of iterator of pids in shutdown hook

pyzoo/test/zoo/chronos/model/forecast/test_lstm_forecaster.py, pyzoo/test/zoo/chronos/model/forecast/test_seq2seq_forecaster.py, pyzoo/test/zoo/chronos/model/forecast/test_tcn_forecaster.py, pyzoo/zoo/automl/model/base_pytorch_model.py, pyzoo/zoo/chronos/model/forecast/base_forecaster.py
Still finding if we need to add more settings to this method.
effectiveness validation is also on-going
api doc: https://junweitestdoc.readthedocs.io/en/onnx-improvements-threads/doc/PythonAPI/Chronos/forecasters.html#zoo.chronos.model.forecast.base_forecaster.BasePytorchForecaster.build_onnx
=> Chronos: forecaster onnx sess thread limit and other settings

python/nano/recipe/build.sh, python/nano/setup.py, python/nano/src/bigdl/nano/pytorch/vision/datasets/datasets.py
This pr makes nano load libturbojpeg.so from wheel package itself instead of conda package, with which we can directly run `pip install bigdl-nano` without `conda install Pyturbojpeg`.
=> Add pip wheel support of Turbojpeg

python/nano/src/bigdl/nano/pytorch/accelerators/__init__.py, python/nano/src/bigdl/nano/pytorch/accelerators/ipex_torchfunctional.py
For the development of ipex is on going, there are some operations or functions we can not call directly [#4600](https://github.com/intel-analytics/analytics-zoo/pull/4600#discussion_r699773873).
This pr provides a way for us to apply any workaround as an alternative if it fixs the issue temporarily. The replacement takes place whenever ipex accelerator is imported, in another word `use_ipex` is specfied as true in Trainer, but it will not affect default behaviors.
=> Bigdl nano: Makes torch function replacement a plugin-like operation

pyzoo/test/zoo/automl/logger/test_tensorboardlogger.py, pyzoo/zoo/automl/logger/__init__.py, pyzoo/zoo/automl/logger/tensorboardlogger.py, pyzoo/zoo/automl/search/ray_tune_search_engine.py
This can solve the OLD & critical sort malfunction in Tensorboard #3426
- `torch.utils.tensorboard` is more stable than `tensorboardx`
- they have nearly the same interface
=> Chronos: change logger to torch tensorboard interface from tensorboardx

pyzoo/zoo/ray/process.py, pyzoo/zoo/ray/ray_daemon.py, pyzoo/zoo/ray/raycontext.py, pyzoo/zoo/ray/utils.py, zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala
While running `RayOnSpark` in cluster, if the spark executor is killed abruptly (e.g. killed by yarn due to memory-deficiency), the ray processes will keep running until meet further error (e.g "No module named zoo"). However, the ray processes should be killed immediately if the spark executor died. 
#4425 
1. This PR added a ray daemon to watch spark executor and kill ray processes after the spark executor is died.
2. This PR removes `shutdown_hook` and `clean_fn` in `ProcessMonitor` which are also for killing ray processes. And the functions don't work at all circumstances, such as `core_dump`.
This PR has only been tested on **Linux**.
In both "standalone" mode and "yarn-client" mode:
In "yarn-client" mode, "core dump" after ray initialized has also been tested.
1. Application keeps …
=> Add ray daemon to kill ray processes

python/nano/example/pytorch/pl-finetune/README.md, python/nano/example/pytorch/semantic_segmentation/README.md, python/nano/script/bigdl-nano-init, python/nano/src/bigdl/nano/__init__.py
warning message:
```
WARNING:root:
******************************************************************************************************************************************************
Nano environment variables ['LD_PRELOAD', 'MALLOC_CONF', 'OMP_NUM_THREADS', 'KMP_AFFINITY', 'KMP_BLOCKTIME'] are not set.
Please run `source bigdl-nano-init` to initialize them, or you can prefix `bigdl-nano-init` to the command you run.
Example:
bigdl-nano-init python pytorch-lenet.py --device ipex
******************************************************************************************************************************************************
```
=> Bigdl-Nano: Check environment variables when import this module

zoo/pom.xml
update pom.xml to reduce whl size from 207MB to 160MB.
Remove breeze from jar.
Some dependencies are included by #4717. Just remove them.
=> update pom.xml to reduce whl size

pyzoo/zoo/friesian/feature/table.py
Fix parameters order of gen_string_idx.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/4655
=> Fix parameters order of gen_string_idx

python/dllib/src/setup.py
@jason-dai Which name we will choose to release on PyPI? "BigDL-dllib", "BigDL-nano" or "bigdl-dllib", "bigdl-nano"?
=> unify release bigdl2.0 PyPI project name

ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/start-all-but-flink.sh, ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/taskmanager-deployment.yaml.back, ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/templates/jobmanager-deployment.yaml, ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/templates/master-deployment.yaml
1. Modify start-all-but-flink.sh to avoid check status before job submitted, which can cause a check fail.
2. Add some properties to make the yaml scripts more user-friendly.
=> Modify scripts in realtime cluster serving

pyzoo/test/zoo/friesian/feature/test_table.py, pyzoo/zoo/friesian/feature/table.py, pyzoo/zoo/friesian/feature/utils.py, zoo/src/main/scala/com/intel/analytics/zoo/friesian/feature/Utils.scala, zoo/src/main/scala/com/intel/analytics/zoo/friesian/python/PythonFriesian.scala, zoo/src/test/scala/com/intel/analytics/zoo/friesian/FriesianSpec.scala
move add_value_features to scala side to boost performance.
refactor add_value_features  and reindex to take tables instead of python dicts.
refactor gen_reindex_mapping  to output tables instead of python dicts.
=> refactor add_value_features and reindex using tables instead of dicts

scala/orca/pom.xml, scala/serving/pom.xml
Related PR #4839 
This PR excluded dllib from orca jar and add dllib dependency in serving jar
With PR #4851, orca jar size can be reduced to 130M
=> Exclude dllib from orca jar

python/dllib/test/dev/release/release.sh, python/orca/dev/release/release.sh, scala/orca/pom.xml
Related [comments]( https://github.com/intel-analytics/analytics-zoo/pull/4839#issuecomment-927599056) in PR #4839.
With `make-dist -P linux`, orca jar size reduces from 384M to 276M
=> Add profile for linux and mac in bigdl-orca jar

python/nano/script/bigdl-nano-init, python/nano/setup.py, python/nano/src/bigdl/nano/__init__.py, python/nano/src/bigdl/nano/common/common.py
By default we will use tcmalloc as our memory allocator and jemalloc will also be available.
Usage:
```
bigdl-nano-init python ...  # tcmalloc only
bigdl-nano-init -j python ...  # jemalloc only
bigdl-nano-init -c python ...  # ptmalloc (no optimaztions)
```
=> [Bigdl-Nano] Enable tcmalloc in nano and turn jemalloc as an option

pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py, pyzoo/zoo/util/utils.py
This modification has been tested using  ```pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py``` adding ```test_array_string_input()```.   (I also modified ```test_string_input()```  to adapt a vocabulary.)
results are:
```test_array_string_input()```:
```
[Row(id=0, input=['foo', 'qux', 'bar'], prediction=DenseVector([4.0, 1.0, 2.0])), Row(id=1, input=['qux', 'baz'], prediction=DenseVector([1.0, 3.0]))]
```
```test_string_input()```:
```
[Row(input='foo qux bar', prediction=DenseVector([3.0, 2.0, 5.0, 0.0])), Row(input='qux baz', prediction=DenseVector([2.0, 4.0, 0.0, 0.0]))]
```
test env:
- python3.7
- tensorflow==2.7.0
- ray==1.9.2
=> Support pyspark.sql.types.ArrayType with pyspark.sql.types.StringType elements

zoo/pom.xml
1. `com.fasterxml.jackson.dataformat` contains org.yaml:snakeyaml
https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/pom.xml#L691
<dependency>
<groupId>com.fasterxml.jackson.dataformat</groupId>
<artifactId>jackson-dataformat-yaml</artifactId>
<version>${jackson.version}</version>
</dependency>
3. log4j:log4j does not has version 2.17.1, and it has CVE issue.
=> fix snakeyaml cve issue

pyzoo/zoo/ray/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch-0.10.0-RC1
=> branch-0.10.0-RC1: remove hardcode redis password in raycontext

pyzoo/zoo/ray/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch-0.10
=> branch-0.10: remove hardcode redis password in raycontext

pyzoo/zoo/orca/common.py, pyzoo/zoo/orca/data/ray_xshards.py, pyzoo/zoo/ray/raycontext.py
This submission removes hardcoded redis_password from pyzoo/zoo/ray/raycontext.py from master branch
- if users want to specify redis_password, they can add key value into extra_params to launch ray: extra_params={"redis-password": "xxxxxx"}
- if redis_password is not defined in extra_params, the [default redis password](https://github.com/ray-project/ray/blob/8ba400cf6cd38d6305d950907d0905087a161eb6/python/ray/_private/ray_constants.py#L285) defined in ray will be used.
**Related PR:** https://github.com/intel-analytics/BigDL/pull/5649 https://github.com/intel-analytics/BigDL/pull/7019
=> orca: remove hardcode redis_password from master branch

.github/workflows/bigdl-llm-nightly-release.yml, .github/workflows/llm_unit_tests.yml, python/llm/dev/release.sh, python/llm/setup.py
This submission creates a workflow for nightly releases of bigdl-llm, we have just migrated to ipex-llm, we need to continue releasing bigdl-llm a few days.
=> release bigdl-llm

python/chronos/src/setup.py
Upgrade scikit-learn to 1.5.0 to fix dependabot issue: https://github.com/intel-analytics/BigDL-2.x/security/dependabot/501
=> Upgrade scikit-learn to 1.5.0 to fix dependabot issue

python/chronos/src/setup.py
Unpin scikit-learn version to fix dependabot issue: https://github.com/intel-analytics/BigDL-2.x/security/dependabot/501
=> unpin scikit-learn version to fix dependabot issue

scala/dllib/pom.xml, scala/friesian/pom.xml, scala/orca/pom.xml, scala/ppml/pom.xml, scala/serving/pom.xml
Fix:
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/513
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/514
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/515
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/516
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/517
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/518
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/519
- Dependency1 
- Dependency2
- ...
- Dependency1 and license1
- Dependency2 and license2
- ...
=> fix dependabot alerts
