intel/BigDL

- notebook/example/sentiment.ipynb
Add a jupyter of sentiment classification.
> Add a sentiment jupyter

- transform/vision/src/main/scala/com/intel/analytics/zoo/transform/vision/image/augmentation/ChannelNormalize.scala
- transform/vision/src/main/scala/com/intel/analytics/zoo/transform/vision/image/augmentation/PixelNormalizer.scala
What changes were proposed in this pull request?
1) Add new transformer for Pixel normalizer 
2) Refinement Channel normalizer to expose std params
How was this patch tested?
Local test with img models
> new normalizer

- apps/recommendation/README.md
- apps/recommendation/recommender-explicit-feedback.ipynb
Publish recommendation notebook
Tested under BigDL 0.3 with spark 2.0 and 2.1
> Recommendation

- models/README.md
- models/src/main/scala/com/intel/analytics/zoo/models/imageclassification/util/ImageClassificationConfig.scala
Add quantized models and download links
> Add quantized models

- models/src/main/python/bigdl/zoo/example/ImageClassificationPredict.py
- models/src/main/python/bigdl/zoo/models.py
- models/src/main/scala/com/intel/analytics/zoo/models/Predictor.scala
- models/src/main/scala/com/intel/analytics/zoo/models/imageclassification/example/Predict.scala
- models/src/main/scala/com/intel/analytics/zoo/models/objectdetection/example/Predict.scala
- models/src/main/scala/com/intel/analytics/zoo/models/objectdetection/example/PredictLocal.scala
A simple change to get label map from predictor instead of reading it  separately
Verified by the example itself
> get label map from predictor

- pom.xml
- zoo/pom.xml
add distributionManagement  to publish jars to ossrh
also change names from zoo to analytics-zoo
sample jars are already uploaded, please have a check
https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/zoo/
Jenkins job:
http://172.168.2.101:8080/view/ZOO-NB/job/ZOO-NB-Deploy-SCALA
> add distributionManagement and change to analytics-zoo in pom

- make-dist.sh
- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/test/zoo/pipeline/autograd/test_operator.py
- pyzoo/zoo/pipeline/api/autograd.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- pyzoo/zoo/pipeline/api/keras/models.py
- pyzoo/zoo/pipeline/api/utils.py
- zoo/pom.xml
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/CustomLoss.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/Lambda.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/math.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonAutoGrad.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/autograd/LambdaSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/ZooSpecHelper.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/HighwaySpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/KerasLayerWrapperSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/SimpleRNNSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TrainingSpec.scala
- Support Lambda layer
- Switch the default profile to spark_2.x
https://github.com/intel-analytics/zoo/issues/175 https://github.com/intel-analytics/zoo/issues/144 https://github.com/intel-analytics/zoo/issues/110 
For Model
```
input = Input([2, 3])
lambdaLayer = Lambda(function=lambda x: x + 3.0)
model = Model(input, lambdaLayer(input))
```
For Sequential
```
seq = Sequential()
lambdaLayer = Lambda(function=lambda x: x + 3.0, input_shape=[2, 3])
seq.add(lambdaLayer)
```
> Support Lambda layer

- pyzoo/zoo/examples/autograd/custom.py
- pyzoo/zoo/examples/autograd/customloss_update.py
Ignore the Lambda layer cause it hasn't been merged to master yet.
> Functional api for customized loss

- pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py
- pyzoo/zoo/pipeline/nnframes/nn_classifier.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/python/PythonNNFrames.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNClassifierSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimatorSpec.scala
add setPreprocessing interface for NNModel and NNClassifierModel
> NNFrames: allow nnmodel set proprocessing

- pyzoo/dev/prepare_env.sh
- pyzoo/zoo/__init__.py
- pyzoo/zoo/common/nncontext.py
- scripts/zoo-build-info
- zoo/pom.xml
- zoo/src/assembly/python-zip.xml
- zoo/src/main/scala/com/intel/analytics/zoo/common/CheckVersion.scala
- zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala
- zoo/src/main/scala/com/intel/analytics/zoo/common/Utils.scala
> auto version check

- pyzoo/zoo/__init__.py
- pyzoo/zoo/examples/objectdetection/predict.py
- pyzoo/zoo/feature/image/imagePreprocessing.py
- zoo/src/main/scala/com/intel/analytics/zoo/feature/common/Preprocessing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/Brightness.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/CenterCrop.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ChannelNormalize.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/Hue.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/MatToTensor.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/Resize.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/Saturation.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonImageFeature.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/python/PythonNNFrames.scala
What changes were proposed in this pull request?
1. Add Brightness, Hue, Saturation
2. Transformer api support imageset
How was this patch tested?
manual test
Related links or issues (optional)
https://github.com/intel-analytics/zoo/issues/191
https://github.com/intel-analytics/zoo/issues/192
> transformer api support imageset and add more transformers

- zoo/src/main/scala/com/intel/analytics/zoo/examples/objectdetection/Predict.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/common/ImageConfigure.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/LabelReader.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/ObjectDetectionConfig.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/ObjectDetector.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/Postprocessor.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/objectdetection/Visualizer.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/models/image/objectdetection/ObjectDetectionSpec.scala
Fix https://github.com/intel-analytics/zoo/issues/205
> change object detector package name

- pyzoo/zoo/examples/run-examle-tests.sh
this is try to track all the python example tests in jenkins
it passed the jenkins job:
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests/5/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/159)
> add python example tests

- apps/run-app-tests.sh
this is try to track all the apps tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/170)
> add apps tests

- pyzoo/zoo/__init__.py
Disable version check on worker
> [Bug Fix] Disable version check on worker

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/CommonSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/models/image/objectdetection/ObjectDetectionSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimatorSpec.scala
resolve some build warning: non-variable type argument and postfixOps
https://github.com/intel-analytics/zoo/issues/217
> fix  non-variable type argument and postfixOps warning

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/CustomLoss.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TrainingSpec.scala
Fix https://github.com/intel-analytics/zoo/issues/174
> Support passing loss func in compile Scala

- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/NetSpec.scala
Transfer learning API support dynamic graph
> Transfer learning API support dynamic graph

- apps/run-app-tests.sh
passed http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Python-AppTests/48/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/203)
> refactor the app-tests and fix wrong ftp url

- pyzoo/zoo/common/nncontext.py
- zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala
disable version check by default
> disable version check by default

- docs/docs/nnframes/NNEstimator.md
- pyzoo/zoo/examples/nnframes/imageTransferLearning/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearning.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/run.sh
https://github.com/intel-analytics/zoo/issues/221 
Use only 2000 of the 25000 images in the example.
> update scala NNFrames Transfer learning example

- pom.xml
this is to fix https://github.com/intel-analytics/zoo/issues/236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/220)
> add source plugin to package source code for zoo

- pyzoo/test/zoo/pipeline/autograd/test_operator.py
- pyzoo/zoo/pipeline/api/autograd.py
- pyzoo/zoo/pipeline/api/keras/layers/torch.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonAutoGrad.scala
- get_input_shape
- get_output_shape
- node
- from_node
> Expose more API for Variable on python side

- pyzoo/test/zoo/pipeline/api/keras/test_net.py
- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/zoo/__init__.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- pyzoo/zoo/pipeline/api/net.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/GraphNetSpec.scala
Fix GraphNet and kerasNet submodules bug
> Fix GraphNet and kerasNet submodules bug

- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/test/zoo/pipeline/utils/test_utils.py
- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/models/image/common/image_config.py
- zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TrainingSpec.scala
https://github.com/intel-analytics/zoo/issues/245
https://github.com/intel-analytics/zoo/issues/241
> Enhance get_nncontext and fix bug in ImageConfigure

- docs/docs/models/recommendation/README.md
- docs/docs/models/recommendation/programming-guide.md
- docs/docs/models/textclassification/programming-guide.md
- docs/mkdocs.yml
- pyzoo/zoo/models/recommendation/recommender.py
- pyzoo/zoo/models/recommendation/wide_and_deep.py
- pyzoo/zoo/models/textclassification/text_classifier.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Recommender.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/WideAndDeep.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/textclassification/TextClassifier.scala
https://github.com/intel-analytics/zoo/issues/231
> Website Doc for TextClassifier and Python Recommender

- pyzoo/zoo/examples/nnframes/imageInference/ImageInferenceExample.py
- pyzoo/zoo/pipeline/api/keras/metrics/auc.py
- pyzoo/zoo/pipeline/api/keras/utils.py
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/Predict.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/ImageInferenceExample.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/AUC.scala
This is a following-up PR for https://github.com/intel-analytics/analytics-zoo/pull/235
> Update default value of AUC to 200

- docs/docs/models/imageclassification/README.md
- docs/docs/models/objectdetection/README.md
Remove quantize model link temporary due to quantize bugs.
> remove quantize model link in doc

- pyzoo/dev/check-license
- pyzoo/dev/run-tests
- pyzoo/test/zoo/pipeline/autograd/__init__.py
- pyzoo/test/zoo/pipeline/utils/__init__.py
- pyzoo/zoo/models/image/common/__init__.py
Fix https://github.com/intel-analytics/zoo/issues/234
@dding3 Please have a review. Thanks~
> Check license for python files

- pyzoo/zoo/examples/imageclassification/README.md
- pyzoo/zoo/examples/nnframes/finetune/README.md
- pyzoo/zoo/examples/nnframes/imageInference/README.md
- pyzoo/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
Fix https://github.com/intel-analytics/zoo/issues/199
> update ZOO_HOME to ANALYTICS_ZOO_HOME

- pyzoo/zoo/pipeline/api/keras/layers/torch.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/math.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/GaussianSampler.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/KerasLayerWrapper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/ResizeBilinear.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/GaussianSamplerSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/ResizeBilinearSpec.scala
updated:
KerasLayerWrapper.scala
added:
GaussianSampler.scala
ResizeBilinear.scala
GaussianSamplerSpec.scala
ResizeBilinearSpec.scala
> added GaussianSampler, ResizeBilinear for VAE

- docs/docs/known-issues.md
Fix https://github.com/intel-analytics/zoo/issues/224
> Add numpy.int64 to known issues

- pyzoo/setup.py
- pyzoo/zoo/examples/autograd/__init__.py
- pyzoo/zoo/examples/nnframes/__init__.py
- pyzoo/zoo/examples/nnframes/finetune/__init__.py
- pyzoo/zoo/examples/nnframes/imageInference/__init__.py
- pyzoo/zoo/examples/nnframes/imageTransferLearning/__init__.py
* add packages
* get all packages
> [backport 0.1] Auto get packages in setup.py for pip install (#282)

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
this pr add simple pojo style inference model to analytics-zoo. 
java user can extends the AbstractInferenceModel and predict with java input and get java output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/297)
> add api for inference model

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
need to change loadModel from bigdl to zoo net
> change to Net loadModel

- docs/docs/APIGuide/PipelineAPI/autograd.md
- docs/docs/ProgrammingGuide/autograd.md
Only `mean` added in this PR(more on the way)
> Add doc for autograd

- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/TransferLearning.scala
[issue #261] fix finetune example typo
> [issue #261] fix finetune example typo

- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/TransferLearning.scala
> [issue #261] fix finetune example typo [backport 0.1]

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
this pr is to fix inferncemodel missing input shape
in the future, will change to predict(JTensor) or predict(List<Float>, shape) style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/310)
> fix inferncemodel missing input shape

- pyzoo/dev/diff.py
- pyzoo/test/zoo/models/recommendation/test_neuralcf.py
- pyzoo/test/zoo/models/textclassification/test_textclassifier.py
- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/zoo/models/common/zoo_model.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/common/ZooModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Net.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Flatten.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Input.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/test/scala/com/intel/analytics/zoo/models/recommendation/NeuralCFSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/models/textclassification/TextClassifierSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InputSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TopologySpec.scala
* add summary
* add non-trainable param count
* python
* fix nested sequential
* update
* fix diff
* refactor
* zoo model summary
* summary for zoo model
> [backport 0.1] Add summary for Keras Models (#255)

- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/TransferLearning.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
Remove edges coming output output in newGraph()
Fix transfer learning example bug
> Remove edges coming output output in newGraph() [backport-0.1]

- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/TransferLearning.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
Remove edges coming output output in newGraph()
Fix transfer learning example bug
> Remove edges coming output output in newGraph()

- docs/docs/ProgrammingGuide/image-classification.md
- zoo/src/test/integration-test.robot
- zoo/src/test/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationSpec.scala
need update download links related to https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/.....
1.  search the impacted files using the link https://github.com/intel-analytics/analytics-zoo/search?p=1&q=amazonaws&type=&utf8=%E2%9C%93
2.  11 files found and 3 of them need update
3.  update as the table:
Category | Model | link
-- | -- | --
object-detection | analytics-zoo_frcnn-pvanet_PASCAL_0.1.0.model | https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/object-detection/analytics-zoo_frcnn-pvanet_PASCAL_0.1.0.model
object-detection | analytics-zoo_frcnn-pvanet-compress_PASCAL_0.1.0.model | https://s3-ap-southeast-1.amazonaws.com/analytics-zoo-models/object-detection/analytics-zoo_frcnn-pvanet-compress_PASCAL_0.1.0.model
object-detection | …
> update S3 download links

- docs/docs/ProgrammingGuide/image-classification.md
- zoo/src/test/integration-test.robot
- zoo/src/test/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationSpec.scala
backport: https://github.com/intel-analytics/analytics-zoo/pull/328
> [backport] Branch 0.1: update S3 links

- docs/docs/APIGuide/PipelineAPI/net.md
> fix a few typos

- zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/README.md
https://github.com/intel-analytics/analytics-zoo/pull/349
> [backport] Update README.md

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
* add modeltype for loading different types of models
* rm unused docker
* reformat java style
* change to simple loading
* change to simple loading
* change to simple loading
>  add modeltype for loading different types of models (#348)

- docs/docs/ProgrammingGuide/image-classification.md
- docs/docs/ProgrammingGuide/object-detection.md
- docs/docs/ScalaUserGuide/run.md
- pyzoo/zoo/examples/imageclassification/README.md
- pyzoo/zoo/examples/nnframes/finetune/README.md
- pyzoo/zoo/examples/nnframes/imageInference/README.md
- pyzoo/zoo/examples/nnframes/imageTransferLearning/README.md
- pyzoo/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/README.md
modify some MD files:
1) some class name missing a "s" . e.g 
the class path should be: com.intel.analytics.zoo.examples.recommendation….
with an extra “s” after “example”
2) some jar name using "zoo-0.1.0-SNAPSHOT-jar-with-dependencies.jar "
,which should be analytics-zoo-VERSION-jar-with-dependencies.jar
3) some python path is updated to "analytics-zoo-VERSION-python-api.zip"
4) some links to Zoo are updated to Analytics Zoo
5) https://github.com/intel-analytics/zoo/issues/293
> update links and class/jar name in readme

- docs/docs/release-download.md
> [backport]Update release-download.md

- docs/docs/ProgrammingGuide/image-classification.md
- docs/docs/ProgrammingGuide/object-detection.md
- docs/docs/ScalaUserGuide/run.md
- pyzoo/zoo/examples/imageclassification/README.md
- pyzoo/zoo/examples/nnframes/finetune/README.md
- pyzoo/zoo/examples/nnframes/imageInference/README.md
- pyzoo/zoo/examples/nnframes/imageTransferLearning/README.md
- pyzoo/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/README.md
cc @helenlly 
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update image-classification.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update object-detection.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update README.md
* Update run.md
* Update run.md
> [backport 0.1] update links and class/jar name in readme (#351)

- docs/docs/PythonUserGuide/install.md
- docs/docs/PythonUserGuide/run.md
Highlight to unset SPARK_HOME.
> Update python user guide doc

- docs/docs/PythonUserGuide/install.md
- docs/docs/PythonUserGuide/run.md
> [backport 0.1] Update python user guide doc (#364)

- pyzoo/zoo/models/recommendation/utils.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/WideAndDeep.scala
values in widemodel's input is incorrect, all the values is 1. the values should be indices for LookuptableSparse.
> fix wide values in wide deep

- pyzoo/zoo/models/recommendation/utils.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/WideAndDeep.scala
* fix wide values in wide deep
* fix python unit test
* fix ut
> [backport]fix wide values in wide deep (#345)

- pyzoo/test/zoo/pipeline/api/keras/test_net.py
- pyzoo/test/zoo/resources/tfnet/graph_meta.json
- pyzoo/zoo/pipeline/api/net.py
- pyzoo/zoo/util/tf.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
- zoo/src/test/resources/tfnet/graph_meta.json
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetSpec.scala
The export_tf utility function will
1. freeze the graph (replace all variables with constants)
2. strip all unused node as specified by inputs and outpus
3. add placeholder nodes as needed 
4. write the frozen graph and inputs/outputs names to the folder
```python
export(sess, folder, list_of_input_tensors, list_of_output_tensors)
```
loading from python
```python
net = TFNet.from_export_folder(folder)
```
loading from scala
```scala
val net = TFNet(folder)
```
> Add util to Export tensorflow graph

- apps/object-detection/README.md
solved https://github.com/intel-analytics/zoo/issues/295 on branch-0.1
> add video link, requirement and correct init_nncontext

- pyzoo/test/zoo/pipeline/api/keras/test_net.py
- pyzoo/test/zoo/resources/tfnet/graph_meta.json
- pyzoo/zoo/pipeline/api/net.py
- pyzoo/zoo/util/tf.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
- zoo/src/test/resources/tfnet/graph_meta.json
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetSpec.scala
* add export tf util
* fix types
* add doc
* preserve
* address comments
* fix bug
> Add util to Export tensorflow graph [backport 0.1]

- apps/fraud-detection/README.md
- apps/fraud-detection/fraud-detection.ipynb
- apps/fraud-detection/run.sh
Fix https://github.com/intel-analytics/zoo/issues/292
> update fraud-detection notebook doc

- pyzoo/zoo/models/textclassification/text_classifier.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/textclassification/TextClassifier.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/test/scala/com/intel/analytics/zoo/models/textclassification/TextClassifierSpec.scala
This Python version is workable and gets good accuracy after the training.
> Expose Python model definition for TextClassifier

- pom.xml
- zoo/pom.xml
- zoo/src/assembly/dist.xml
* zip the distribution
* add ossrh sign
* add ossrh sign
* add oss sigh profile
* remove spark bdl conf
* add nexus-staging-maven-plugin
* add nexus-staging-maven-plugin
> [backport 0.1] add zip for deployment and also add OSSRH release support pom (#378)

- docs/docs/APIGuide/PipelineAPI/nnframes.md
- docs/docs/ProgrammingGuide/workingwithimages.md
- docs/docs/release-docs.md
- docs/docs/release-download.md
> Backport 0.1 docs

- pom.xml
- zoo/pom.xml
- zoo/src/assembly/all-in-one.xml
- zoo/src/assembly/dist.xml
* modify pom to pass the ossrh staging rules
* modify pom to pass the ossrh staging rules
* modify pom to pass the ossrh staging rules
* modify pom to pass the ossrh staging rules
> Stage (#394)

- docs/docs/ScalaUserGuide/run.md
> [backport] Update run.md

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetSpec.scala
TFNet should be able to process tensor whose storage.length is not equal to its length
> TFNet should be able to process tensor whose storage.length is not equal to its length

- zoo/pom.xml
- zoo/src/assembly/dist-all.xml
- zoo/src/assembly/dist.xml
this pr is to fix msssing apps in dist.zip
the structure of the dist-all.zip will be
tree analytics-zoo-0.2.0-SNAPSHOT-spark-2.1.0-dist-all
analytics-zoo-0.2.0-SNAPSHOT-spark-2.1.0-dist-all
├── apps
│   ├── anomaly-detection
│   │   ├── anomaly-detection-nyc-taxi.ipynb
│   │   └── README.md
│   ├── dogs-vs-cats
│   │   ├── README.md
│   │   └── transfer-learning.ipynb
│   ├── fraud-detection
│   │   ├── fraud-1.0.1-SNAPSHOT.jar
│   │   ├── fraud-detection.ipynb
│   │   ├── README.md
│   │   └── run.sh
│   ├── image-augmentation
│   │   ├── image
│   │   │   └── test.jpg
│   │   ├── image-augmentation.ipynb
│   │   └── README.md
│   ├── ipynb2py.sh
│   ├── object-detection
│   │   ├── download_model.sh
│   │   ├── object-detection.ipynb
│   │   └── README.md
│   ├── recommendation
│   │   …
> Releasefix

- zoo/pom.xml
- zoo/src/assembly/dist-all.xml
* add apps and zoo build info to dist
* add apps and zoo build info to dist
* add apps and zoo build info to dist
* add apps and zoo build info to dist
* add both dist and dist-all
* add both dist and dist-all
> Releasefix (#412)

- docs/mkdocs.yml
- pyzoo/zoo/pipeline/api/autograd.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/CustomLoss.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/autograd/CustomizedLossSpec.scala
It would be useful if yPred and yTrue have different shape.
> Add yTrueShape for CustomLoss

- pyzoo/zoo/examples/imageclassification/predict.py
Update image classification predict according to predict API change.
Related issue: https://github.com/intel-analytics/zoo/issues/307
> update image classification predict according to predict API change

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/JTensor.java
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/ModelTypeEnum.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
With this support, we can use AbstractInferenceModel with Caffe models.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/431)
> add caffe model loading support to AbstractInferenceModel

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
add back old predict method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/439)
> deprecate single record predict method

- pyzoo/zoo/pipeline/api/autograd.py
- pyzoo/zoo/pipeline/api/keras/layers/torch.py
- pyzoo/zoo/pipeline/api/keras2/layers/pooling.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Threshold.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras2.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/AveragePooling1D.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/ThresholdSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/AveragePooling1DSpec.scala
wrap torch layer Threshold in a keras style
add AveragePooling1D layer in keras2
> add Threshold and AveragePooling1D

- docs/docs/APIGuide/PipelineAPI/math.md
- pyzoo/test/zoo/pipeline/autograd/test_operator.py
- pyzoo/zoo/pipeline/api/autograd.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/math.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonAutoGrad.scala
add dot and l2_normalize operators
fix predict (https://github.com/intel-analytics/zoo/issues/315)
> add dot and l2_normalize operators

- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/KerasLayerWrapper.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/autograd/VariableSpec.scala
add meaningful variable name (https://github.com/intel-analytics/zoo/issues/313)
add get layer by name method (https://github.com/intel-analytics/zoo/issues/320) (https://github.com/intel-analytics/zoo/issues/262)
add unittests
> add meaningful variable name and get layer by name

- pyzoo/test/zoo/pipeline/autograd/test_operator.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/math.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/torch/MM.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/torch/MMSpec.scala
Before this patch, `mm` operator would generate wrong result if being executed multiple times.
> Fix operator mm

- docker/Dockerfile
- docker/README.md
- docker/start-notebook.sh
install moviepy requests per customer requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/452)
> add moviepy to docker image

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/457)
> add batchpercore due to localpredictor bug

- pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py
- pyzoo/zoo/pipeline/nnframes/nn_classifier.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/python/PythonNNFrames.scala
provide a prototype, tested manually. Will add some unit tests.
> NNFrames: save load for python

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/469)
> add serialize feature to FloatInferenceModel

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
JList[JFloat] to Sample time drop from 140ms to 40ms for a single 2590 x 1942 x 3 image on a i7-6700 desktop.
> optimize preprocessing

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/471)
> need init Engine to create LocalPredictor

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
Reverts intel-analytics/analytics-zoo#470
> Revert "fix inference output tensor order mess up"

- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/zoo/feature/image/imagePreprocessing.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- pyzoo/zoo/pipeline/api/keras/objectives.py
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonImageFeature.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TrainingSpec.scala
Fix https://github.com/intel-analytics/zoo/issues/270
cc @dding3 @jenniew @jason-dai 
fit accepts ImageSet as data.
Also adds a missing unit test from 0-based-label PR.
> Support ImageSet in fit

- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/Reflection.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TrainingSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/utils/ReflectionSpec.scala
Fix https://github.com/intel-analytics/zoo/issues/330
> Support Python model predict for multiple outputs

- zoo/pom.xml
this PR is used to support different bigdl versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/488)
> change bigdl default version to 0.6.0

- zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/492)
> fix style error for ImageClassificationConfig

- docs/docs/APIGuide/PipelineAPI/inference.md
- docs/docs/ProgrammingGuide/inference.md
- docs/mkdocs.yml
added inference doc in API Guide
> add inference doc in API Guide

- pyzoo/zoo/examples/imageclassification/README.md
- pyzoo/zoo/examples/objectdetection/README.md
- pyzoo/zoo/examples/textclassification/README.md
- pyzoo/zoo/examples/tfnet/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/tfnet/README.md
Change ZOO_JAR_PATH from analytics-zoo-VERSION-jar-with-dependencies.jar to analytics-zoo-bigdl_BIGDL_VERSION-spark_SPARK_VERSION-ZOO_VERSION-jar-with-dependencies.jar.
Change PYTHON_API_ZIP from analytics-zoo-VERSION-python-api.zip to analytics-zoo-bigdl_BIGDL_VERSION-spark_SPARK_VERSION-ZOO_VERSION-python-api.zip.
> Change jar names and zip names

- pyzoo/zoo/examples/imageclassification/README.md
- pyzoo/zoo/examples/objectdetection/README.md
- pyzoo/zoo/examples/textclassification/README.md
- pyzoo/zoo/examples/tfnet/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/tfnet/README.md
Change ZOO_JAR_PATH from analytics-zoo-VERSION-jar-with-dependencies.jar to analytics-zoo-bigdl_BIGDL_VERSION-spark_SPARK_VERSION-ZOO_VERSION-jar-with-dependencies.jar.
Change PYTHON_API_ZIP from analytics-zoo-VERSION-python-api.zip to analytics-zoo-bigdl_BIGDL_VERSION-spark_SPARK_VERSION-ZOO_VERSION-python-api.zip.
> Change jar names and zip names 

- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
Support list within a list for kerasNet forward.
Predict doest not work for now, because it need fixes from bigdl predictor.
> Support list within a list for kerasNet forward

- docs/docs/PythonUserGuide/install.md
- pom.xml
- pyzoo/zoo/version.py
- zoo/pom.xml
prepare pom and python version to 0.2.0
if everything is ok. will stage the artifacts to OSSRH staging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/532)
> change version to 0.2.0

- pyzoo/test/zoo/pipeline/api/keras/test_net.py
- pyzoo/zoo/pipeline/api/net.py
Add from_session api for TFNet
> Add from_session api for TFNet

- pyzoo/zoo/__init__.py
- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/examples/autograd/custom.py
- pyzoo/zoo/examples/autograd/customloss.py
- pyzoo/zoo/examples/textclassification/text_classification.py
- pyzoo/zoo/pipeline/api/keras/base.py
- pyzoo/zoo/pipeline/api/keras2/base.py
Fix https://github.com/intel-analytics/zoo/issues/275
> Fix creating sc when import bigdl.nn.keras

- pyzoo/zoo/pipeline/api/keras2/layers/convolutional.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras2.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/Conv2D.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/Conv2DSpec.scala
add Conv2D keras2 layer
fix unit tests in Convolution2DSpec
> add Conv2D keras2 layer

- zoo/pom.xml
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/JTensor.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
Change the type of data in JTensor from List<Float> to float[], type of shape from List<Integer> to int[] and the corresponding parts in other files.
> Change data type to float[] and shape to int[] in JTensor

- pyzoo/test/zoo/pipeline/api/keras/test_simple_integration.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TrainingSpec.scala
Fix https://github.com/intel-analytics/zoo/issues/270
Need to depend on BigDL 0.6.0 and use its `evaluateImage` API
> Support predict and evaluate on Imageset

- README.md
- docs/docs/index.md
> Fix typos in README

- docs/docs/Keras2StyleAPIGuide/Layers/convolutional.md
- docs/docs/Keras2StyleAPIGuide/Layers/merge.md
- docs/docs/Keras2StyleAPIGuide/Layers/pooling.md
- docs/mkdocs.yml
- pyzoo/zoo/pipeline/api/keras2/layers/convolutional.py
add doc for following layers:
Conv1D
Conv2D
Maximum
Minimum
AveragePooling1D
MaxPooling1D
> add keras2StyleGuide

- apps/fraud-detection/README.md
the old url is 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/581)
> update toree pip install url

- pyzoo/zoo/pipeline/api/keras/engine/topology.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/Reflection.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/utils/ReflectionSpec.scala
https://github.com/intel-analytics/zoo/issues/351
> model.predict() should set default batch size to -1

- docs/docs/KerasStyleAPIGuide/Layers/core.md
- docs/docs/KerasStyleAPIGuide/Layers/embedding.md
- docs/mkdocs.yml
- pyzoo/zoo/pipeline/api/keras/layers/embeddings.py
add SparseDense & SparseEmbedding doc
> add kerasStyleAPIGuide

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
add ut to test serialization, concurrent, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/589)
> refactor InferenceModel and add uts

- pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py
- pyzoo/zoo/pipeline/nnframes/nn_classifier.py
Avoid creating the extra SparkContext during import.
more details in https://github.com/intel-analytics/zoo/issues/352#issue
> remove CallBigDLFunc during import

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
this pr is to rm localpredictor, which will cause serialization problems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/592)
> rm predictor use model forward

- .gitignore
- pyzoo/test/zoo/pipeline/onnx/test_model_loading.py
- pyzoo/test/zoo/pipeline/utils/test_utils.py
- pyzoo/test/zoo/pipeline/utils/test_utils_onnx.py
- pyzoo/zoo/pipeline/api/keras/layers/convolutional.py
- pyzoo/zoo/pipeline/api/onnx/__init__.py
- pyzoo/zoo/pipeline/api/onnx/mapper/__init__.py
- pyzoo/zoo/pipeline/api/onnx/mapper/conv.py
- pyzoo/zoo/pipeline/api/onnx/mapper/operator_mapper.py
- pyzoo/zoo/pipeline/api/onnx/onnx_helper.py
- pyzoo/zoo/pipeline/api/onnx/onnx_loader.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Convolution2D.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
This PR would focus on initializing the structure which support a Convolution2D only, and would add more support shortly.
> Load onnx model

- pyzoo/zoo/examples/tfnet/train_lenet.py
- pyzoo/zoo/pipeline/api/net.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFTrainingHelper.scala
Core api:
1. create dataset from RDD of list of numpy.ndarray
```
dataset = TFDataset.from_rdd(rdd,
names=["features", "labels"],
shapes=[(None, 28, 28, 1), (None, 1)],
types=[tf.float32, tf.int32]
)
```
2. construct model from dataset
```
images, labels = dataset.inputs
labels = tf.squeeze(labels)
with slim.arg_scope(lenet.lenet_arg_scope()):
logits, end_points = lenet.lenet(images, num_classes=10, is_training=True)
loss = tf.reduce_mean(tf.losses.sparse_softmax_cross_entropy(logits=logits, labels=labels))
```
3. create optimizer and training
```
optimizer = TFOptimizer(loss, Adam(1e-3))
optimizer.optimize(end_trigger=MaxEpoch(5), batch_size=256)
```
4. evalution using optimizer.sess on tensorflow
```
(images_data, labels_data) = mnist.read_data_sets("/tmp/mnist", "test")
images_data = …
```
> Easy distributed training for tensorflow

- docker/Dockerfile
this pr is to fix nightly build error since jdk download path is not available yet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/639)
> change jdk download path

- docs/docs/index.md
> update index.md based on changes of readme.md

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
this pr is to support model loading when used WordEmbedding layer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/660)
> support load model with WordEmbedding layer

- README.md
- docs/docs/index.md
Also fix the typo in the Project headline? @jason-dai @glorysdj 
```Distribtued TensoFlow, Keras and BigDL on Apache Spark```
> Fix some typos in readme

- docs/docs/ProgrammingGuide/tensorflow.md
code snippet should not have leading blanks, otherwise the doc site will render it wrong
> fix tensorflow doc

- docs/docs/ScalaUserGuide/install.md
Fix https://github.com/intel-analytics/zoo/issues/377#event-1824419334
> Update artifactId in scala install document

- docs/docs/ScalaUserGuide/install.md
Fix https://github.com/intel-analytics/zoo/issues/377#event-1824419334
> [Backport 0.2]Update artifactId in scala install document

- pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py
- pyzoo/zoo/util/tf.py
Export TFNet should raise an error when inputs do not in the graph de…
> Export TFNet should raise an error when inputs do not in the graph defined by outputs And test code

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModelSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
This PR is to change the execution of batch inference from while loop to batch forward.
Please help to review the logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/672)
> change inference model to support batch forward

- docker/Dockerfile
- docker/start-notebook.sh
this PR is to fix docker image error caused by pandas change numpy version
> fix version issue of pandas

- zoo/pom.xml
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/Accuracy.scala
this pr is to fix complibity issue between zoo and bigdl 0.6/0.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/696)
> [WIP] fix compatibility for bigdl 0.6 and 0.7

- docs/docs/powered-by.md
Fix https://github.com/intel-analytics/zoo/issues/367
add doc links about Analytics zoo
> update power-by page

- pyzoo/zoo/examples/run-example-tests.sh
to fix https://github.com/intel-analytics/analytics-zoo/issues/721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/727)
> change zoo home as dist

- pyzoo/zoo/examples/objectdetection/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/objectdetection/README.md
Fix https://github.com/intel-analytics/analytics-zoo/issues/718#issuecomment-428475984
> update readme about install from pip for object detection examples

- docs/docs/ScalaUserGuide/install.md
backport PR#728 :https://github.com/intel-analytics/analytics-zoo/pull/728
> [backport] PR#728 to branch0.2: Update install.md

- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageChannelNormalize.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/FeatureSpec.scala
Fix https://github.com/intel-analytics/analytics-zoo/issues/708
> bug fix for imagechannelnormalize

- docs/docs/ScalaUserGuide/install.md
A style error brought in PR #746 Sorry about that...
> Fix a website style error

- zoo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/789)
> change bigdl default version to 0.7.0

- docker/Dockerfile
this pr is to support app image-augmentation
and also change big version to 0.7.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/792)
> add h5py and change bigdl to 0.7 spark to 2.3

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
Fix http://10.239.47.211:18888/view/ZOO-PR/job/ZOO-PR-Pip-Example-Integration/9/console
> Fix classtag problem for Accuracy

- docs/docs/APIGuide/Models/text-classification.md
- docs/docs/ProgrammingGuide/text-classification.md
- pyzoo/zoo/models/textclassification/text_classifier.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/textclassification/TextClassifier.scala
Update according to API changes.
> Update website doc for TextClassifier

- apps/object-detection/README.md
- docs/docs/ScalaUserGuide/install.md
Fix https://github.com/intel-analytics/analytics-zoo/issues/748 and https://github.com/intel-analytics/analytics-zoo/issues/757
> fix document in apps/object detection and scala install

- pyzoo/zoo/examples/nnframes/finetune/README.md
- pyzoo/zoo/examples/nnframes/finetune/image_finetuning_example.py
- pyzoo/zoo/examples/nnframes/imageInference/ImageInferenceExample.py
- pyzoo/zoo/examples/nnframes/imageInference/README.md
- pyzoo/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearningExample.py
- pyzoo/zoo/examples/nnframes/imageTransferLearning/README.md
also update code for consistency and correct some errors.
> update readme for python nnframes examples

- apps/dogs-vs-cats/README.md
Fix https://github.com/intel-analytics/analytics-zoo/issues/752
@yangw1234 @dding3 Please have a review, thanks.
> Update readme for apps/dogs-vs-cats

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
@glorysdj jenkins passed http://10.239.47.211:18888/view/ZOO-PR/job/ZOO-PR-Pip-Apps-Integration/8/console
> Add script for pip app integration test

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/inference.md
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/FloatInferenceModelSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
this PR is to move thread safe and prediction part code to a scala inferencemodel for scala local predictor usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/738)
>  refactor inference model for scala usage

- pyzoo/zoo/examples/autograd/custom.py
- pyzoo/zoo/examples/autograd/customloss.py
- pyzoo/zoo/examples/run-example-tests-pip.sh
> Add image classification and autograd to pip integration

- pyzoo/zoo/examples/imageclassification/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
> Update readme for scala and python examples/imageclassification

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNImageReader.scala
Use OpenCVMat API to load the jni lib.
> fix mat loading

- pyzoo/zoo/examples/run-example-tests-pip.sh
> Fix pip example integration

- apps/image-augmentation-3d/README.md
analytics-zoo/apps/image-augmentation-3d/：Readme need updates about "install from pip" / "download prebuilt package" #754
> Update readme for apps/image-augmentation-3d

- zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/README.md
> recommendation readme update

- apps/run-app-tests.sh
https://github.com/intel-analytics/analytics-zoo/pull/901
> [Backport 0.3] Fix typo in apps/run-app-tests.sh

- docs/docs/PythonUserGuide/run.md
- scripts/python_package.sh
I went through the doc steps for running with virtual environment and found two issues:
1. the python_package.sh can only be executed when current directory is `bin` folder, otherwise it cannot find requirement.txt
2. the scripts for running with virtual environment ran with error:
`Caused by: java.io.IOException: Cannot run program "/root/dist/bin/venv.zip/venv/bin/python": error=2, No such file or directory`
The PR tries to fix both issues.
> fix two issues with virtual environment

- docs/docs/PythonUserGuide/run.md
- scripts/python_package.sh
* update venv script
* update doc
* update
> [backport 0.3] Fix doc site for python yarn virtual environment (#845)

- docs/docs/PythonUserGuide/install.md
- docs/docs/PythonUserGuide/run.md
- scripts/README.md
* update readme and website
* update
> [backport 0.3] Update README for yarn guide and fix website style (#906)

- zoo/src/test/common.robot
- zoo/src/test/integration-test.robot
this PR is to simplify integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/926)
> Integration

- docs/docs/release-download.md
update release info for BigDL 0.7.1
> [backport] Update release-download.md

- docs/docs/PythonUserGuide/run.md
- pyzoo/dev/release/release.sh
- pyzoo/setup.py
- pyzoo/zoo/__init__.py
- pyzoo/zoo/examples/tensorflow/__init__.py
- pyzoo/zoo/examples/tensorflow/distributed_training/__init__.py
Fix #933 
```
release.sh linux without_bigdl false
```
> Change 'zoo.version.__version__' to 'zoo.__version__'

- docs/docs/APIGuide/FeatureEngineering/text.md
- docs/docs/ProgrammingGuide/workingwithtexts.md
- pyzoo/test/zoo/feature/text/test_text_feature.py
- pyzoo/test/zoo/feature/text/test_text_set.py
- pyzoo/zoo/examples/textclassification/text_classification.py
- pyzoo/zoo/feature/text/text_set.py
- pyzoo/zoo/feature/text/transformer.py
- zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/TextClassification.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonTextFeature.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/text/SequenceShaper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextFeature.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextFeatureToSample.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/text/WordIndexer.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/text/SequenceShaperSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextSetSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/text/WordIndexerSpec.scala
First transform from word2index. Those words not in wordDict will be aborted.
Then shape sequence on indices.
> Change the order of shape sequence and word2idx

- apps/web-service-sample/recommendation-interence/README.md
- apps/web-service-sample/recommendation-interence/pom.xml
- apps/web-service-sample/recommendation-interence/src/main/java/com/intel/analytics/zoo/apps/recommendation/inference/NueralCFModel.java
- apps/web-service-sample/recommendation-interence/src/main/java/com/intel/analytics/zoo/apps/recommendation/inference/SimpleDriver.java
- apps/web-service-sample/recommendation-interence/src/main/java/com/intel/analytics/zoo/apps/recommendation/inference/UserItemPair.java
- apps/web-service-sample/recommendation-interence/src/main/scala/com/intel/analytics/zoo/apps/recommendation/interence/NueralCFModel.scala
- apps/web-service-sample/recommendation-interence/src/main/scala/com/intel/analytics/zoo/apps/recommendation/interence/SimpleDriver.scala
- apps/web-service-sample/recommendation-interence/src/main/scala/com/intel/analytics/zoo/apps/recommendation/interence/SimpleScalaDriver.scala
an example of loading NueralCF model and having inference is added, for the purpose of productionization of customer's project
> simple java example of recommendation inference

- docs/docs/PythonUserGuide/install.md
restrict to install pyspark==2.3.2 in the instruction as spark 2.4 will have error with TFNet.
> [branch 0.3] Update pip install command

- pyzoo/zoo/examples/tensorflow/distributed_training/train_lenet.py
- pyzoo/zoo/examples/tensorflow/distributed_training/train_mnist_keras.py
- pyzoo/zoo/pipeline/api/net.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFTrainingHelper.scala
API:
```python
dataset = ...
data = Input(shape=[784])
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)
model = Model(input=data, output=predictions)
model.compile(optimizer='rmsprop',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])
opt = TFOptimizer.from_keras_model(model, dataset)
opt.optimize(end_trigger=MaxEpoch(max_epoch))
```
> support keras in distributed tensorflow on analytics-zoo

- docs/docs/KerasStyleAPIGuide/Layers/advanced-activation.md
- docs/docs/KerasStyleAPIGuide/Layers/convolutional.md
- docs/docs/KerasStyleAPIGuide/Layers/core.md
- docs/docs/KerasStyleAPIGuide/Layers/pooling.md
- docs/docs/KerasStyleAPIGuide/Layers/recurrent.md
Tasks:
init   the doc structure
./ELU.scala
./UpSampling2D.scala
./SparseDense.scala
./MaxPooling3D.scala
./LocallyConnected1D.scala
./Reshape.scala
./MaxoutDense.scala
./Convolution1D.scala
./Highway.scala
All finished.
> Keras Layer docs 

- pyzoo/test/zoo/pipeline/onnx/test_model_loading.py
- pyzoo/zoo/pipeline/api/onnx/mapper/batchnormalization.py
refer to issue **ut failures when upgrade to pytorch 1.0.0 #1011**
> Fix ut failures of pytorch 1.0.0 

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/optimizers/Adam.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/optimizers/OptimizersSpec.scala
Since the learning rate schedule already has the logic to update nevalCounter.
> avoid adding timestep in adam

- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/optimizers/OptimizersSpec.scala
> shorten ut time

- pyzoo/test/zoo/models/anomalydetection/test_anomalydetector.py
- pyzoo/test/zoo/models/recommendation/test_neuralcf.py
- pyzoo/zoo/examples/anomalydetection/__init__.py
- pyzoo/zoo/examples/anomalydetection/anomaly_detection.py
- pyzoo/zoo/models/anomalydetection/__init__.py
- pyzoo/zoo/models/anomalydetection/anomaly_detector.py
- zoo/src/main/scala/com/intel/analytics/zoo/examples/anomalydetection/AnomalyDetection.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/anomalydetection/AnomalyDetector.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
add python wrapper for anomaly detector
> Anomaly detector python

- pyzoo/zoo/examples/tensorflow/distributed_training/evaluate_lenet.py
- pyzoo/zoo/examples/tensorflow/distributed_training/train_lenet.py
- pyzoo/zoo/pipeline/api/net.py
- pyzoo/zoo/util/tf.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFTrainingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala
@hkvision This should fix the problem you encountered. Could you help testing this?
1. fix keras mtl model does not converge
2. support setting sessionConfig in python
If performance is batch size sensitive, using
```
TFOptimizer.from_keras(model, tfdataset, config=tf.ConfigProto())
```
and setting spark.master to `local[1]` would be faster. In this case, we are using a single tensorflow session to run the whole batch.
> add keras learning phase support

- pyzoo/zoo/examples/qaranker/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/qaranker/README.md
Fix link 404 in README.
Put download data link at the very beginning.
> Update qaranker readme

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1091)
> refactor api

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1093)
> fix style error

- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModelSuite.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1096)
> fix a ut error

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
- Add QARanker Python into integration (both pip and non-pip)
- Fix batch size problem for anomaly detection pip 
http://10.239.47.211:18888/view/ZOO-NB/job/ZOO-NB-Pip-Example-Integration/100/console
cc @glorysdj @songhappy
> Add QARanker Python example to integration

- docs/docs/KerasStyleAPIGuide/Optimization/objectives.md
- docs/docs/KerasStyleAPIGuide/Optimization/optimizer.md
- docs/docs/KerasStyleAPIGuide/Optimization/training.md
> [Doc] Optimization Doc

- docs/docs/APIGuide/PipelineAPI/inference.md
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/abstract-Inference-model.md
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/inference.md
* Update inference.md
* Update inference.md
* Update abstract-Inference-model.md
* Update inference.md
* Update abstract-Inference-model.md
* Update inference.md
> update doc for inference (#1121)

- docs/docs/ProgrammingGuide/workingwithimages.md
> update pmem Docs

- docs/docs/release-docs.md
- docs/docs/release-download.md
update release download and links
> update Branch 0.4 doc website 

- docs/docs/ProgrammingGuide/inference.md
* update docs/ProgrammingGuide/inference.md
* update docs/ProgrammingGuide/inference.md
> Update docs/ProgrammingGuide/inference.md (#1132)

- pyzoo/dev/diff.py
- pyzoo/zoo/models/seq2seq/seq2seq.py
- pyzoo/zoo/pipeline/api/keras/layers/torch.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seq.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
Fix https://github.com/intel-analytics/analytics-zoo/issues/1124
> implement python version of build_model method for seq2seq

- pyzoo/zoo/examples/tensorflow/tfnet/predict.py
> change input name to align with tensorflow object detection model convention

- zoo/src/main/scala/com/intel/analytics/zoo/examples/qaranker/README.md
> Update Scala QARanker README

- pyzoo/zoo/pipeline/api/keras/layers/convolutional_recurrent.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/ConvLSTM2D.scala
enhancement for #724 
ConvLSTM2D should extend Recurrent instead of KerasLayer.
> ConvLSTM2D extend Recurrent

- zoo/pom.xml
this pr is help to deploy zoo-core 0.4.0-S. 0.4.0 and 0.5.0-S
at the end, will merge with dependency zoo-core with version 0.5.0-SNAPSHOT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1148)
> zoo with zoo-core 0.4.0-S, 0.4.0, and 0.5.0-S

- docs/docs/ScalaUserGuide/install.md
this pr is to update scala install guide
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1153)
> add specific repo for 0.4.0

- docker/Dockerfile
> Change download URL to use "dist.apache.org"

- zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextSet.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/pmem/NativeSpec.scala
Set rdd name in QAranker example.
> Set rdd name in textset

- docs/docs/ProgrammingGuide/workingwithimages.md
1. Add missing import in workingwithimages.md
2. Fix a typo.
> Add missing import in workingwithimages.md

- zoo/pom.xml
Change zoo-core from 0.5.0-SNAPSHOT to 0.4.0.
> change zoo-core from 0.5.0-SNAPSHOT to 0.4.0

- pyzoo/dev/diff.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Softmax.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/KerasUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/Softmax.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/ActivationSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/SoftmaxSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/AvtivationSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras2/layers/SoftmaxSpec.scala
This PR is split from https://github.com/intel-analytics/analytics-zoo/pull/966/files and used to fix https://github.com/intel-analytics/analytics-zoo/issues/961
> support 4d softmax

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModelSuite.scala
this pr is to refine openvino loadtf exception handling and log output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1183)
> refine openvino loadtf exception handling and log output

- zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/ImageNet2012.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/Train.scala
Current code's Top1 result is 67.204%, while bigdl can reach 68.x %.
Change validation's RandomCrop to CenterCrop can fix this.
The top1 result is below:
```
2019-02-18 14:17:58 INFO  DistriOptimizer$:152 - [Epoch 1 871552/1281167][Iteration 619][Wall Clock 1762.839761811s] Top1Accuracy is Accuracy(correct: 352, count: 50000, accuracy: 0.00704)
2019-02-18 14:47:34 INFO  DistriOptimizer$:152 - [Epoch 2 463232/1281167][Iteration 1239][Wall Clock 3538.710446394s] Top1Accuracy is Accuracy(correct: 1373, count: 50000, accuracy: 0.02746)
2019-02-18 15:17:19 INFO  DistriOptimizer$:152 - [Epoch 3 54912/1281167][Iteration 1859][Wall Clock 5323.887021443s] Top1Accuracy is Accuracy(correct: 3216, count: 50000, accuracy: 0.06432)
2019-02-18 15:47:00 INFO  DistriOptimizer$:152 - [Epoch 3 …
```
> [Inception V1]change validation to center crop

- pyzoo/test/zoo/pipeline/api/keras/test_layer.py
- pyzoo/zoo/pipeline/api/keras/regularizers.py
added regularizers.py with l1 l2 regularization
added test corresponded
> added regularizers.py with l1 l2 regularization

- README.md
- docker/Dockerfile
- docker/README.md
- docker/install-python.sh
Adding python 3 compatibility for docker containers
> Python3 support for docker containers

- zoo/src/main/scala/com/intel/analytics/zoo/common/CheckedObjectInputStream.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/FloatModelSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
please refer to 
https://www.owasp.org/index.php/Deserialization_of_untrusted_data
https://www.contrastsecurity.com/security-influencers/java-serialization-vulnerability-threatens-millions-of-applications
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1200)
>  check inputstream when deserialize object

- pyzoo/test/zoo/tfpark/test_tfpark_estimator.py
- pyzoo/test/zoo/tfpark/test_tfpark_model.py
- pyzoo/zoo/examples/tensorflow/tfpark/estimator_dataset.py
- pyzoo/zoo/pipeline/api/net.py
- pyzoo/zoo/tfpark/estimator.py
- pyzoo/zoo/util/nest.py
> Add TFPark Estimator API

- pyzoo/test/zoo/tfpark/test_text_models.py
- pyzoo/zoo/tfpark/text/__init__.py
- pyzoo/zoo/tfpark/text/intent_extraction.py
- pyzoo/zoo/tfpark/text/ner.py
- pyzoo/zoo/tfpark/text/pos_tagging.py
> Add sequence tagger in tfpark

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/WordEmbedding.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
Use CheckedObjectInputStream
To play safe, I will run TextClassification example in cluster.
> Resolve deserialize problem for WordEmbedding and NNEstimator

- docs/docs/release-download.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1230)
> correct the download urls

- pyzoo/test/zoo/pipeline/onnx/test_model_loading.py
- pyzoo/zoo/pipeline/api/onnx/onnx_helper.py
In ONNX,  pads format is [x1_begin, x2_begin...x1_end, x2_end,...]
> [ONNX] Maxpool

- docker/install-python.sh
- docker/start-notebook.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1241)
> adjust tf version and local[*]

- pyzoo/dev/check-license
- pyzoo/test/zoo/tfpark/test_tfpark_model.py
- pyzoo/zoo/tfpark/__init__.py
- pyzoo/zoo/tfpark/model.py
- pyzoo/zoo/tfpark/text/text_model.py
- pyzoo/zoo/util/tf.py
- pyzoo/zoo/util/tf_graph_util.py
should fix #1228 
do not need to use variable_creator_scope anymore
modified lasted tensorflow version of graph_util (https://github.com/tensorflow/tensorflow/commit/cebce4a2b5e33a06a1c92772008082895568f10a), and fixed bug in it:
1. treat colocated operation as input operation to prevent it being lost
2. for every operation that reads from a variable resource, use dfs to find the variable it reads and record all operations in the path. Then make those operations accept a regular tensor instead of a resource tensor (because variable will become a const after freeze).
> using latest tensorflow's freeze funtion, fix keras embedding freeze bug

- zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/ImageNet2012.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/Options.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/Train.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageBytesToMat.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImagePixelBytesToMat.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/pmem/FeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/pmem/NativeSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/pmem/PersistentMemorySpec.scala
1. Add opencv preprocessing pipeline to TrainInceptionV1
2. Support caching ImageFeature to PMEM
> Opencv preprocessing for inceptionv1

- pyzoo/test/zoo/pipeline/utils/test_utils.py
- pyzoo/test/zoo/tfpark/test_tfpark_estimator.py
- pyzoo/test/zoo/tfpark/test_tfpark_model.py
- pyzoo/zoo/pipeline/api/net.py
- pyzoo/zoo/tfpark/estimator.py
- pyzoo/zoo/tfpark/model.py
support tfdataset without batch:
if user does not specify batch_size in TFDataset, then TFDataset.tensors will return the a tensor without batch dim.
> support tfdataset without batch

- pyzoo/zoo/feature/image/imageset.py
- pyzoo/zoo/feature/text/text_set.py
> Make ImageSet and TextSet transform return a new ImageSet/TextSet

- pyzoo/test/zoo/models/anomalydetection/test_anomalydetector.py
- pyzoo/zoo/examples/anomalydetection/anomaly_detection.py
- pyzoo/zoo/models/anomalydetection/anomaly_detector.py
- pyzoo/zoo/models/common/zoo_model.py
- zoo/src/main/scala/com/intel/analytics/zoo/models/anomalydetection/AnomalyDetector.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/common/KerasZooModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
Separate KerasZooModel from recommendation PR
> KerasZooModel

- pyzoo/dev/diff.py
- pyzoo/test/zoo/pipeline/autograd/test_operator.py
- pyzoo/zoo/pipeline/api/autograd.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/autograd/math.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BERT.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InternalERF.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonAutoGrad.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BertSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InternalERFSpec.scala
`gelu` in bert is a slight different with transformer `gelu`, override the method in bert.
> update gelu in bert

- pyzoo/test/zoo/pipeline/inference/test_inference_model.py
Download from tensorflow.org will cause HTTP error in Jenkins.
> Python OpenVINO unit test download from local repo

- zoo/pom.xml
fix mismatch error between analytics-zoo and analytics-zoo-core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1305)
> fix pom error

- pyzoo/test/zoo/pipeline/inference/test_inference_model.py
- pyzoo/zoo/pipeline/inference/inference_model.py
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/PythonInferenceModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModelSuite.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1275)
> add api for load,optimize,calibrate imageclassification models

- zoo/src/main/scala/com/intel/analytics/zoo/examples/inception/Train.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/Estimator.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/estimator/DistriEstimatorSpec.scala
Add l2norm and contant norm to estimator API.
> Add norm option to estimator.

- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/ImageNetEvaluation.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/ImageNetInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/Perf.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/bigdl/Predict.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageBytesToMat.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSetToSample.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/common/ImageModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/LabelOutput.scala
#1265 Address new comments from @dding3
> Meet review comments for #1265

- pyzoo/test/zoo/pipeline/utils/test_utils.py
- pyzoo/test/zoo/tfpark/test_text_estimators.py
Use smaller data
Now need 5g.
Will investigate more why so much is used.
> Make bert classifier ut cost less memory

- pyzoo/test/zoo/tfpark/test_text_estimators.py
> Change collect to count in bert classifier ut

- docs/docs/ProgrammingGuide/image-classification.md
- zoo/src/main/scala/com/intel/analytics/zoo/models/image/imageclassification/ImageClassificationConfig.scala
- Run evaluation on ImageNet val data and got same results.
Top1Accuracy is Accuracy(correct: 37912, count: 50000, accuracy: 0.75824)
Top5Accuracy is Accuracy(correct: 46332, count: 50000, accuracy: 0.92664)
- Latency for one image preprocessing is around ~2.3 ms and the overall end2end latency is <10ms.
> Change RandomCropper to CenterCrop in ResNet50 preprocessor

- pyzoo/zoo/pipeline/api/keras/layers/self_attention.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BERT.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InternalExpand.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/TransformerLayer.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
This PR is separated from https://github.com/intel-analytics/analytics-zoo/pull/1304/files and it includes:
1. Add pooler for python bert
2. Support load pretrain bert in python
3. Minor bug fix
> support pooler for python bert and bug fix

- docs/docs/PythonUserGuide/install.md
- docs/docs/release-download.md
> Fix pip install doc

- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/PrepareOpenVINOResNet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/inference.md
* Add PrepareOpenVINOResNet for preparing resnet model for zoo and OpenVINO.
* Refine document.
> [Backport] Refine OpenVINO Int8 example

- zoo/src/test/integration-test.robot
* test 0, 1 job
* test 2, 3, 4 job
* test rest
* test from anomaly detection
* test spark inception v1, inception v1 opencv
* test inceptionv1 opencv and wideAndDeep
* test ncf
* fix errors in integration test .robot
* fix errors in scala integration test robot
* agg
* typo
> [Backport] Fix Scala integration test scripts (#1357)

- zoo/src/main/scala/com/intel/analytics/zoo/examples/chatbot/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/chatbot/Train.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/chatbot/Utils.scala
Fix https://github.com/intel-analytics/analytics-zoo/issues/1360#event-2359089368
> update chatbot doc

- pyzoo/zoo/examples/streaming/textclassification/streaming_text_classification.py
> Fix streaming_text_classification code style

- pyzoo/zoo/examples/tensorflow/tfpark/README.md
- pyzoo/zoo/examples/tensorflow/tfpark/estimator_inception.py
> add tfpark example readme

- pyzoo/zoo/examples/tensorflow/tfpark/README.md
- pyzoo/zoo/examples/tensorflow/tfpark/estimator_inception.py
* add tfpark example readme
* fix style
* add comments
> add tfpark example readme (#1380)

- docs/docs/APIGuide/PipelineAPI/inference.md
- docs/docs/ProgrammingGuide/inference.md
- pyzoo/zoo/examples/autograd/README.md
- pyzoo/zoo/examples/openvino/README.md
- pyzoo/zoo/examples/openvino/predict.py
- pyzoo/zoo/examples/streaming/objectdetection/README.md
- pyzoo/zoo/examples/streaming/textclassification/README.md
Fix #1353.
Add System Requirements for #1374 .
Address #1368 .
> Modify OpenVINO and Streaming Python doc

- docs/docs/APIGuide/PipelineAPI/inference.md
- docs/docs/ProgrammingGuide/inference.md
- pyzoo/zoo/examples/autograd/README.md
- pyzoo/zoo/examples/openvino/README.md
- pyzoo/zoo/examples/openvino/predict.py
- pyzoo/zoo/examples/streaming/objectdetection/README.md
- pyzoo/zoo/examples/streaming/textclassification/README.md
* Add System requirements into OpenVINO doc and OpenVINO example.
* Modify Streaming Python doc.
* Fix path problem in autograd example.
> [Backport] Modify OpenVINO and Streaming Python doc

- docs/docs/APIGuide/PipelineAPI/inference.md
- pyzoo/test/zoo/pipeline/inference/test_inference_model.py
- pyzoo/zoo/pipeline/inference/inference_model.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/PythonInferenceModel.scala
> Add OpenVINO int8 Python API

- zoo/pom.xml
> [backport] Shading protobuf 

- docs/docs/powered-by.md
- docs/docs/release-download.md
> update 0.6.0 snapshots

- docs/docs/APIGuide/PipelineAPI/inference.md
- pyzoo/test/zoo/pipeline/inference/test_inference_model.py
- pyzoo/zoo/pipeline/inference/inference_model.py
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/ImageNetEvaluation.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/Perf.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/Predict.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/AbstractModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/FloatModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/PythonInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/README.md
* Merge predictInt8 into predict in Scala, Java and Python API.
> Merge predictInt8 into predict

- zoo/src/main/scala/com/intel/analytics/zoo/examples/resnet/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/resnet/TrainImageNet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/resnet/Utils.scala
Add ResNet50 Training code for imagenet using FeatureSet and Estimator. 
Use "--memoryType PMEM" to cache with AEP.
Add mkldnn support.
> Add ResNet 50 training code

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/JTensor.java
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOInt8Suite.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModelSuite.scala
Note that this PR cannot pass Jenkins until Zoo-core is updated.
Split OpenVINOModelSuit into 2 testSuit.
Add mismatch UT.
Add changeLayout for JTensor.
> Add mismatch and int8 Unit test

- pyzoo/zoo/pipeline/api/net/tf_optimizer.py
- pyzoo/zoo/tfpark/model.py
TFOptimizer.refresh_weights does not work
> Fix keras fit

- scripts/jupyter-with-zoo.sh
change from `ip=*` to `ip=0.0.0.0`
fix issue:  #1471  #1340
> update jupyter-with-zoo.sh 's bounding ip

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
to fix https://github.com/intel-analytics/analytics-zoo/issues/1473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1489)
> fix arrays reference

- docker/jenkins-ci/jenkins-slave/Dockerfile
Add torch, torch-rnn, caffe, ray in Dockerfile
> update Dockerfile to support torch

- pyzoo/zoo/util/spark.py
This would be covered by unitest once the Jenkins turn on the ray test.
> fix init_spark_on_local

- docs/docs/ProgrammingGuide/visualization.md
Remove redundant '*' in visualization doc.
> Visualization doc markdown style fix

- pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py
- pyzoo/zoo/pipeline/nnframes/nn_classifier.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNClassifier.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNClassifierSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimatorSpec.scala
change to 4 * num of total cores.
> change default batch size for NNModel transform

- zoo/pom.xml
update pom to fix mac version pypi build failure
> update pom to fix mac version pypi build failure

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOInt8Suite.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1531)
> add bytes model loading for inference model

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOInt8Suite.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1540)
> add support of tf saved model load as openvino

- zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/CaffeLoader.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/Converter.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/LayerConverter.scala
- zoo/src/main/scala/com/intel/analytics/zoo/models/caffe/V1LayerConverter.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Net.scala
- zoo/src/main/scala/com/intel/analytics/zoo/utils/File.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/NetSpec.scala
new caffe loader with difference
> Caffewithdiff

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModelSuite.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1556)
> fix release bug of AbstractInferenceModel

- docs/docs/powered-by.md
1. re-org
2.add new tech docs and wp
> update powerby page 

- pyzoo/zoo/pipeline/api/keras/datasets/__init__.py
- pyzoo/zoo/pipeline/api/keras/engine/topology.py
Add __init__ to make zoo.pipeline.api.keras.datasets a package.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/1529
> Make keras datasets to a package

- pyzoo/zoo/automl/README.md
> Fix typo in automl README

- docs/docs/release-download.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1605)
> update snapshot release for bigdl 0.9.1

- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala
- zoo/src/test/scala/com/intel/analytics/zoo/feature/FeatureSpec.scala
Fix imageset read relative path
> Fix imageset read relative path

- pyzoo/dev/build.sh
> Update build.sh, fix typo

- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageChannelScaledNormalizer.scala
There is an obvious error in the comments.
The variate meanB is mean of channel B rather than  mean of channel R
> Fix incorrect code comment

- pyzoo/zoo/examples/anomalydetection/anomaly_detection.py
* Fix predict batch size in anomaly_detection.py
* Add `input_dir` check to avoid NonType error.
* Add usage.
> Fix predict batch size in anomaly_detection.py

- pyzoo/test/zoo/pipeline/api/test_torch_net.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNEstimator.scala
support save/load torchnet model in NNFrames.
Since Torchnet does not support saveModule, we need to provide special logic for it.
> Support TorchNet save load with NNFrames

- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/NeuralCF.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Net.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Dense.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Dropout.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Embedding.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Flatten.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Input.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/LSTM.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Merge.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Permute.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Reshape.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Select.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/NetSpec.scala
Add support to Keras Model.
Related pr: #1600
> Save KerasModel to pure keras or tf protobuf

- zoo/pom.xml
#1560 change bigdl to 0.9.0 by mistake
> update bigdl to 0.9.1

- zoo/pom.xml
#1560 change bigdl to 0.9.0 by mistake
> [branch-0.6]update bigdl to 0.9.1

- docs/mkdocs.yml
add pytorch to doc/programming guide
> add PyTorch to doc/programming guide 

- zoo/pom.xml
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
* Clean up dist-mac.
* Modify mac openvino bin path.
> [Backport] Clean up dist-mac

- docs/docs/APIGuide/FeatureEngineering/featureset.md
- zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
> update Featureset apiguide

- docs/docs/KerasStyleAPIGuide/Layers/self-attention.md
- docs/mkdocs.yml
- pyzoo/zoo/examples/attention/README.md
- pyzoo/zoo/examples/attention/transformer.py
- pyzoo/zoo/pipeline/api/keras/layers/self_attention.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BERT.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/TransformerLayer.scala
- Fix #1659 #1660 
- Expose documentation on website
- Fix some doc format and typos.
> Fix transformer example and update doc

- docs/docs/KerasStyleAPIGuide/Layers/self-attention.md
- docs/mkdocs.yml
- pyzoo/zoo/examples/attention/README.md
- pyzoo/zoo/examples/attention/transformer.py
- pyzoo/zoo/pipeline/api/keras/layers/self_attention.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/BERT.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/TransformerLayer.scala
* fix and update doc
* meet review
* minor
* fix typo
> [backport 0.6] Fix transformer example and update doc (#1676)

- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/README.md
> Modify vnni example doc

- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/README.md
* Use full path to avoid calibration error.
> [Backport] Modify vnni openvino example doc

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
* Replace OpenVINO related decompression output with one line log info.
* Remove unnecessary `ls`.
> Reduce vino logs

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala
1. Fix variable not initialized after clone bug
2. return zero grad instead of null
> [Bug Fix] SavedModel loaded TFNet return zero grad

- docs/docs/PythonUserGuide/install.md
- pyzoo/setup.py
Somehow I overlooked this before the release...
> Upgrade pip bigdl dependency to 0.9.1

- docs/docs/ProgrammingGuide/rayonspark.md
- docs/docs/PythonUserGuide/install.md
Also update missing pip dependency.
> Update RayOnSpark doc

- docs/docs/powered-by.md
- docs/docs/presentations.md
1. powered by:
CERN
Deep Learning Pipelines for High Energy Physics using Apache Spark with Distributed Keras on Analytics Zoo
SK Telecom
Apache Spark AI Use Case in Telco: Network Quality Analysis and Prediction with Geospatial Visualization
2.Talks:
Deep Learning Pipelines for High Energy Physics using Apache Spark with Distributed Keras on Analytics Zoo, Spark+AI Summit, Oct 2019, Amsterdam (slides)
Apache Spark AI Use Case in Telco: Network Quality Analysis and Prediction with Geospatial Visualization, Spark+AI Summit, Oct 2019, Amsterdam (slides)
> update Spark Summit talks and slides in powerby and presentation 

- docs/mkdocs.yml
- pyzoo/zoo/ray/util/raycontext.py
Reported by tencent when testing.
"local" in self.sc.master can be standalone `spark://localhost:7777`
Even though we are not supporting for standalone, better fix it in case.
> Minor fix for detecting sc is local

- pyzoo/test/zoo/automl/feature/test_time_sequence_feature.py
- pyzoo/test/zoo/automl/pipeline/test_time_sequence.py
- pyzoo/zoo/automl/feature/time_sequence.py
- pyzoo/zoo/automl/pipeline/time_sequence.py
- pyzoo/zoo/automl/regression/time_sequence_predictor.py
- pyzoo/zoo/automl/search/RayTuneSearchEngine.py
main changes:
1. add result analysis in ray 0.7.4 (searcher.run() returns ExperimentAnalysis instead of trials)
2. change default look back length from 1 to 2. Add input check and some corresponding UTs
3. while future_seq_len=1, output one value instead of an array
> [Automl] Change default look back value and evaluation output format while future_seq_len=1

- pyzoo/zoo/automl/model/Seq2Seq.py
- pyzoo/zoo/automl/model/VanillaLSTM.py
- pyzoo/zoo/automl/model/time_sequence.py
- pyzoo/zoo/automl/pipeline/time_sequence.py
- pyzoo/zoo/automl/regression/time_sequence_predictor.py
- pyzoo/zoo/automl/search/RayTuneSearchEngine.py
add mc dropout and predict with uncertainty
> add mcdrop and predict with uncertainty

- pyzoo/test/zoo/automl/pipeline/test_time_sequence.py
- pyzoo/zoo/automl/common/parameters.py
- pyzoo/zoo/automl/common/util.py
- pyzoo/zoo/automl/pipeline/time_sequence.py
- pyzoo/zoo/automl/regression/time_sequence_predictor.py
add ppl.fit_with_fixed_configs API and UT
add ppl.config_save API and UT
> [Automl] add fit with fixed configs

- pyzoo/test/zoo/pipeline/estimator/test_estimator.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/python/PythonEstimator.scala
py4j will translate python list to java.util.ArrayList not scala's Array.
> [Bug Fix] Fix estimator python validation method argument type bug

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1745)
> add load TF saved model as TFNet inference model

- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/Perf.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceSupportive.scala
* Add pure JAVA Perf.
* Refine document.
> Refine OpenVINO VNNI Perf

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/objectives/CategoricalCrossEntropy.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/objectives/CategoricalCrossEntropySpec.scala
Fixed issue in https://groups.google.com/forum/#!topic/bigdl-user-group/2CR_j_LQd9U
> Fix CategoricalCrossEntropy may NaN.

- pyzoo/test/zoo/automl/common/test_metrics.py
- pyzoo/test/zoo/automl/model/test_Seq2Seq.py
- pyzoo/test/zoo/automl/model/test_VanillaLSTM.py
- pyzoo/test/zoo/automl/pipeline/test_time_sequence.py
- pyzoo/zoo/automl/common/metrics.py
- pyzoo/zoo/automl/model/Seq2Seq.py
- pyzoo/zoo/automl/model/VanillaLSTM.py
- pyzoo/zoo/automl/model/time_sequence.py
- pyzoo/zoo/automl/pipeline/time_sequence.py
- pyzoo/zoo/automl/regression/time_sequence_predictor.py
- pyzoo/zoo/automl/search/RayTuneSearchEngine.py
fixed issue https://github.com/intel-analytics/analytics-zoo/issues/1695
> add some metrics and their test case

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
this pr is to remove unnecessary code for bigdl engine init before model loading
> remove bigdl engine init when load model

- zoo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1757)
> update bigdl version to 0.10.0

- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/FloatModelSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOInt8Suite.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModelSuite.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1758)
> update ut for inference model to test no bigdl properties

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/PyTorchModelSpec.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1765)
> add pytorch inferenceModel

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchNet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/PyTorchModelSpec.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1785)
> add load bytes to pytorch model in inferencemodel

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/ModelLoader.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1787)
> add load bytes to tf saved model in inferencemodel

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/NetUtils.scala
> Enhance TFNet error messages when input name is wrong

- pyzoo/zoo/tfpark/gan/gan_estimator.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/GanOptimMethod.scala
> [Bug Fix] Fix GANOptimizer

- pyzoo/zoo/examples/run-example-tests.sh
add run python example test: inception and pytorch
> add run python example test: inception and pytorch

- pyzoo/test/zoo/feature/text/test_text_set.py
- pyzoo/zoo/examples/streaming/textclassification/streaming_text_classification.py
- pyzoo/zoo/examples/textclassification/text_classification.py
- pyzoo/zoo/feature/text/text_set.py
- zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/TextClassification.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonTextFeature.scala
Fix #1818 
Align with ImageSet
> Add uri to get_predicts in TextSet

- pyzoo/test/zoo/pipeline/api/test_tf.py
- pyzoo/test/zoo/tfpark/test_tf_dataset.py
- pyzoo/zoo/pipeline/api/net/tf_dataset.py
- pyzoo/zoo/pipeline/api/net/tf_predictor.py
- pyzoo/zoo/pipeline/api/net/tfnet.py
- pyzoo/zoo/tfpark/estimator.py
- zoo/src/main/scala/com/intel/analytics/zoo/common/PythonZoo.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Predictor.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/StringMiniBatch.scala
1. Support Predict Minibatch in Predictior
2. Add TFDataset Support in TFNet.predict
> Support Predict MiniBatch in Predictior

- docs/gen_site.py
- pyzoo/zoo/util/spark.py
Switched to Python3 to generate website docs.
> Fix scan issue for gen_site

- pyzoo/zoo/examples/pytorch/train/Lenet_mnist.py
- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
add mnist and resnet_finetune auto test
only pip version for resnet finetune
> add mnist and resnet_finetune auto test

- pyzoo/zoo/ray/util/raycontext.py
Default mkl-related environment variables would hinder performance for different frameworks.
Removed all of them.
If users want to set some/all of these environments, they could choose to pass in the env argument.
Fix #1831
> Remove default mkl settings when start ray

- pyzoo/zoo/automl/feature/time_sequence.py
fix bug in the case that too short input data frame for prediction cause error.
> fix bug of generated datetime while prediction

- docker/zoo/Dockerfile
Reverts intel-analytics/analytics-zoo#1842
> Revert "build docker for automl branch"

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
> add driver memory to incepitonv1 pip test

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
- pyzoo/zoo/examples/streaming/textclassification/streaming_text_classification.py
> add streaming auto test

- pyzoo/test/zoo/automl/pipeline/test_time_sequence.py
- pyzoo/zoo/automl/pipeline/time_sequence.py
add ppl.get_default_configs and UT
recommend to call ppl.get_default_configs before calling ppl.fit_with_fixed_configs
> add ppl.get_default_configs

- pyzoo/zoo/automl/model/Seq2Seq_pytorch.py
test results:
training for 20 epochs, 
keras version, train_loss: 0.21->0.04; val_loss: 0.21->0.07
pytorch version: train_loss: 0.42-> 0.01; val_loss: 0.25->0.1
May need further check on the difference between the two versions
> Add Pytorch seq2seq model

- apps/anomaly-detection-hd/README.md
- apps/anomaly-detection/README.md
- apps/dogs-vs-cats/README.md
- apps/image-augmentation-3d/README.md
- apps/image-augmentation/README.md
- apps/image-similarity/README.md
- apps/object-detection/README.md
- apps/pytorch/README.md
- apps/ray/parameter_server/README.md
- apps/recommendation-ncf/README.md
- apps/recommendation-wide-n-deep/README.md
- apps/sentiment-analysis/README.md
- apps/tfnet/README.md
- apps/variational-autoencoder/README.md
- docs/docs/DeveloperGuide/python.md
- docs/docs/ProgrammingGuide/visualization.md
- docs/docs/PythonUserGuide/install.md
- docs/docs/PythonUserGuide/python-faq.md
- docs/docs/PythonUserGuide/run.md
- docs/docs/README.md
- docs/docs/Readme.md
- pyzoo/zoo/examples/streaming/README.md
- pyzoo/zoo/examples/streaming/objectdetection/README.md
- pyzoo/zoo/examples/streaming/textclassification/README.md
Also some spark 1.6 stuff that I notice.
> Remove python2.7 and spark1.6 in doc

- apps/anomaly-detection-hd/README.md
- apps/anomaly-detection/README.md
- apps/dogs-vs-cats/README.md
- apps/image-augmentation-3d/README.md
- apps/image-augmentation/README.md
- apps/image-similarity/README.md
- apps/object-detection/README.md
- apps/pytorch/README.md
- apps/ray/parameter_server/README.md
- apps/recommendation-ncf/README.md
- apps/recommendation-wide-n-deep/README.md
- apps/sentiment-analysis/README.md
- apps/tfnet/README.md
- apps/variational-autoencoder/README.md
- docs/docs/DeveloperGuide/python.md
- docs/docs/ProgrammingGuide/visualization.md
- docs/docs/PythonUserGuide/install.md
- docs/docs/PythonUserGuide/python-faq.md
- docs/docs/PythonUserGuide/run.md
- docs/docs/README.md
- pyzoo/zoo/examples/streaming/README.md
- pyzoo/zoo/examples/streaming/objectdetection/README.md
- pyzoo/zoo/examples/streaming/textclassification/README.md
* update install guide
* update readme
* minor
* update spark version
* update
* update
* update
> [backport 0.7] Remove python2.7 and spark1.6 in doc (#1925)

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1947)
> fix wget issue

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/1948)
> fix wget issue (#1947)

- docs/docs/DeveloperGuide/python.md
- pyzoo/dev/build.sh
- pyzoo/dev/release.sh
- pyzoo/dev/release_default.sh
* add release default script
* minor
* doc
* minor
> Add release default script (#1941)

- docs/docs/ProgrammingGuide/inference.md
- pyzoo/zoo/examples/openvino/README.md
* Upgraded to Ubuntu 18.04.
* Remove Windows.
> Refine OpenVINO supported OS

- docs/docs/ProgrammingGuide/inference.md
- pyzoo/zoo/examples/openvino/README.md
* Refine OpenVINO supported OS.
* Remove small version.
> [Backport] Refine OpenVINO supported OS (#1958)

- pyzoo/zoo/common/utils.py
- pyzoo/zoo/tfpark/model.py
- zoo/src/main/scala/com/intel/analytics/zoo/common/PythonZoo.scala
- zoo/src/main/scala/com/intel/analytics/zoo/common/Utils.scala
If the model/weight path starts with "hdfs", KerasModel will load/save from HDFS.
Fix #1896
> [Issue #1896] KerasModel support saving and loading from HDFS

- pyzoo/zoo/feature/common.py
- pyzoo/zoo/util/spark.py
- zoo/pom.xml
- zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonFeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/Estimator.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/python/PythonEstimator.scala
Provide a way to reuse tensorflow's dataset.
like this:
```python
def train_fn():
import tensorflow_datasets as tfds
t = tfds.load(data_dir="/tmp/tfds/mnist", name="mnist", split=tfds.Split.TRAIN, as_supervised=True)
return t.map(_normalize_train_img).shuffle(1024) \
.batch(512).prefetch(tf.data.experimental.AUTOTUNE)
def test_fn():
import tensorflow_datasets as tfds
t = tfds.load(data_dir="/tmp/tfds/mnist", name="mnist", split=tfds.Split.TEST, as_supervised=True)
return t.map(_normalize_test_img) \
.batch(128).prefetch(tf.data.experimental.AUTOTUNE)
...
train_featureSet = FeatureSet.tf_dataset(train_fn)
test_featureSet = FeatureSet.tf_dataset(test_fn)
...
estimator.train_minibatch(train_featureSet,
zooCriterion, 
end_trigger=MaxEpoch(10), 
checkpoint_trigger=EveryEpoch(), …
```
> jep dataset

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/Net.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Embedding.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TopologySpec.scala
> Fix non-trainable param count in KerasNet model.summary

- docs/docs/ProgrammingGuide/rayonspark.md
> Update ray doc

- zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala
> writing to redis control

- README.md
> Fix tfpark link in README

- pyzoo/test/zoo/pipeline/inference/test_inference_model.py
- pyzoo/zoo/pipeline/inference/inference_model.py
- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModelFactory.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/PythonInferenceModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/README.md
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOInt8DeprecatedSuite.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOInt8Suite.scala
* Remove calibration from inference mode.
* Remove calibration from OpenVINOInferenceSupportive.
> Remove calibration from Zoo

- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala
> Fix generate indicator tensor in WND scala

- pyzoo/setup.py
Refer to Keras: https://github.com/keras-team/keras/blob/master/setup.py#L4
https://pypi.org/project/Keras/2.3.1/
Previous analytics-zoo: https://pypi.org/project/analytics-zoo/0.7.0/
> Add long description for pypi

- docker/cluster-serving/DockerFile
Add numactl dependency to cluster-serving Dockerfile
> Cluster-serving Dockerfile add numactl

- docs/docs/ProgrammingGuide/run-notebook-colab.md
- docs/mkdocs.yml
https://analytics-zoo.github.io/master/#ProgrammingGuide/run-notebook-colab/
Some contents not beautifully rendered.
Need more test when I go back to office. Put this PR here first.
> Polish doc style of Google colab

- zoo/src/main/scala/com/intel/analytics/zoo/examples/anomalydetection/AnomalyDetection.scala
this is try to fix spark example not stop on k8s cluster
need to build k8s image and test on k8s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2123)
> try to fix spark example not stop on k8s cluster

- scripts/cluster-serving/config.yaml
- zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala
Support Tensorflow saved model in cluster serving
> Cluster serving saved model support

- pyzoo/zoo/examples/anomalydetection/anomaly_detection.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2124)
> try to finish a spark job not complete issue for python

- zoo/src/test/resources/serving/imagenet_correctness.sh
- zoo/src/test/resources/serving/imagenet_enqueuer.py
The similar version of auto benchmark
and could also test correctness, and real world data benchmark
user has to specify image path and total image number, because serving has to check if the number are consistent and no data would be lost
> Cluster Serving imagenet correctness auto script

- pyzoo/zoo/zouwu/README.md
* some fixes in input shape descripitons
* rewording 
* add comparison between built-in models and AutoTS
> update zouwu README with autots and built-in model comparison

- docs/docs/gettingstarted.md
- docs/mkdocs.yml
K8s document link is a placeholder and to be updated.
> Add a Getting Started page

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
to fix https://github.com/intel-analytics/analytics-zoo/issues/2174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2186)
> fix ftp uri issue

- docs/docs/ClusterServingGuide/ProgrammingGuide.md
Add descriptions of performance mode, filter & TensorFlow saved model.
> Cluster serving programming guide config description modification

- apps/variational-autoencoder/using_variational_autoencoder_and_deep_feature_loss_to_generate_faces.ipynb
- apps/variational-autoencoder/using_variational_autoencoder_to_generate_faces.ipynb
- apps/variational-autoencoder/utils.py
try to fix https://github.com/intel-analytics/analytics-zoo/issues/2187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2197)
> fix vae with scipy issue

- apps/variational-autoencoder/using_variational_autoencoder_and_deep_feature_loss_to_generate_faces.ipynb
- apps/variational-autoencoder/using_variational_autoencoder_to_generate_faces.ipynb
- apps/variational-autoencoder/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2202)
> remove unnecessary scipy import

- zoo/src/main/scala/com/intel/analytics/zoo/common/PythonInterpreter.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
- zoo/src/test/scala/com/intel/analytics/zoo/common/PythonInterpreterSpec.scala
add singleton PythonInterpreter
> Add a uniform jepinterpreter API

- docs/docs/ProgrammingGuide/xshard.md
- docs/mkdocs.yml
- pyzoo/zoo/examples/xshard/README.md
Fix xshard name upper/lower case. Update docs.
> update docs for xshard

- pyzoo/zoo/examples/run-example-test-ray.sh
- pyzoo/zoo/examples/run-example-tests-pip-ray.sh
File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/mxnet/test_utils.py", line 1780, in get_mnist_ubyte
os.makedirs('data')
File "/opt/work/conda/envs/py37/lib/python3.7/os.py", line 221, in makedirs
mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'data'
Don't know why there is probably a file named data...
> Follow up to fix mxnet integration

- pyzoo/zoo/examples/tensorflow/tfpark/tf_optimizer/train.py
- pyzoo/zoo/tfpark/tf_optimizer.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
> Fix TFPark checkpoint missing

- apps/model-inference-examples/text-classification-training/src/main/scala/com/intel/analytics/zoo/apps/textclassfication/training/TextClassificationTrainer.scala
- pyzoo/zoo/examples/anomalydetection/README.md
- pyzoo/zoo/examples/anomalydetection/anomaly_detection.py
- pyzoo/zoo/examples/nnframes/finetune/image_finetuning_example.py
- pyzoo/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearningExample.py
- pyzoo/zoo/examples/qaranker/README.md
- pyzoo/zoo/examples/ray/mxnet/README.md
- pyzoo/zoo/examples/ray/mxnet/lenet_mnist.py
- pyzoo/zoo/examples/textclassification/README.md
- pyzoo/zoo/ray/mxnet/mxnet_runner.py
- pyzoo/zoo/ray/mxnet/mxnet_trainer.py
- pyzoo/zoo/ray/mxnet/utils.py
- zoo/src/main/scala/com/intel/analytics/zoo/examples/qaranker/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/README.md
- Add readme
- Add validation for gluon model
- Fix some errors in doc: iterations -> epochs
> Add README for MXNet LeNet example

- pyzoo/test/zoo/tfpark/test_tfpark_tfoptimizer.py
- pyzoo/zoo/examples/tensorflow/tfpark/inception/inception.py
- pyzoo/zoo/tfpark/tf_optimizer.py
- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/GraphRunner.scala
- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/TFTrainingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/python/PythonTFPark.scala
Support loading zoo checkpoint in TFOptimizer and resume training
```python
opt = TFOptimizer.from_loss(...)
opt.load_checkpoint(path, version=1000)
opt.optimize()
```
> Support loading zoo checkpoint in TFOptimizer

- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/TFUtils.scala
> Fix top5 accuracy

- docker/cluster-serving/DockerFile
- docker/hyperzoo/Dockerfile
- docker/jenkins-ci/jenkins-master/Dockerfile
- docker/jenkins-ci/jenkins-slave/Dockerfile
- docker/zoo/Dockerfile
try to fix issue https://github.com/intel-analytics/analytics-zoo/issues/2218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2219)
> fix jdk download issue

- pyzoo/zoo/examples/ray/mxnet/lenet_mnist.py
- pyzoo/zoo/examples/run-example-test-ray.sh
- pyzoo/zoo/examples/run-example-tests-pip-ray.sh
http://10.239.47.210:18888/job/ZOO-PR-Python-ExampleTests-py36/439/console
Found the root cause of such random failure.
Two workers are downloading the data to the same location, as there is no something like lock, this would cause a problem.
> Fix MXNet example download issue

- docs/docs/examples.md
- docs/docs/gettingstarted.md
- docs/mkdocs.yml
1. add examples.md page
2. update gettingstarted.md page
> Add examples.md page

- zoo/src/test/scala/com/intel/analytics/zoo/common/PythonInterpreterSpec.scala
Find existing spark context. Checking the spark conf...
Exception encountered when invoking run on a nested suite - requirement failed: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/ *** ABORTED ***
java.lang.IllegalArgumentException: requirement failed: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
at scala.Predef$.require(Predef.scala:224)
at com.intel.analytics.bigdl.utils.Engine$.com$intel$analytics$bigdl$utils$Engine$$verify$1(Engine.scala:418)
at com.intel.analytics.bigdl.utils.Engine$$anonfun$checkSparkContext$1.apply(Engine.scala:426)
at …
> fix a sc not stop error

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
need to replace hdfs site on different env
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2245)
> fix hdfs hard code issue

- docs/docs/ProgrammingGuide/visualization.md
- pyzoo/zoo/tfpark/model.py
- pyzoo/zoo/tfpark/tf_optimizer.py
* fix tfpark train summary
* fix summary
> [Bug Fix] Fix KerasModel and TFEstimator summary

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2248)
> fix hard code path issue

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
and also fix typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2252)
> fix wrong file path check in python examples

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
* fix wrong file path check in python examples
* fix typo
> fix wrong file path check in python examples (#2252)

- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2257)
> fix mkdir but exists bug (#2255)

- docker/cluster-serving/DockerFile
- docker/hyperzoo/Dockerfile
- docker/jenkins-ci/jenkins-master/Dockerfile
- docker/jenkins-ci/jenkins-slave/Dockerfile
- docker/zoo/Dockerfile
old jdk url is not available now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2259)
> update jdk download url

- pyzoo/test/zoo/tfpark/test_tf_dataset.py
- pyzoo/zoo/tfpark/tf_dataset.py
* Support ArrayType in TFDataset.from_dataframe
* fix style
> [backport-0.8] Support ArrayType in TFDataset.from_dataframe

- pyzoo/zoo/pipeline/api/net/__init__.py
- pyzoo/zoo/pipeline/api/net/torch_net.py
remove some useless tf dependency in torch_net.py
> remove some useless dependency in torch_net.py

- docs/docs/APIGuide/TFPark/model.md
- docs/docs/APIGuide/TFPark/tf-optimizer.md
- pyzoo/zoo/tfpark/model.py
- pyzoo/zoo/tfpark/tf_optimizer.py
1. it does not work now
2. it makes more sense to support it in TFDataset if needed
> Temporarily drop support for val_split

- pyzoo/test/zoo/tfpark/test_tfpark_model.py
- pyzoo/zoo/tfpark/tf_optimizer.py
> [Fix #2144] add input checking code for keras

- pyzoo/zoo/automl/model/time_sequence.py
- pyzoo/zoo/automl/search/RayTuneSearchEngine.py
This PR is to address comments in #2276.
> address comments in upgrade ray0.8.4

- pyzoo/test/zoo/pipeline/inference/test_inference_model.py
* Re-enable necessary test.
* Add a new test for `load_openvino` and `predict`.
> Refine OpenVINO Python unit test

- pyzoo/test/zoo/xshard/test_ray_pandas.py
- pyzoo/zoo/examples/xshard/ray_pandas.py
- pyzoo/zoo/examples/xshard/spark_pandas.py
- pyzoo/zoo/xshard/pandas/preprocessing.py
- pyzoo/zoo/xshard/shard.py
- pyzoo/zoo/xshard/utils.py
Add **kwargs support for read_csv, read_json.
Related issue:
analytics-zoo/orca#20
https://github.com/analytics-zoo/orca/issues/14
Refactor code.
> xShard arguments  support for read_csv on Ray

- scripts/cluster-serving/spark-streaming-cluster-serving-start
- zoo/src/main/scala/com/intel/analytics/zoo/serving/SparkStreamingClusterServing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/SparkStructuredStreamingClusterServing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/SparkReceiver.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/AsyncUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingManager.scala
for user use spark 1.6. and also 2.4 could be used if structured streaming is deprecated
> Cluster Serving spark streaming support

- docs/docs/ProgrammingGuide/orca-data.md
- pyzoo/test/zoo/orca/data/test_ray_pandas.py
- pyzoo/test/zoo/orca/data/test_spark_pandas.py
- pyzoo/zoo/orca/data/pandas/preprocessing.py
- pyzoo/zoo/orca/data/shard.py
Related issue [rename orca.data.DataShards to orca.data.XShards](https://github.com/analytics-zoo/orca/issues/26)
> Orca DataShards to XShards

- pyzoo/test/zoo/orca/data/test_utils.py
- pyzoo/zoo/orca/data/utils.py
https://github.com/analytics-zoo/orca/issues/8
https://github.com/analytics-zoo/orca/issues/9
Can Popen to execute a cat command to read hdfs text files. Alternatively, https://pypi.org/project/pydoop/ can be used as well.
> Add open_text and open_image in orca

- docs/docs/meetup.md
1) https://www.alluxio.io/resources/videos/ultra-fast-deep-learning-in-hybrid-cloud-using-intel-analytics-zoo-alluxio/
2) https://www.meetup.com/Shanghai-Apache-Spark-AI-Meetup/events/270598470/
> add 2 meetup links

- pyzoo/dev/run-pytests
- pyzoo/dev/run-pytests-jep.sh
- pyzoo/test/zoo/pipeline/api/torch/test_torch.py
- pyzoo/zoo/pipeline/api/torch/torch_model.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModel.scala
Convert TorchModel to pytorch model
> Convert TorchModel to pytorch model

- pyzoo/zoo/examples/orca/learn/mxnet/lenet_mnist.py
To avoid multiple processes downloading the dataset at the same time.
> Use filelock in MXNet LeNet example

- zoo/src/main/scala/com/intel/analytics/zoo/serving/http/FrontEndApp.scala
also add to wait a query to redis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2387)
> add metrics to predict api

- pyzoo/test/zoo/ray/test_ray_on_local.py
- pyzoo/zoo/ray/raycontext.py
Return plasma address, etc.
Same as ray.init(), it returns such info.
> RayContext init return address info

- apps/automl/nyc_taxi_dataset.ipynb
- pyzoo/test/zoo/automl/common/test_util.py
- pyzoo/test/zoo/automl/feature/test_time_sequence_feature.py
- pyzoo/zoo/automl/common/util.py
- pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_autots_forecasting.ipynb
Fix issue #2283, change split_input_df function.
> change split_input_df and its test case, not change the col name while splitting

- docs/docs/ProgrammingGuide/orca-data.md
- pyzoo/test/zoo/orca/data/test_spark_pandas.py
- pyzoo/zoo/examples/orca/data/spark_pandas.py
- pyzoo/zoo/orca/data/shard.py
Usage:
transformed_xshard = origin_xshard.transform_shard(func, *args)
> Orca  make SparkXShards immutable

- pyzoo/zoo/orca/learn/tf/estimator.py
> [Bug Fix] Fix pre init session

- pyzoo/zoo/orca/data/pandas/preprocessing.py
Remove ray dependency in orca.data.read_csv().
> Remove Ray dependency in read_csv

- pyzoo/test/zoo/orca/data/test_file.py
- pyzoo/zoo/orca/data/file.py
Add file utility functions: exists and makedirs, which support local/hdfs/s3 file systems.
> Orca file add exists, makedirs

- pyzoo/test/zoo/orca/data/test_spark_pandas.py
- pyzoo/zoo/orca/data/shard.py
related issue: [XShards __del__ gets exception if xshards was not cached before #2433](https://github.com/intel-analytics/analytics-zoo/issues/2433)
> [bugfix] Orca sparkxshards uncache bugfix

- pyzoo/test/zoo/orca/learn/mxnet/test_mxnet_ray_xshards.py
> Temporarily remove mxnet trainer list input test

- docs/docs/PythonUserGuide/install.md
- pyzoo/dev/release_default_linux.sh
- pyzoo/dev/release_default_mac.sh
Also split the release-default scripts for linux and mac.
As after running each release, the contents under `pyzoo/dist` would be removed.
> Update NB pip doc

- pyzoo/test/zoo/orca/data/test_spark_pandas.py
- pyzoo/zoo/orca/data/shard.py
Related issue [
Projection (selecting columns) for SparkXShards #54 ](https://github.com/analytics-zoo/orca/issues/54)
> Orca SparkXShard select

- pyzoo/test/zoo/orca/data/test_spark_pandas.py
- pyzoo/zoo/orca/data/shard.py
Update unique() and __len__()  without 'key' parameter according to XShards selection with [] support
> Update XShards unique and len according to XShards [] selection support

- pyzoo/test/zoo/automl/model/test_TCMF.py
- pyzoo/test/zoo/zouwu/test_model_forecast.py
- pyzoo/zoo/automl/model/tcmf_model.py
- pyzoo/zoo/zouwu/model/forecast.py
changes:
1. add docs
2. change some of the default values 
3. rename init_XF_epoch to init_FX_epoch
4. remove forward_cov and end_index.
> add zouwu tcmf docs

- docs/docs/APIGuide/AutoML/recipe.md
- docs/docs/Zouwu/tutorial.md
- pyzoo/test/zoo/zouwu/test_auto_ts.py
- pyzoo/test/zoo/zouwu/test_model_forecast.py
- pyzoo/zoo/automl/config/recipe.py
- pyzoo/zoo/automl/model/MTNet_keras.py
- pyzoo/zoo/automl/model/VanillaLSTM.py
- pyzoo/zoo/zouwu/model/forecast.py
- pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_autots_forecasting.ipynb
- pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_model_forecasting.ipynb
- scripts/data/NAB/nyc_taxi/get_nyc_taxi.sh
> zouwu lstm/mtnet forecaster interface change

- apps/tfnet/image_classification_inference.ipynb
- pyzoo/test/zoo/pipeline/api/keras/test_net.py
- pyzoo/zoo/pipeline/api/net/__init__.py
- pyzoo/zoo/pipeline/api/net/torch_net.py
- pyzoo/zoo/tfpark/tfnet.py
- pyzoo/zoo/util/utils.py
1. move tfnet.to_sample_rdd to zoo.util.utils
2. remove tfnet from pipeline.api
#2487 is a little complicated, let's do the easier part first.
> Move to_sample_rdd to utils and remove tfnet from pipeline api

- pyzoo/test/zoo/tfpark/test_text_estimators.py
- pyzoo/test/zoo/tfpark/test_tfpark_estimator.py
- pyzoo/zoo/examples/tensorflow/tfpark/estimator/estimator_dataset.py
- pyzoo/zoo/examples/tensorflow/tfpark/estimator/estimator_inception.py
- pyzoo/zoo/examples/tensorflow/tfpark/estimator/pre-made-estimator.py
- pyzoo/zoo/examples/tensorflow/tfpark/gan/gan_train_and_evaluate.py
- pyzoo/zoo/tfpark/__init__.py
- pyzoo/zoo/tfpark/estimator.py
- pyzoo/zoo/tfpark/gan/gan_estimator.py
- pyzoo/zoo/tfpark/model.py
- pyzoo/zoo/tfpark/text/estimator/bert_base.py
- pyzoo/zoo/tfpark/text/estimator/bert_classifier.py
- pyzoo/zoo/tfpark/text/estimator/bert_ner.py
- pyzoo/zoo/tfpark/text/estimator/bert_squad.py
- pyzoo/zoo/tfpark/tf_dataset.py
- pyzoo/zoo/tfpark/tf_optimizer.py
- pyzoo/zoo/tfpark/tf_predictor.py
- pyzoo/zoo/tfpark/tfnet.py
- pyzoo/zoo/tfpark/utils.py
- pyzoo/zoo/tfpark/zoo_optimizer.py
- pyzoo/zoo/util/tf.py
> Remove TF imports 

- scripts/data/NAB/nyc_taxi/get_nyc_taxi.sh
> Change nyc taxi link to public github link

- pyzoo/test/zoo/orca/learn/spark/test_estimator_for_spark.py
- pyzoo/zoo/orca/data/tf/data.py
Fix dataset for Orca tf estimator evaluation
> Fix dataset for Orca tf estimator evaluation

- pyzoo/zoo/feature/common.py
- zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonFeatureSet.scala
fix pytorch featureset, total train sample is incorrect.
> fix pytorch featureset, total train sample is incorrect.

- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/util/spark.py
Change drive classpath from sparkconf to submit option.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/2522
> fix driver classpath issue in init_spark_on_local

- pyzoo/zoo/serving/server.py
- zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkRedisSource.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/InferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/postprocessing/PostProcessing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/FileUtils.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/SerParams.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/Watcher.scala
- zoo/src/test/scala/com/intel/analytics/zoo/serving/CorrectnessSpec.scala
temporary solution for dynamic loading and some other fix for nightly version
> Cluster Serving dynamic loading and fix

- pyzoo/dev/run-pytests
- pyzoo/zoo/examples/orca/data/README.md
- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests.sh
Add orca tf estimator tests and orca data example to Jenkins.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/2528
> Add orca tf estimator tests and orca data example to Jenkins

- pyzoo/test/zoo/orca/data/test_spark_pandas.py
- pyzoo/test/zoo/orca/learn/mxnet/test_mxnet_gluon.py
- pyzoo/test/zoo/orca/learn/mxnet/test_mxnet_spark_xshards.py
- pyzoo/test/zoo/orca/learn/mxnet/test_mxnet_symbol.py
- pyzoo/zoo/examples/orca/learn/mxnet/lenet_mnist.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_runner.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_trainer.py
- pyzoo/zoo/orca/learn/mxnet/utils.py
> Refactor MXNet API

- pyzoo/zoo/automl/model/tcmf/DeepGLO.py
- pyzoo/zoo/automl/model/tcmf/LocalModel.py
- pyzoo/zoo/automl/model/tcmf/__init__.py
- pyzoo/zoo/automl/model/tcmf/data_loader.py
- pyzoo/zoo/automl/model/tcmf/local_model.py
- pyzoo/zoo/automl/model/tcmf_model.py
It seems cuda flag is already removed. So code cleaning contains:
* remove deprecate option
* optimize imports
* optimize class and filenames
> Clear tcmf code

- pyzoo/zoo/orca/learn/horovod/horovod_ray_runner.py
Simplify horovod start process. 
It also works around the cloudpickle conflict problem.
Instead of finding a common network interface among workers, just use the interface corresponding to the ip address returned by ray.
Tested on:
local
almaren cluster
yarn integration test cluster
> Simplify horovod start process

- zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala
> Fix Scala WND continuous features

- pyzoo/test/zoo/tfpark/test_tfpark_tfoptimizer.py
- pyzoo/zoo/tfpark/tf_optimizer.py
- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/TFTrainingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/TFTrainingHelperV2.scala
> Fix tfpark resume training exception

- zoo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2585)
> upgrade netty

- zoo/src/main/scala/com/intel/analytics/zoo/serving/http/FrontEndApp.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/http/domains.scala
try to fix:
https://github.com/intel-analytics/analytics-zoo/issues/2571
now the error response is:
```
Wrong content format.
Details: Cannot construct instance of `com.intel.analytics.zoo.serving.http.Instances`, problem: no instance can be found, please check your input or json(keyword should be 'instances')
at [Source: (String)"{
"instance" : [ {
"ids" : [ 100.0, 88.0 ]
}, {
"ids" : [ 100.0, 88.0 ]
}, {
"ids" : [ 100.0, 88.0 ]
}, {
"ids" : [ 100.0, 88.0 ]
}, {
"ids" : [ 100.0, 88.0 ]
} ]
}"; line: 13, column: 1]
Please refer to examples:
{
"instances" : [ {
"intScalar" : 12345,
"floatScalar" : 3.14159,
"stringScalar" : "hello, world. hello, zoo.",
"intTensor" : [ 7756, 9549, 1094, 9808, 4959, 3831, 3926, 6578, 1870, 1741 ],
"floatTensor" : [ 0.6804766, 0.30136853, 0.17394465, …
```
> enhance error report for http server

- pyzoo/test/zoo/orca/data/test_pandas_backend.py
- pyzoo/zoo/automl/model/tcmf_model.py
- pyzoo/zoo/orca/data/__init__.py
- pyzoo/zoo/orca/data/shard.py
Move load_pickle from SparkXShards to XShards.
Related issue: https://github.com/analytics-zoo/orca/issues/62
> move load_pickle to xshards

- pyzoo/zoo/models/recommendation/__init__.py
Reverts intel-analytics/analytics-zoo#2643
> Revert "Add TxT import"

- docs/docs/ProgrammingGuide/AnalyticsZoo-on-Databricks.md
To fix https://github.com/intel-analytics/analytics-zoo/issues/2648
> fix Databricks doc content link

- pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py
- pyzoo/zoo/orca/learn/horovod/horovod_ray_runner.py
- pyzoo/zoo/orca/learn/pytorch/__init__.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_horovod_estimator.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_trainer.py
- pyzoo/zoo/orca/learn/pytorch/torch_runner.py
- pyzoo/zoo/orca/learn/pytorch/training_operator.py
Support for Tianchi case so that users don't need to modify any baseline code.
- Support tuple input/output for TorchRunner
- PyTorchHorovodEstimator check data type (same as RaySGD)
- Several minor bugs brought in https://github.com/intel-analytics/analytics-zoo/pull/2602 @yangw1234 Please take a look.
> Several bug fixes for Orca Ray distributed PyTorch

- pyzoo/test/zoo/orca/data/test_partition.py
- pyzoo/zoo/orca/data/__init__.py
- pyzoo/zoo/orca/data/shard.py
- pyzoo/zoo/orca/learn/tf/estimator.py
sample code:
```python
import numpy as np
train_data = np.load("../../data/train.npy", allow_pickle=True)
val_data = np.load("../../data/val.npy", allow_pickle=True)
import zoo.orca.data as orca_data
train_x_shards = orca_data.partition(train_data)
val_x_shards = orca_data.partition(val_data)
metrics = {}
metrics["total_loss"] = model.keras_model.total_loss
from zoo.orca.learn.tf.estimator import Estimator
estimator = Estimator.from_keras(model.keras_model, metrics=metrics, model_dir="./logs")
estimator.fit(data=train_x_shards,
epochs=30,
batch_size=32,
validation_data=val_x_shards,
hard_code_batch_size=True,
session_config=tf.ConfigProto(inter_op_parallelism_threads=2, intra_op_parallelism_threads=24))
```
> support metrics in orca.tf.estimator.from_keras and support partition in orca.data

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
To fix https://github.com/intel-analytics/analytics-zoo/issues/2700
> fix realworld.zip link missing

- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/util/spark.py
- Add docs
- Support connecting to an existing standalone cluster.
> Update and add docs for Spark standalone

- pyzoo/dev/run-pytests-jep.sh
- pyzoo/test/zoo/pipeline/api/torch/test_torch.py
- pyzoo/test/zoo/pipeline/api/torch/test_torch_estimator.py
- pyzoo/zoo/feature/common.py
- pyzoo/zoo/pipeline/api/torch/torch_loss.py
- pyzoo/zoo/pipeline/api/torch/torch_model.py
- pyzoo/zoo/pipeline/api/torch/utils.py
- pyzoo/zoo/util/nest.py
- zoo/src/main/scala/com/intel/analytics/zoo/feature/FeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonFeatureSet.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModel.scala
Support create FeatureSet from pytorch dataloader creator functions.
> support create featureset from pytorch dataloader creator functions.

- pyzoo/zoo/orca/learn/pytorch/estimator.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_horovod_estimator.py
- pyzoo/zoo/orca/learn/pytorch/torch_runner.py
- pyzoo/zoo/orca/learn/pytorch/training_operator.py
Fix #2655 
Print out the progress bar during training.
> Expose tqdm in Horovod Estimator

- pyzoo/test/zoo/pipeline/api/torch/test_torch.py
- pyzoo/zoo/pipeline/api/torch/torch_model.py
fix to pytorch throws exception when model is frozen.
> fix to pytorch throws exception when model is frozen.

- pyzoo/zoo/orca/learn/pytorch/torch_runner.py
> Horovod Estimator validate check serialize_data_creation

- pyzoo/zoo/orca/learn/pytorch/estimator.py
> [hot fix] features and labels not exposed in Orca Estimator FeatureSet.pytorch_dataloader

- zoo/src/main/java/com/intel/analytics/zoo/pipeline/inference/AbstractInferenceModel.java
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/EncryptSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/InferenceModel.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/inference/EncryptSpec.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2729)
> add AES-256 encrypt and decrypt for inferencemodel model loading

- zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/Conventions.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/SerParams.scala
Whether OpenVINO model could be broadcast successfully does not matter now.
> Cluster Serving flink distributed to remote and load local model

- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/nnframes/XgboostTrainSpec.scala
resolve https://github.com/intel-analytics/analytics-zoo/issues/2726
> fix ut failure on mac

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/nnframes/NNClassifier.scala
xgboost bug fix for "xgboostError: check failed: jenv->exceptionoccurred()"
> Xgbregressor bug fix

- pyzoo/zoo/examples/pytorch/train/mnist/README.md
- pyzoo/zoo/pipeline/api/torch/torch_loss.py
- pyzoo/zoo/pipeline/api/torch/torch_model.py
throw exception when jep is not installed and update readme
fix #2690
> throw exception when jep is not installed

- pyzoo/test/zoo/orca/learn/spark/test_estimator_for_spark.py
- pyzoo/test/zoo/orca/learn/spark/test_estimator_keras_for_spark.py
- pyzoo/zoo/orca/learn/tf/estimator.py
- pyzoo/zoo/orca/learn/tf/utils.py
Add save() method in Orca tf estimator. 
For graph model, it would save current session to tf checkpoint.
For keras model, it would save wrapped keras model to file system.
Also change load_checkpoint() to load_orca_checkpoint().
Change load_latest_checkpoint() to load_latest_orca_checkpoint()
> Orca tf estimator save model

- pyzoo/zoo/orca/learn/horovod/horovod_ray_runner.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_horovod_estimator.py
- pyzoo/zoo/orca/learn/tf2/tf_ray_estimator.py
- pyzoo/zoo/orca/learn/tf2/tf_runner.py
> [Horovod] Support multiple workers in one spark executor

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
fix pytorch evaluation throws exception when core>1
> fix pytorch evaluation throws exception when core>1

- docs/docs/ProgrammingGuide/pytorch.md
> update pytorch document

- pyzoo/test/zoo/orca/learn/ray/mxnet/test_mxnet_gluon_multiple_input.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_runner.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_trainer.py
Fix https://github.com/intel-analytics/analytics-zoo/issues/2437
> MXNet Estimator support multiple inputs/outputs for Gluon

- pyzoo/dev/run-pytests
- pyzoo/test/zoo/orca/data/conftest.py
- pyzoo/test/zoo/orca/learn/jep/test_pytorch_estimator_for_dataloader.py
- pyzoo/test/zoo/orca/learn/jep/test_pytorch_estimator_for_spark.py
- pyzoo/test/zoo/orca/learn/jep/test_pytorch_estimator_for_spark_creator.py
- pyzoo/test/zoo/orca/learn/ray/mxnet/conftest.py
- pyzoo/test/zoo/orca/learn/ray/mxnet/test_mxnet_gluon_multiple_input.py
- pyzoo/test/zoo/orca/learn/ray/pytorch/conftest.py
- pyzoo/test/zoo/orca/learn/ray/tf/conftest.py
- pyzoo/test/zoo/orca/learn/spark/conftest.py
- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/examples/orca/data/README.md
- pyzoo/zoo/examples/orca/data/spark_pandas.py
- pyzoo/zoo/examples/orca/learn/bigdl/pytorch/mnist/README.md
- pyzoo/zoo/examples/orca/learn/bigdl/pytorch/mnist/lenet_mnist.py
- pyzoo/zoo/examples/orca/learn/horovod/README.md
- pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py
- pyzoo/zoo/examples/orca/learn/horovod/resnet-50-imagenet.py
- pyzoo/zoo/examples/orca/learn/horovod/simple_horovod_pytorch.py
- pyzoo/zoo/examples/orca/learn/mxnet/README.md
- pyzoo/zoo/examples/orca/learn/mxnet/lenet_mnist.py
- pyzoo/zoo/examples/orca/learn/tf/lenet_mnist_graph.py
- pyzoo/zoo/examples/orca/learn/tf/lenet_mnist_keras.py
- pyzoo/zoo/orca/common.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_trainer.py
- pyzoo/zoo/orca/learn/pytorch/utils.py
- pyzoo/zoo/ray/process.py
- pyzoo/zoo/ray/raycontext.py
- Update all UTs and examples in Orca.
- Update README.
- Fix some import ray issues.
> Update UTs and examples with init_orca_context

- pyzoo/zoo/common/nncontext.py
- zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/utils/Reflection.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/estimator/Estimator.scala
> enable DistriOptimizerV2

- docs/docs/Orca/context.md
- docs/mkdocs.yml
- pyzoo/zoo/orca/common.py
> Add website doc for init_orca_context

- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/InferenceSupportive.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/Timer.scala
This is timer which is not thread safe, thus only used in sequential pipeline. Noted multi-thread timer is not useful, because timing should be analyzed in sequential pipeline but not parallel operations.
Want to use dependencies as few as possible, thus did not use accumulators.
> Cluster Serving Timer

- pyzoo/zoo/util/spark.py
add java_home to standalone env， fixed #2811
> add java_home to standalone env

- docker/hyperzoo/Dockerfile
- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/ray/raycontext.py
- pyzoo/zoo/util/spark.py
- pyzoo/zoo/util/utils.py
- Add init_spark_on_k8s
- Code refactor for yarn, standalone and k8s
> Support init_spark_on_k8s

- docs/docs/powered-by.md
- docs/docs/presentations.md
1) update presentations https://www.intel.cn/content/www/cn/zh/service-providers/analytics-zoo-helps-tencent-cloud-improve-ti-ml-platform-performance.html
2) update 3 talks at OpML 2020 and Ray Summit Connect 2020
> update presentations and powerby

- pyzoo/zoo/util/engine.py
Reverts intel-analytics/analytics-zoo#2628
fixed #2664 
The original problem is fixed by #2743
> Revert "temporary fix org.tensorflow.util conflict"

- docs/docs/Orca/orca-tf-estimator.md
- pyzoo/zoo/common/utils.py
- pyzoo/zoo/examples/orca/learn/tf/lenet_mnist_keras.py
- pyzoo/zoo/orca/learn/tf/estimator.py
- pyzoo/zoo/tfpark/model.py
> Orca tf save_keras_model add overwrite option

- pyzoo/zoo/util/spark.py
> add LD_PRELOAD to init_spark_on_yarn

- pyzoo/zoo/examples/vnni/openvino/README.md
- zoo/src/main/scala/com/intel/analytics/zoo/examples/vnni/openvino/README.md
* Update OpenVINO and model zoo links. Add OpenVINO DL Workbench link.
* resnet-50-tf link.
> Refine OpenVINO VNNI example model Optimization related document

- pyzoo/zoo/automl/model/__init__.py
- pyzoo/zoo/automl/model/tcmf/DeepGLO.py
- pyzoo/zoo/automl/model/tcmf/data_loader.py
- pyzoo/zoo/automl/model/tcmf/local_model.py
- pyzoo/zoo/automl/model/tcmf/local_model_distributed_trainer.py
- pyzoo/zoo/automl/model/tcmf_model.py
Note that the distributed option only exposed to zoo.automl.model.tcmf_model and haven't expose to zouwu forecaster yet.
> [WIP] add distributed tcmf (train y seq)

- pyzoo/zoo/orca/common.py
- pyzoo/zoo/util/spark.py
> Add stop_orca_context to python exit handler

- pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py
> fix nn classifier falky test

- pyzoo/zoo/ray/raycontext.py
> Hotfix for ray psutil on macOS

- pyzoo/dev/build.sh
- pyzoo/dev/release.sh
- pyzoo/dev/release_default_linux.sh
- pyzoo/dev/release_default_mac.sh
Fix #2852 
quick = true won't build the jar.
> Add quick option when building python whl

- scripts/cluster-serving/config.yaml
- zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/ZooBaseline.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/ClusterServingInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkRedisSource.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/operator/ClusterServingInferenceOperator.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/preprocessing/PreProcessing.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/SerParams.scala
and remove "single" mode for user, to reduce their choices.
> Cluster Serving switching to optimized INT8 performance design

- pyzoo/zoo/examples/orca/learn/bigdl/pytorch/mnist/lenet_mnist.py
- pyzoo/zoo/orca/learn/pytorch/estimator.py
Support pytorch optimizer in orca estimator
> Support pytorch optimizer in orca estimator

- docs/docs/Orca/orca-pytorch-estimator.md
- pyzoo/zoo/orca/learn/pytorch/estimator.py
TODO: load checkpoint in estimator
> Orca PyTorch Estimator Add model_dir and Clipping Methods

- zoo/src/main/resources/spark-analytics-zoo.conf
- zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonFeatureSet.scala
Fixed #2915
load opencv before createFeatuerSetFromImageSet.
> fix createFeatuerSetFromImageSet may throw java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()J

- pyzoo/test/zoo/automl/model/test_xgbregressor.py
- pyzoo/zoo/automl/model/__init__.py
> remove automl model init imports to fix jenkins fail

- pyzoo/zoo/zouwu/examples/README.md
- pyzoo/zoo/zouwu/examples/run_electricity.py
> [WIP]add electricity example for zouwu tcmf distributed

- docs/docs/Zouwu/API/TCMFForecaster.md
- docs/docs/Zouwu/tutorials/TCMFForecaster.md
- pyzoo/test/zoo/automl/model/test_TCMF.py
- pyzoo/test/zoo/zouwu/model/forecast/test_tcmf_forecaster.py
- pyzoo/zoo/automl/model/tcmf/DeepGLO.py
- pyzoo/zoo/automl/model/tcmf_model.py
- pyzoo/zoo/zouwu/examples/README.md
- pyzoo/zoo/zouwu/examples/run_electricity.py
- pyzoo/zoo/zouwu/model/forecast/tcmf_forecaster.py
Create a new PR for tcmf fit incremental since there has been a lot of changes since PR #2560 
tasks
> add tcmf fit incremental

- pyzoo/zoo/pipeline/api/torch/torch_optim.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchOptim.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/net/TorchOptimSpec.scala
support epochdecay iterationdecay epochdecaybyscore in TorchOptim
> support epochdecay iterationdecay epochdecaybyscore in TorchOptim

- docs/docs/Zouwu/API/TCMFForecaster.md
- docs/docs/Zouwu/tutorials/TCMFForecaster.md
- pyzoo/test/zoo/automl/model/test_TCMF.py
- pyzoo/test/zoo/zouwu/model/forecast/test_tcmf_forecaster.py
- pyzoo/zoo/automl/model/tcmf/DeepGLO.py
- pyzoo/zoo/automl/model/tcmf_model.py
- pyzoo/zoo/zouwu/examples/run_electricity.py
- pyzoo/zoo/zouwu/model/forecast/tcmf_forecaster.py
> Fix zouwu TCMFForecaster interface

- zoo/pom.xml
- zoo/src/main/scala/com/intel/analytics/zoo/examples/serving/ClusterServingFlinkSqlExample.scala
- zoo/src/main/scala/com/intel/analytics/zoo/examples/serving/ClusterServingFunction.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/operator/ClusterServingFunction.scala
VVP Function is ready for launch
Kafka feature is only the first version
> Cluster Serving new VVP Function

- pyzoo/test/zoo/orca/data/test_spark_backend.py
- pyzoo/zoo/orca/data/pandas/preprocessing.py
Add schema and options for Orca read_parquet
> Add options for orca read_parquet

- pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py
- pyzoo/zoo/orca/data/shard.py
- pyzoo/zoo/orca/data/utils.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_runner.py
- pyzoo/zoo/orca/learn/mxnet/mxnet_trainer.py
- pyzoo/zoo/orca/learn/tf2/tf_ray_estimator.py
- pyzoo/zoo/orca/learn/tf2/tf_runner.py
example code
```python
rdd = sc.parallelize([0]*1000, 20)
ray_rdd = RayRdd.from_spark_rdd(rdd)
ray_rdd2 = ray_rdd.map_partitions_with_actors(actors, predict_fn)
rdd2 = ray_rdd2.to_spark_rdd(sc)
```
> Connect rdd data into ray cluster for processing and send back to rdd

- pyzoo/test/zoo/orca/learn/ray/pytorch/test_pytorch_estimator.py
- pyzoo/test/zoo/orca/learn/ray/pytorch/test_pytorch_trainer.py
- pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_ray_estimator.py
- pyzoo/zoo/orca/learn/pytorch/torch_runner.py
Fix #2998 
@yangw1234 Take a look.
Also torch model and torch loss are also callable, can't use callable to identify the input is a function.
> Orca PyTorch Estimator input torch loss instance

- pyzoo/test/zoo/automl/feature/test_time_sequence_feature.py
- pyzoo/zoo/automl/feature/time_sequence.py
> automl allow future time in feature

- scripts/cluster-serving/config.yaml
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkRedisSink.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkRedisSource.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/SerParams.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/3024)
> cluster serving fix timeout issue

- zoo/src/test/scala/com/intel/analytics/zoo/serving/models/OpenVINOModelSpec.scala
Add cluster serving test code for openvino models of Inception v1, mobilenet v1,v2, resnet50 and vgg16.
> add cluster serving test for openvino models of inception,mobilenet,resnet50,vgg16

- pyzoo/test/zoo/automl/feature/test_time_sequence_feature.py
- pyzoo/zoo/automl/feature/time_sequence.py
- pyzoo/zoo/automl/regression/base_predictor.py
This PR is related to issue #3023 .
1. Change the implementation to built-in pandas implementation. 
2. Remove dependency on `featuretools`.
3. Add some features in TCMF `time.py`.
> Automl TimeSequenceFeature change to pandas implementation

- docs/docs/ClusterServingGuide/ProgrammingGuide.md
- pyzoo/zoo/serving/client.py
- scripts/cluster-serving/cluster-serving-init
- scripts/cluster-serving/cluster-serving-start
- zoo/src/main/scala/com/intel/analytics/zoo/serving/ClusterServing.scala
@glorysdj could check if any other log need to refine
> Cluster Serving log, script, doc refine

- apps/automl/README.md
- docs/docs/PythonUserGuide/python-lib-version.md
- pyzoo/setup.py
- pyzoo/zoo/automl/feature/identity_transformer.py
- pyzoo/zoo/automl/feature/time_sequence.py
Related to issue #3051 
`featuretools` has been removed from the codes in PR #3029
> Remove featuretools from setup.py and docs

- pyzoo/test/zoo/orca/learn/spark/test_estimator_for_spark.py
- pyzoo/test/zoo/orca/learn/spark/test_estimator_keras_for_spark.py
- pyzoo/zoo/orca/learn/tf/estimator.py
- pyzoo/zoo/tfpark/model.py
- pyzoo/zoo/tfpark/tf_optimizer.py
> expose bigdl optim method to orca tf estimators

- pyzoo/test/zoo/automl/impute/__init__.py
- pyzoo/test/zoo/automl/impute/test_impute.py
- pyzoo/zoo/automl/impute/impute.py
- pyzoo/zoo/orca/data/elastic_search.py
1. Support TimeMergeImputor to merge time which are seconds apart
2. Add flatten method to elastic_search to parse loading data
3. Fix comments
> Add TimeMergeImputor and flatten

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
disable facegen example temporarily, will enable this test when update the notebook.
> disable pytorch face-gen

- docs/docs/powered-by.md
> Update powered-by.md 

- zoo/pom.xml
> fix no scala-library in Httpjar

- pyzoo/zoo/automl/search/ray_tune_search_engine.py
> address comments

- pyzoo/zoo/util/utils.py
Fix #3147 
command -v python fails to detect the conda env for jupyter notebook.
conda info fails to detect the conda name for anaconda2.
> Fix detect_python_location and detect_conda_env

- zoo/src/main/scala/com/intel/analytics/zoo/common/PythonInterpreter.scala
fix jep stuck in scala 2.12, and add a 100s timeout in jep.
> fix jep stuck in scala 2.12

- pom.xml
- zoo/pom.xml
> fix profile spark version doens't work in IDE's maven

- docs/docs/Zouwu/tutorials/Autots.md
- pyzoo/zoo/zouwu/use-case/AIOps/README.md
- pyzoo/zoo/zouwu/use-case/network_traffic/README.md
> Fix zouwu use-case installation docs

- zoo/src/main/scala/com/intel/analytics/zoo/tfpark/TFModelBroadcast.scala
Fix TFModelBroadcast issue on cluster.
> Fix TFModelBroadcast

- pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py
- pyzoo/zoo/orca/learn/pytorch/torch_runner.py
* fix ddp
* add model join
* fix
* add ut
* remove join
* remove debug msg
> [backport 0.9] Fix missing DDP in torch distributed (#3185)

- pyzoo/zoo/ray/raycontext.py
* Fix macOS ZombieProcess
* Add ProcessLookupError catch
> [Backport] Fix macOS ZombieProcess Exception

- docker/cluster-serving/Dockerfile
- docker/cluster-serving/image_classification_and_object_detection_quick_start.py
- docs/docs/ClusterServingGuide/ProgrammingGuide.md
Change docker image to use pip install
and update quick start to match latest version
> Cluster Serving Docker

- pyzoo/zoo/examples/orca/learn/pytorch/cifar10/cifar10.py
- pyzoo/zoo/examples/orca/learn/pytorch/fashion-mnist/fashion-mnist.py
- pyzoo/zoo/examples/run-example-test-ray.sh
- pyzoo/zoo/examples/run-example-tests-pip-ray.sh
The example should be ok to run after fixing #3233
> Add back example test for fashion-mnist

- pyzoo/zoo/common/nncontext.py
> fix init_nncontext cannot be called twice when log_output set to true

- zoo/src/main/scala/com/intel/analytics/zoo/models/image/common/ImageModel.scala
Fix ObjectDetecter to load finetuned ssd model.
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/3299
> fix ObjectDetecter to load finetuned ssd model

- pyzoo/test/zoo/automl/common/test_metrics.py
- pyzoo/zoo/automl/common/metrics.py
- pyzoo/zoo/automl/model/XGBoost.py
Use a reshape operation before calling sklearn.mean_squared_error
> change metrics in automl to support higher dim

- docs/docs/colab-notebook/orca/quickstart/tf2_keras_lenet_mnist.ipynb
- docs/docs/colab-notebook/run-notebook-test-tf2.sh
- readthedocs/source/doc/Orca/QuickStart/orca-tf2-quickstart.md
Colab notebook link:  https://colab.research.google.com/github/Le-Zheng/analytics-zoo/blob/tf2doc/docs/docs/colab-notebook/orca/quickstart/tf2_keras_lenet_mnist.ipynb
For https://github.com/intel-analytics/analytics-zoo/issues/3372
> TF2 quickstart

- pyzoo/zoo/automl/model/base_pytorch_model.py
Change to support torch data loader while training.
> use torch dataset and dataloader util for automl pytorch based model

- pyzoo/dev/run-pytests-jep.sh
- pyzoo/test/zoo/orca/learn/jep/test_pytorch_estimator_for_dataframe.py
- pyzoo/test/zoo/orca/learn/ray/pytorch/conftest.py
- pyzoo/test/zoo/orca/learn/ray/pytorch/test_estimator_pytorch_backend.py
- pyzoo/test/zoo/orca/learn/ray/tf/conftest.py
- pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py
- pyzoo/test/zoo/orca/learn/spark/test_estimator_keras_for_spark.py
- pyzoo/test/zoo/orca/learn/test_utils.py
- pyzoo/zoo/orca/data/utils.py
- pyzoo/zoo/orca/learn/bigdl/estimator.py
- pyzoo/zoo/orca/learn/openvino/estimator.py
- pyzoo/zoo/orca/learn/pytorch/estimator.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_ray_estimator.py
- pyzoo/zoo/orca/learn/pytorch/torch_runner.py
- pyzoo/zoo/orca/learn/tf/estimator.py
- pyzoo/zoo/orca/learn/tf/utils.py
- pyzoo/zoo/orca/learn/tf2/estimator.py
- pyzoo/zoo/orca/learn/tf2/tf_runner.py
- pyzoo/zoo/orca/learn/utils.py
> clean up orca estimators predict

- docs/docs/APIGuide/FeatureEngineering/image.md
- zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala
Fixed: https://github.com/intel-analytics/analytics-zoo/issues/2612#event-4215794800
> Update Imageset read docs

- pyzoo/test/zoo/automl/model/test_tcn.py
- pyzoo/zoo/automl/config/recipe.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
- pyzoo/zoo/automl/model/model_builder.py
- pyzoo/zoo/automl/model/tcn.py
> Change TCN model and recipe to fit TS forcasting task

- pyzoo/zoo/orca/data/ray_rdd.py
> Remove meta store from ray rdd

- pyzoo/test/zoo/orca/learn/spark/test_estimator_for_bigdl.py
- pyzoo/zoo/orca/data/utils.py
- pyzoo/zoo/orca/learn/utils.py
Reverts intel-analytics/analytics-zoo#3436
accidently press merge.
> Revert "support multi-inputs model in bigdl estimator when data is xshards"

- docker/hyperzoo/Dockerfile
to fix https://github.com/intel-analytics/analytics-zoo/issues/3428
> update hyperzoo docker image

- docker/hyperzoo/Dockerfile
https://github.com/intel-analytics/analytics-zoo/issues/2816
> update hyperzoo image

- pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py
fix http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Python-integration-test-horovod/15/
> fix default arguments (driver port)

- pyzoo/zoo/examples/orca/learn/bigdl/resnet_finetune/README.md
- pyzoo/zoo/examples/orca/learn/bigdl/resnet_finetune/resnet_finetune.py
- pyzoo/zoo/examples/run-example-tests-jep.sh
- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests-yarn-integration.sh
- pyzoo/zoo/examples/run-example-tests.sh
Ported from [resnet_finetune](https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/pytorch/train/resnet_finetune)
> Orca bigdl example: Resnet_finetune

- pyzoo/zoo/examples/orca/learn/bigdl/imageInference/README.md
- pyzoo/zoo/examples/orca/learn/bigdl/imageInference/imageInference.py
- pyzoo/zoo/examples/run-example-tests-pip.sh
- pyzoo/zoo/examples/run-example-tests-yarn-integration.sh
- pyzoo/zoo/examples/run-example-tests.sh
Ported from [imageInference](https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/nnframes/imageInference)
> Orca bigdl example: imageInference

- pyzoo/zoo/automl/config/recipe.py
> change recipe bug and expose

- pyzoo/test/zoo/automl/model/test_VanillaLSTM.py
- pyzoo/test/zoo/automl/model/test_base_keras_model.py
- pyzoo/test/zoo/automl/model/test_base_pytorch_model.py
- pyzoo/zoo/automl/model/base_keras_model.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
- pyzoo/zoo/automl/model/model_builder.py
- pyzoo/zoo/examples/automl/plugin_model_demo.py
make sure the fit_eval does not create model all the time
> conditionally create model in automl model fit_eval method 

- docker/hyperzoo/Dockerfile
this is a update to hyperzoo to fit it with cnvrg.io jupyter noetbook
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/3486)
> update python dep to fit cnvrg

- readthedocs/source/doc/UserGuide/hadoop.md
- readthedocs/source/doc/UserGuide/python.md
- Fix JAVA_HOME on centos
- Fix typo for OpenJDK
> Fix install java doc on centos

- pyzoo/test/zoo/automl/feature/test_time_sequence_feature.py
- pyzoo/zoo/automl/feature/time_sequence.py
> add time_feature use/drop option

- ppml/trusted-big-data-ml/scala/docker-graphene/Dockerfile
- ppml/trusted-big-data-ml/scala/docker-graphene/Makefile
- ppml/trusted-big-data-ml/scala/docker-graphene/README.md
- ppml/trusted-big-data-ml/scala/docker-graphene/bigdl.lenet.training.patch
- ppml/trusted-big-data-ml/scala/docker-graphene/init.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/java.manifest.template
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-local-train-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-driver-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-master-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-worker-sgx.sh
ppml/trusted-big-data-ml is tested and ready
> add ppml docker for ppml/trusted-big-data-ml

- pyzoo/test/zoo/orca/data/test_spark_backend.py
- pyzoo/zoo/orca/common.py
- pyzoo/zoo/orca/data/elastic_search.py
- pyzoo/zoo/orca/data/pandas/preprocessing.py
- Add get_spark_session and get_sql_context
- Update the related spark session code.
> Add get_spark_session in OrcaContext

- readthedocs/source/doc/Orca/Overview/data-parallel-processing.md
- readthedocs/source/doc/Orca/Overview/distributed-training-inference.md
Update documents for previous `batch_size` related changes.
> Update for batch_size related documents 

- pyzoo/zoo/orca/learn/horovod/horovod_ray_runner.py
> Support horovod above 0.20.x

- pyzoo/test/zoo/orca/learn/test_metrics.py
- pyzoo/zoo/orca/learn/metrics.py
- pyzoo/zoo/orca/learn/pytorch/pytorch_metrics.py
> Implement Orca Pytorch metrics

- pyzoo/test/zoo/automl/model/test_base_pytorch_model.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
Add onnx method predict_with_onnx and evaluate_with_onnx and a internal method _build_onnx
related to issue #3349
> Onnx pytorch base model

- pyzoo/test/zoo/zouwu/model/forecast/test_tcn_forecaster.py
- pyzoo/zoo/automl/model/tcn.py
> Make sure TCN config can interpret num_channels as well as (hidsize, level)

- pyzoo/zoo/automl/model/base_pytorch_model.py
> vis progress during automl pytorch base model training

- ppml/trusted-cluster-serving/scala/docker-graphene/Dockerfile
- ppml/trusted-cluster-serving/scala/docker-graphene/README.md
- ppml/trusted-cluster-serving/scala/docker-graphene/cluster-serving-config.yaml
- ppml/trusted-cluster-serving/scala/docker-graphene/init-cluster-serving.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/init-java.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/init-redis.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/java.Makefile
- ppml/trusted-cluster-serving/scala/docker-graphene/java.manifest.template
- ppml/trusted-cluster-serving/scala/docker-graphene/redis-server.manifest.template
- ppml/trusted-cluster-serving/scala/docker-graphene/redis.Makefile
- ppml/trusted-cluster-serving/scala/docker-graphene/start-all.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/start-cluster-serving-job.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/start-flink-jobmanager.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/start-flink-taskmanager.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/start-http-frontend.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/start-redis.sh
cluster serving docker imclude distributed and all-in-one in local mode is ready
will add doc later in another pr
> add ppml docker for trusted-cluster-serving [WIP]

- docs/docs/colab-notebook/orca/quickstart/ncf_dataframe.ipynb
- docs/docs/colab-notebook/orca/quickstart/tf2_keras_lenet_mnist.ipynb
ray1.2.0 has conflicts with `aiohttp` version installed on colab. It requires to specify the available version.
> fix Ray1.2 on colab error message

- pyzoo/zoo/examples/orca/learn/pytorch/cifar10/README.md
update packages needed by cifar10 examples in README
> update cifar10 environment

- pyzoo/test/zoo/zouwu/model/forecast/test_tcn_forecaster.py
- pyzoo/zoo/zouwu/model/forecast/tcn_forecaster.py
add tcn forecaster onnx interface.
> add tcn_forecaster onnx

- docs/docs/colab-notebook/run-notebook-tf1.sh
- docs/docs/colab-notebook/zouwu/zouwu_autots_nyc_taxi.ipynb
- docs/readthedocs/source/doc/Zouwu/QuickStart/zouwu-autots-quickstart.md
- docs/readthedocs/source/index.rst
> Add Zouwu quick start in readthedocs

- ppml/trusted-big-data-ml/scala/docker-graphene/Dockerfile
- ppml/trusted-big-data-ml/scala/docker-graphene/README.md
- ppml/trusted-big-data-ml/scala/docker-graphene/environment.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-distributed-big-data-ml.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-driver-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-master-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-worker-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/stop-distributed-big-data-ml.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/3613)
> add passwordless and start distributed all in one scripts

- ppml/trusted-cluster-serving/scala/docker-graphene/README.md
- ppml/trusted-cluster-serving/scala/docker-graphene/environment.sh
- ppml/trusted-cluster-serving/scala/docker-graphene/start-distributed-cluster-serving.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/3627)
> modify distributed all in one scripts

- docs/readthedocs/source/doc/UseCase/keras-api.md
- docs/readthedocs/source/doc/UseCase/nnframes.md
change uppercase letters to lower case letters when page relocation.
demo:  https://testhelendoc.readthedocs.io/en/latest/doc/UseCase/nnframes.html
> fix: uppercase letters are not supported in page relocation

- docs/docs/Zouwu/API/TCNForecaster.md
- pyzoo/zoo/zouwu/model/forecast/tcn_forecaster.py
Since there will be some change for the TCNForecaster, the doc revise PR will stay WIP after all other changes are completed and merged
> TCNForecaster doc revise

- docs/docs/colab-notebook/orca/quickstart/keras_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/ncf_dataframe.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_distributed_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/tf2_keras_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/tf_lenet_mnist.ipynb
- docs/docs/colab-notebook/zouwu/zouwu_autots_nyc_taxi.ipynb
- docs/readthedocs/source/doc/UserGuide/colab.md
- docs/readthedocs/source/doc/UserGuide/python.md
- docs/readthedocs/source/doc/Zouwu/Overview/zouwu.md
- pyzoo/zoo/examples/orca/learn/bigdl/attention/README.md
- pyzoo/zoo/examples/orca/learn/bigdl/imageInference/README.md
- pyzoo/zoo/examples/orca/learn/tf/basic_text_classification/README.md
Tested that `--upgrade --pre` would always install the latest nightly build whl.
> Add --upgrade option to --pre

- pyzoo/test/zoo/pipeline/api/torch/test_torch.py
- pyzoo/zoo/common/utils.py
- pyzoo/zoo/pipeline/api/torch/torch_model.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TorchModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/python/PythonZooNet.scala
Load torch model from java value
fixed #3606
> Load torch model from java value

- ppml/README.md
- ppml/scripts/generate-keys.sh
- ppml/scripts/generate-password.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/README.md
- ppml/trusted-cluster-serving/scala/docker-graphene/Dockerfile
- ppml/trusted-cluster-serving/scala/docker-graphene/README.md
- ppml/trusted-cluster-serving/scala/docker-graphene/start-local-cluster-serving.sh
very short readme for ppml and graphene
> draft ppml readme

- pyzoo/zoo/common/utils.py
- pyzoo/zoo/tfpark/model.py
The over_write option was not applied when save to remote file
> Fix overwrite issue in save model

- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/ClusterServingInference.scala
- zoo/src/test/scala/com/intel/analytics/zoo/serving/CorrectnessSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/serving/models/OpenVINOModelSpec.scala
remove the adding dim operation before predict to support batch inference of openvino model
add openvino face detection 0100 model to openvino model specific test
add batch inference for correctness unit test
> remove add dim of input for openvino for batch infer

- pyzoo/zoo/orca/learn/metrics.py
- pyzoo/zoo/pipeline/api/keras/metrics.py
- pyzoo/zoo/pipeline/api/keras/utils.py
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/MSE.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
- zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/metrics/MSESpec.scala
> add MSE metric for bigdl backend

- ppml/trusted-big-data-ml/scala/docker-graphene/Dockerfile
Fixed #3661
This spark-network-common.jar is build with this change https://github.com/qiuxin2012/spark/commit/af5446bc20e200d8e5d3690f8563b09060160d42.
> download spark-network-common

- pyzoo/zoo/orca/learn/mpi/mpi_runner.py
> Fix get host ips for MPIRunner

- pyzoo/zoo/serving/client.py
- scripts/cluster-serving/config.yaml
- zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/InferenceBaseline.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/MockSinglePipelineBaseline.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/baseline/OpenVINOBaseline.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/ClusterServingInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/engine/FlinkInference.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/operator/ClusterServingFunction.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/operator/ClusterServingInferenceOperator.scala
- zoo/src/main/scala/com/intel/analytics/zoo/serving/utils/ClusterServingHelper.scala
- zoo/src/test/scala/com/intel/analytics/zoo/serving/CorrectnessSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/serving/models/OpenVINOModelSpec.scala
- zoo/src/test/scala/com/intel/analytics/zoo/serving/models/TensorflowModelSpec.scala
Reverts intel-analytics/analytics-zoo#3732
> Revert "Cluster Serving add batch inference"

- pyzoo/zoo/examples/orca/learn/pytorch/super_resolution/README.md
- pyzoo/zoo/examples/orca/learn/pytorch/super_resolution/super_resolution.py
- pyzoo/zoo/examples/run-example-test-ray.sh
- pyzoo/zoo/examples/run-example-tests-jep.sh
- pyzoo/zoo/examples/run-example-tests-pip-ray.sh
Add different backends for orca pytorch super resolution example.
> Orca pytorch superresolution

- pyzoo/test/zoo/zouwu/model/forecast/test_seq2seq_forecaster.py
- pyzoo/zoo/zouwu/model/Seq2Seq.py
- pyzoo/zoo/zouwu/model/Seq2Seq_pytorch.py
- pyzoo/zoo/zouwu/model/forecast/seq2seq_forecaster.py
This forcaster is based on new pytorch model. API is the same as TCNForecaster. pytorch model is slightly changed for onnx support
> Add Seq2SeqForecaster based on pytorch model

- docs/docs/Zouwu/API/TCNForecaster.md
- pyzoo/zoo/zouwu/model/forecast/tcn_forecaster.py
> Add validation set option for fit method in TCNForecaster

- docs/readthedocs/source/doc/PythonAPI/Friesian/feature.rst
- docs/readthedocs/source/index.rst
- pyzoo/test/zoo/friesian/feature/test_table.py
- pyzoo/zoo/examples/friesian/feature/dlrm_preprocessing.py
- pyzoo/zoo/friesian/feature/table.py
- zoo/src/main/scala/com/intel/analytics/zoo/friesian/feature/Utils.scala
> Add friesian docs, make freq_limit more user friendly

- pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py
- pyzoo/zoo/orca/data/ray_xshards.py
> Fix RayXShards fail with empty partitions

- ppml/trusted-big-data-ml/scala/docker-graphene/bigdl.lenet.training.patch
- ppml/trusted-big-data-ml/scala/docker-graphene/java.manifest.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-analytics/analytics-zoo/3801)
> fix graphene spark release issues

- ppml/trusted-big-data-ml/scala/docker-graphene/ppml-spark-submit.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-local-train-sgx.sh
- ppml/trusted-big-data-ml/scala/docker-graphene/start-spark-standalone-driver-sgx.sh
> add ppml-spark-submit.sh

- pyzoo/zoo/examples/orca/automl/autoxgboost/AutoXGBoostRegressor.py
- pyzoo/zoo/zouwu/config/recipe.py
Related to issue #3827
Related PR #3726
> fix XgbRegressorSkOptRecipe cannot find tune

- ppml/trusted-big-data-ml/scala/docker-graphene/README.md
- ppml/trusted-realtime-ml/scala/docker-graphene/README.md
- ppml/trusted-realtime-ml/scala/docker-graphene/check-status.sh
- ppml/trusted-realtime-ml/scala/docker-occlum/Dockerfile
- ppml/trusted-realtime-ml/scala/docker-occlum/README.md
- ppml/trusted-realtime-ml/scala/docker-occlum/check-status.sh
* Fix occlum Trusted Realtime ML analytics-zoo build
* Fix typo in doc and check-status.sh
> [PPML] Fix occlum AZ build

- pyzoo/test/zoo/automl/model/test_base_keras_model.py
- pyzoo/test/zoo/automl/model/test_base_pytorch_model.py
- pyzoo/zoo/automl/model/base_keras_model.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
> Add check in automl base models

- apps/run-app-tests-pip.sh
The test failed on MAC because the data corrupted. 
This PR download data from FTP and force rewrite the data.
> Fix zouwu aiops anomaly detection app test

- docs/readthedocs/source/doc/PPML/Overview/ppml.md
> backport ppml doc to branch 0.10

- docs/readthedocs/source/doc/PPML/Overview/ppml.md
- ppml/trusted-big-data-ml/scala/docker-graphene/README.md
- ppml/trusted-realtime-ml/scala/docker-graphene/README.md
- ppml/trusted-realtime-ml/scala/docker-occlum/README.md
* Refine generate-keys permission and doc. Add root permission warning
* Refine doc
> [PPML] Refine generate-keys permission and doc

- docs/readthedocs/source/doc/PPML/Overview/ppml.md
- ppml/trusted-big-data-ml/scala/docker-graphene/README.md
- ppml/trusted-realtime-ml/scala/docker-graphene/README.md
- ppml/trusted-realtime-ml/scala/docker-occlum/README.md
* Refine generate-keys permission and doc. Add root permission warning
* Refine doc
> [Backport][PPML] Refine generate-keys permission and doc

- pyzoo/test/zoo/automl/common/test_metrics.py
- pyzoo/zoo/automl/common/metrics.py
- Fix large array metrics precision error 
- Add multidim support for R2, MAE and MSLE
> Fix large array metrics precision error & add highdim support for some metrics

- README.md
- docs/readthedocs/source/doc/PPML/Overview/ppml.md
- docs/readthedocs/source/index.rst
backport 3 files:
1)ppml.md
2)readme
3)index.rst
> [backport Branch 0.10] backport doc changes

- docs/docs/release-docs.md
- docs/docs/release-download.md
- docs/readthedocs/source/doc/release.md
back port Branch 0.10 download links in https://github.com/intel-analytics/analytics-zoo/pull/3872
> [backport] Branch 0.10 download links

- pyzoo/test/zoo/automl/model/test_base_pytorch_model.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
> AutoML pytorch base model predict method change to dataldr implementation

- pyzoo/zoo/automl/logger/tensorboardxlogger.py
- pyzoo/zoo/automl/search/base.py
- pyzoo/zoo/automl/search/ray_tune_search_engine.py
- Move `_log_adapt` function to logger
- Remove `GridSearch`, `RandomSample`, `BayersianOpt`
- Remove shape transformer from searcher
- Remove `_is_validation_df_valid`, `_prepare_trainable_class`, `_prepare_tune_config`
- Remove redundant comment
- Add function doc
> Code clean for RayTuneSearcherEngine

- pyzoo/test/zoo/automl/model/test_base_keras_model.py
- pyzoo/test/zoo/automl/model/test_base_pytorch_model.py
- pyzoo/test/zoo/orca/automl/xgboost/test_xgbregressor.py
- pyzoo/test/zoo/zouwu/model/test_Seq2Seq.py
- pyzoo/test/zoo/zouwu/model/test_Seq2Seq_pytorch.py
- pyzoo/test/zoo/zouwu/model/test_TCMF.py
- pyzoo/test/zoo/zouwu/model/test_VanillaLSTM.py
- pyzoo/test/zoo/zouwu/model/test_mtnet.py
- pyzoo/test/zoo/zouwu/model/test_tcn.py
- pyzoo/zoo/automl/model/abstract.py
- pyzoo/zoo/automl/model/base_keras_model.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
- pyzoo/zoo/automl/search/ray_tune_search_engine.py
- pyzoo/zoo/examples/automl/plugin_model_demo.py
- pyzoo/zoo/orca/automl/xgboost/XGBoost.py
- pyzoo/zoo/zouwu/model/MTNet_keras.py
- pyzoo/zoo/zouwu/model/Seq2Seq.py
- pyzoo/zoo/zouwu/model/forecast/seq2seq_forecaster.py
- pyzoo/zoo/zouwu/model/forecast/tcn_forecaster.py
- pyzoo/zoo/zouwu/model/tcmf_model.py
- pyzoo/zoo/zouwu/model/time_sequence.py
- pyzoo/zoo/zouwu/pipeline/time_sequence.py
from fit_eval(x, y ...) to fit_eval(data, ...)
> API change for all fit_eval method in automl related models

- pyzoo/zoo/examples/orca/automl/autoestimator/autoestimator_pytorch.py
- pyzoo/zoo/examples/run-example-test-ray.sh
- pyzoo/zoo/examples/run-example-tests-pip-ray.sh
completed create and Copy some existing functions
> new example for ut:test_autoestimator_pytorch

- pyzoo/zoo/automl/recipe/base.py
- pyzoo/zoo/automl/search/ray_tune_search_engine.py
- pyzoo/zoo/zouwu/config/recipe.py
1. remove `SEARCH_ALG_ALLOWED`.
2. remove `manual_search_space` in recipe.
> AutoML RayTuneSearcher search alg clean up

- pyzoo/test/zoo/automl/model/test_base_pytorch_model.py
- pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_pytorch.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
- pyzoo/zoo/orca/automl/hp.py
support code for ray tune searcher and autoest ut should be added later.
some code inherited from #3894
> Automl data creator support for pytorch

- pyzoo/test/zoo/orca/data/test_write_parquet.py
- pyzoo/zoo/orca/data/image/__init__.py
- pyzoo/zoo/orca/data/image/parquet_dataset.py
> Orca Data Image Write API

- docs/readthedocs/source/doc/PPML/Overview/ppml.md
- ppml/README.md
- ppml/trusted-realtime-ml/scala/docker-graphene/start-local-cluster-serving.sh
- ppml/trusted-realtime-ml/scala/docker-occlum/start-local-cluster-serving.sh
* Refine PPML README.md and link
* Add Occlum Link in PPML.md
> [PPML] Refine PPML README & Link

- pyzoo/zoo/orca/automl/auto_estimator.py
Add API documentation for Orca AutoEstimator.
> Add API documentation for Orca AutoEstimator

- docs/docs/powered-by.md
- docs/readthedocs/source/doc/Application/powered-by.md
1. Inspur: 
https://dpgresources.intel.com/asset-library/inspur-end-to-end-smart-computing-solution-with-intel-analytics-zoo/
2.Alibaba:
https://www.intel.com/content/www/us/en/artificial-intelligence/posts/alibaba-privacy-preserving-machine-learning.html
3. Burger-king: 
https://venturebeat.com/2021/04/06/how-intel-and-burger-king-built-an-order-recommendation-system-that-preserves-customer-privacy/
> add 3 links in powerby pages

- pyzoo/zoo/examples/tensorflow/tfpark/estimator/estimator_inception.py
please reference to this [commit](https://github.com/intel-analytics/analytics-zoo/commit/86c2ff6974b42f49ca9aac23d492b5d085bcf472) for all changes.
> add --batch_size option

- pyzoo/zoo/examples/tensorflow/tfpark/tf_optimizer/evaluate.py
add `data_path` option in evaluate.py file.
please reference to this [commit](https://github.com/intel-analytics/analytics-zoo/commit/abfee6d955e5503a8aaba69d108e6da508557ff9) for all changes
> add --data_path option

- pyzoo/test/zoo/chronos/data/__init__.py
- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/zoo/chronos/data/tsdataset.py
This PR will add from_pandas, init and to_pandas function
> TSDataset in and out method function

- pyzoo/test/zoo/chronos/data/utils/test_roll.py
- pyzoo/zoo/chronos/data/utils/roll.py
Roll will generate numpy arrays from dataframe
Roll will support strides and shifts. 
Different behavior for train/eval vs test
id sensitive or id-insensitive mode will be implement in tsdataset.py rather than utils function
> TSDataset roll utils function

- pyzoo/test/zoo/friesian/feature/test_table.py
- pyzoo/zoo/friesian/feature/table.py
add more types: boolean, short
add corresponding check
remove pyspark.sql.types from documentation
> Add more types support for recsys challenge cast operation

- pyzoo/test/zoo/chronos/model/anomaly/test_dbscan_detector.py
- pyzoo/zoo/chronos/model/anomaly/dbscan_detector.py
TODO:
* notebooks 
* add roll window based detection. (apply dbscan directly may generate high local false positives and negatives, window based approach may be able to resolve this. refer to https://aditya-bhattacharya.net/2020/07/20/sales-and-demand-forecast-analysis/3/)
* add more unittests (window-based approach, univariate input, more DBScan arguments)
> Add DBscan anomaly detector

- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVINOModel.scala
- zoo/src/main/scala/com/intel/analytics/zoo/pipeline/inference/OpenVinoInferenceSupportive.scala
* Change predict output from JTensor to List<JTensor>
* Fix maskrcnn, Yolo output issues.
> [OpenVINO] Change predict output from JTensor to List<JTensor>

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/zoo/chronos/data/tsdataset.py
- pyzoo/zoo/chronos/data/utils/scale.py
Some minor helper function need to be filled in (in later pr)
> Add scale/unscale method for TSDataset

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/zoo/chronos/data/tsdataset.py
- pyzoo/zoo/chronos/data/utils/split.py
Call method
```python
df = get_multi_id_ts_df()
tsdata_train, tsdata_valid, tsdata_test =\
TSDataset.from_pandas(df, dt_col="datetime", target_col="value",
extra_feature_col=["extra feature"], id_col="id",
with_split=True, val_ratio=0.1, test_ratio=0.1)
```
> Add split method for tsdataset initialization

- pyzoo/test/zoo/chronos/model/anomaly/test_th_detector.py
- pyzoo/zoo/chronos/model/anomaly/abstract.py
- pyzoo/zoo/chronos/model/anomaly/ae_detector.py
- pyzoo/zoo/chronos/model/anomaly/th_detector.py
issue #4029 
1. add anomaly_indexes() for ThreasholdDetector and in base class
2. unify anomaly_scores_ and anomaly_indexes_ class variable names
> anomaly indexes function for Anomaly Detectors 

- pyzoo/test/zoo/automl/searcher/test_ray_tune_search_engine.py
- pyzoo/test/zoo/orca/automl/xgboost/test_auto_xgb.py
- pyzoo/test/zoo/orca/automl/xgboost/test_xgbregressor.py
- pyzoo/zoo/automl/search/ray_tune_search_engine.py
- pyzoo/zoo/orca/automl/auto_estimator.py
- pyzoo/zoo/orca/automl/xgboost/XGBoost.py
Fix bug: `metric` value passed through xgboost `fit_eval` doesn't take effect.
> Fix xgboost metric

- pyzoo/test/zoo/chronos/model/anomaly/test_ae_detector.py
- pyzoo/zoo/chronos/model/anomaly/ae_detector.py
> add pytorch implementation and ut of autoencoder model for AE

- pyzoo/test/zoo/chronos/model/anomaly/test_ae_detector.py
- pyzoo/test/zoo/chronos/model/anomaly/test_dbscan_detector.py
- pyzoo/test/zoo/chronos/model/anomaly/test_th_detector.py
- pyzoo/zoo/chronos/model/anomaly/ae_detector.py
- pyzoo/zoo/chronos/model/anomaly/th_detector.py
add unit tests for corner cases and direct approach for AEDetector
#4029
> unit tests for anomaly detectors

- pyzoo/zoo/common/nncontext.py
- pyzoo/zoo/orca/common.py
- pyzoo/zoo/ray/raycontext.py
First launch the ray master using spark and then launch raylets in two stages.
> Add support for non-barrier mode to launch ray

- docker/hyperzoo/README.md
- docker/zoo/README.md
- docker/zoo/start-notebook.sh
- docs/docs/DockerUserGuide/index.md
- docs/docs/ProgrammingGuide/k8s.md
- docs/readthedocs/source/doc/UserGuide/docker.md
- docs/readthedocs/source/doc/UserGuide/k8s.md
> fix 4087 issue

- docs/readthedocs/source/doc/UserGuide/k8s.md
Delete the notes updated in last pr
Add a section "Common topics for both client mode and cluster mode", includes:
1. How to debug ray issues?
2. How to deal with "JSONDecodeError" ?
3. How to use NFS?
4. How to deal with  "RayActorError" ?
5. How to set proper "steps_per_epoch" and "validation steps" ?
6. spark.kubernetes.container.image.pullPolicy needs to be specified as always.
> update k8s doc

- docs/readthedocs/source/doc/PythonAPI/Chronos/anomaly_detectors.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/forecasters.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/index.rst
- docs/readthedocs/source/index.rst
- pyzoo/zoo/chronos/model/anomaly/ae_detector.py
- pyzoo/zoo/chronos/model/anomaly/dbscan_detector.py
- pyzoo/zoo/chronos/model/anomaly/th_detector.py
Add readthedocs documents for three anomaly detectors #4029
You can preview the doc [here](https://yuyin-analytics-zoo.readthedocs.io/en/latest/doc/PythonAPI/Chronos/anomaly_detectors.html)
> Api docs for anomaly detectors

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
> rm rolling feature in test_tsdataset_unscale_numpy

- docs/docs/ProgrammingGuide/rayonspark.md
- docs/docs/PythonUserGuide/python-lib-version.md
- docs/readthedocs/source/doc/Orca/Overview/orca-context.md
- docs/readthedocs/source/doc/Ray/Overview/ray.md
- docs/readthedocs/source/doc/Ray/QuickStart/ray-quickstart.md
- docs/readthedocs/source/doc/UserGuide/python.md
- Add barrier_mode in doc
- Remove pyarrow==0.17.0
> Add Ray doc for non-barrier mode

- apps/run-app-tests-pip.sh
> update anomaly detector notebook paths in scripts

- ppml/trusted-big-data-ml/python/docker-graphene/start-spark-standalone-master-sgx.sh
- ppml/trusted-big-data-ml/python/docker-graphene/start-spark-standalone-worker-sgx.sh
- Modify master and worker start scripts to support bigdl example
> Modify master and worker start scripts to support bigdl example

- docs/readthedocs/requirements-doc.txt
- docs/readthedocs/source/doc/PythonAPI/Chronos/index.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/tsdataset.rst
- pyzoo/zoo/chronos/data/tsdataset.py
You can preview the doc at [here](https://yuyin-analytics-zoo.readthedocs.io/en/latest/doc/PythonAPI/Chronos/tsdataset.html)
> api docs for tsdataset 

- ppml/trusted-big-data-ml/python/docker-graphene/README.md
- add bigdl lenet example to README
- replace secret key in command line with "your_secret_key"
> add bigdl lenet example to README

- ppml/trusted-big-data-ml/python/docker-graphene/README.md
- Add Xgboost example in python graphene README
- Change specific master url to your_master_url in command
> Add xgboost example in python graphene README

- pyzoo/test/zoo/chronos/model/forecast/test_prophet_forecaster.py
- pyzoo/zoo/chronos/model/forecast/prophet_forecaster.py
Add Chronos Prophet Forecaster.
> Add Chronos Prophet Forecaster

- docs/readthedocs/source/doc/Chronos/Overview/chronos.md
- docs/readthedocs/source/doc/PythonAPI/AutoML/automl.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/autots.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/index.rst
- pyzoo/test/zoo/chronos/autots/model/test_auto_lstm.py
- pyzoo/test/zoo/chronos/autots/test_experimental.py
- pyzoo/test/zoo/chronos/model/forecast/test_prophet_forecaster.py
- pyzoo/zoo/automl/model/base_pytorch_model.py
- pyzoo/zoo/chronos/autots/experimental.py
- pyzoo/zoo/chronos/autots/forecast.py
- pyzoo/zoo/chronos/autots/model/__init__.py
- pyzoo/zoo/chronos/autots/model/auto_lstm.py
- pyzoo/zoo/chronos/config/recipe.py
- pyzoo/zoo/chronos/data/tsdataset.py
- pyzoo/zoo/chronos/model/forecast/prophet_forecaster.py
- pyzoo/zoo/orca/automl/hp.py
You can preview the docs here 
User guide: https://testshanedoc.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html
Python API docs: https://testshanedoc.readthedocs.io/en/latest/doc/PythonAPI/Chronos/index.html
> Update Chronos User Guide and Python API docs

- pyzoo/setup.py
related to issue #4137 and pr #4140
> Change versions of scipy and aioredis in automl extra require

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/test/zoo/chronos/data/utils/test_resample.py
- pyzoo/zoo/chronos/data/tsdataset.py
- pyzoo/zoo/chronos/data/utils/resample.py
> Add default values for tsdataset resample function parameters

- pyzoo/dev/run-pytests-ray
- pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_keras.py
- pyzoo/test/zoo/orca/automl/autoestimator/test_autoestimator_pytorch.py
> May fix jenkins AutoEstimator randomly fail

- docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/run-notebook-pytorch.sh
- docs/readthedocs/source/doc/Orca/QuickStart/orca-autoestimator-pytorch-quickstart.md
- docs/readthedocs/source/index.rst
This PR added a quick start for `AutoEstimator` with pytorch in COMMON USE CASE
You can review the quick start at 
https://auto-estimator.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-autoestimator-pytorch-quickstart.html
> Add autoestimator quick start

- pyzoo/test/zoo/chronos/autots/test_experimental.py
- pyzoo/zoo/chronos/autots/experimental.py
- pyzoo/zoo/chronos/autots/model/auto_lstm.py
- pyzoo/zoo/chronos/autots/model/auto_tcn.py
> Experimental AutoTSTrainer support 3rd party model with feature selection tuning

- pyzoo/zoo/orca/learn/tf2/estimator.py
> remove max_length calculation in orca estimators

- pyzoo/zoo/tfpark/__init__.py
> fix py36 tf version checking issue

- pyzoo/test/zoo/friesian/feature/test_table.py
> test_clip unit test hot fix

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/zoo/chronos/data/tsdataset.py
> fix tsdataset roll(id_sensitive=True) target first ordering issue

- docs/readthedocs/source/doc/UserGuide/python.md
> revise protobuf version in doc

- docs/readthedocs/source/doc/PythonAPI/Chronos/autots.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/autotsestimator.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/index.rst
- pyzoo/zoo/chronos/autots/experimental/autotsestimator.py
- pyzoo/zoo/chronos/autots/experimental/tspipeline.py
prereview the doc here: https://junweitestdoc.readthedocs.io/en/auotsest-api-doc/doc/PythonAPI/Chronos/index.html
related to #4187
> add experimental AutoTSEstimator API doc

- docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb
- docs/docs/colab-notebook/run-notebook-pytorch.sh
- docs/readthedocs/source/doc/Orca/QuickStart/orca-autoestimator-pytorch-quickstart.md
- docs/readthedocs/source/doc/Orca/QuickStart/orca-autoxgboost-quickstart.md
- docs/readthedocs/source/index.rst
Preview documents: https://add-xgb-quick-start.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-autoxgboost-quickstart.html
quick start notebook: https://github.com/yushan111/analytics-zoo/blob/add-xgb-quick-start/docs/docs/colab-notebook/orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb
> Add AutoXGBoost quick start

- pyzoo/zoo/orca/learn/tf2/tf_runner.py
Add rank and size in config for data creator to use
> Add rank and size  in config for training and validation data creator in TFRunner

- docs/readthedocs/source/doc/Chronos/Overview/chronos.md
I include some detailed information in this version of TSDataset UG.
You can preview the doc here: https://junweitestdoc.readthedocs.io/en/tsdataset-user-guide/doc/Chronos/Overview/chronos.html#data-processing-and-feature-engineering
1. What can we do through TSDataset ?
2. How can we do these things through TSDataset ?
3. (not for every subsection) Why should we do this?
1. Overview block diagram (future overview)
2. Detailed behavior of each parameter (API doc)
3. Runnable code (Quick start)
> TSDataset user guide revision

- docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb
> fix colab orca.automl examples for 0.11.0

- docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb
1. fix old links
2. fix tensorboardx
related to #4263
> fix colab orca.automl examples

- ppml/trusted-big-data-ml/scala/docker-occlum/Dockerfile
Fixed the unzip command for docker-occlum spark
> [branch-0.11-RC1] Fixing docker-occlum spark

- ppml/trusted-big-data-ml/scala/docker-occlum/Dockerfile
Fixed the unzip command for docker-occlum spark
> [branch-0.11] Fixing docker-occlum spark

- pyzoo/zoo/common/utils.py
- pyzoo/zoo/orca/learn/pytorch/estimator.py
- pyzoo/zoo/orca/learn/tf/estimator.py
- pyzoo/zoo/orca/learn/tf2/estimator.py
- pyzoo/zoo/tfpark/model.py
> Support save & load from hdfs in orca estimators

- ppml/trusted-realtime-ml/scala/docker-occlum/deploy-flink.sh
Fixed PATH issues with starting distributed realtime occlum flink
> [PPML] Fix distributed realtime occlum

- ppml/trusted-realtime-ml/scala/docker-occlum/deploy-flink.sh
Fixed PATH issues with starting distributed realtime occlum flink
> [PPML] Fix distributed realtime occlum (master branch)

- docs/readthedocs/source/doc/UserGuide/notebooks.md
1. Add readdoc for fashion_mnist, basic_test_classification, super_resolution
2. Add AI Application Class
> add readdoc for colab-notebook orca example

- docs/readthedocs/source/doc/Chronos/Overview/chronos.md
related to #4312 .
preview [here](https://junweitestdoc.readthedocs.io/en/doc-automl-0.11/doc/Chronos/Overview/chronos.html#install)
> Change UG for chronos installation in 0.11.0

- pyzoo/zoo/chronos/data/tsdataset.py
speed up ~150X on baidu traffic dataset
related to #4186
> TSDataset deduplicate method speed up

- pyzoo/zoo/util/utils.py
This modification has been tested using a tf2/keras  model through Orca TF2 APIs.
> support pyspark.sql.types.StringType column

- pyzoo/zoo/automl/model/base_pytorch_model.py
Add a batch_size setting to control the mem usage for base model
> Chronos: fix onnx inference oom problem by adding batch_size

- docs/docs/colab-notebook/run-notebook-pytorch.sh
Downloading dataset from external websites is unstable:
http://10.239.176.111:18888/job/ZOO-PR-Colab-Pytorch/1223/console
so we prepare dataset in advance.
> Prepare BSDdataset in advance at colabnotebook test

- pyzoo/zoo/chronos/use-case/network_traffic/network_traffic_multivariate_multistep_tcnforecaster.ipynb
> Chronos: fix notebook path name

- docs/readthedocs/source/doc/PPML/Overview/ppml.md
- add how to run user's own pyspark program to ppml doc
This PR is to add the instructions for user to run his self-developed pyspark program.
We will also add similar instructions to scala/java part.
It's tested with a sample pyspark program.
> add how to run user's own pyspark program to ppml doc

- docs/readthedocs/source/doc/PPML/Overview/ppml.md
- ppml/trusted-big-data-ml/python/docker-graphene/README.md
- add how to run user's spark program to ppml doc scala 
- add how to run user's pyspark program to python graphene readme
> add how to run user's spark and pyspark program to doc and readme

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/test/zoo/chronos/data/utils/test_resample.py
- pyzoo/zoo/chronos/data/tsdataset.py
- pyzoo/zoo/chronos/data/utils/resample.py
> TSDataset impute/resample/gen_dt_feature method speed up

- pyzoo/test/zoo/orca/learn/ray/tf/test_tf_ray_estimator.py
- pyzoo/zoo/orca/learn/utils.py
> [Fix #4328]Repartition validation data for zip reduce RayXShards

- docs/docs/colab-notebook/orca/examples/super_resolution.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_distributed_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist_data_creator_func.ipynb
Convert 7 colab examples to python 3.7.10 to solve errors caused by new updated python vision in Colab.
> Colab update

- docs/docs/colab-notebook/orca/examples/fashion_mnist_bigdl.ipynb
- docs/docs/colab-notebook/orca/examples/super_resolution.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoestimator_pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/autoxgboost_regressor_sklearn_boston.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_distributed_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist.ipynb
- docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist_data_creator_func.ipynb
> Colab url update

- zoo/pom.xml
Reverts intel-analytics/analytics-zoo#4372
> Revert "Grpc dependency hot fix"

- apps/model-inference-examples/recommendation-inference/pom.xml
- zoo/pom.xml
> Spark 3.1.2 

- docs/readthedocs/source/doc/PythonAPI/AutoML/automl.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/index.rst
- docs/readthedocs/source/doc/PythonAPI/Chronos/metrics.rst
- pyzoo/test/zoo/automl/common/test_metrics.py
- pyzoo/zoo/automl/common/metrics.py
#4356 
You can preview the doc [here](https://yuyin-analytics-zoo.readthedocs.io/en/metrics_doc/doc/PythonAPI/AutoML/automl.html#automl-common-metrics)
> Chronos Evaluator/Metrics API doc

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
fix the setting to "minimal".
related to #4405
> Chronos: shrink the tsfresh ut

- pyzoo/zoo/ray/raycontext.py
> fix integration test fail due to compatible to ray 1.5.0 

- pyzoo/zoo/automl/model/base_pytorch_model.py
- pyzoo/zoo/automl/search/ray_tune_search_engine.py
> Chronos: fix autoest/autotsest resource issue(pytorch)

- pyzoo/test/zoo/chronos/data/test_tsdataset.py
- pyzoo/test/zoo/chronos/data/utils/test_feature.py
> Chronos: shrink/remove possible problems in tsfresh uts

- pyzoo/zoo/friesian/feature/table.py
Fix https://github.com/intel-analytics/analytics-zoo/issues/4429
> Fix Table style

- docker/hyperzoo/Dockerfile
build image with the `SPARK_VERSION` parameter, the following values are optional
* 3.1.2
* 2.4.6
> update Dockerfile to support spark 3.1.2 && 2.4.6

- pyzoo/test/zoo/friesian/feature/test_table.py
- pyzoo/zoo/friesian/feature/table.py
- Output type cast to int
- Support output col the same as input col
> Fix cut bins

- pyzoo/zoo/chronos/data/utils/roll_dataset.py
This PR has optimized memory for tsdataset.to_torch_data_loader, tested on baidu-traffic dataset, from 14G to 4G.
This PR also fixed bug when the dataframe index doesn't start from zero.
> Optimize memory for tsdataset.to_torch_data_loader and fix index

- pyzoo/zoo/util/engine.py
Fix https://github.com/intel-analytics/analytics-zoo/issues/4427
> Support log level in pyzoo.zoo.util.engine.prepare_env

- ppml/trusted-big-data-ml/python/docker-graphene/examples/orca_api_example.py
- ppml/trusted-big-data-ml/python/docker-graphene/examples/sql_context_example.py
- ppml/trusted-big-data-ml/python/docker-graphene/examples/sql_example.py
- add orca TF and BigDL api example to python graphene
- add sql dataframe api example to python graphene
- add sqlcontext api example to python graphene
> add orca, sql dataframe and sqlcontext api examples to python graphene

- pyzoo/zoo/chronos/data/utils/split.py
Result on baidu-traffic dataset:
```python
tsdata_train, tsdata_valid, _ = TSDataset.from_pandas(df, dt_col="timestamp",
id_col="road_id",
target_col=["traffic_speed"],
with_split=True,
val_ratio=0.1,
test_ratio=0.1)
```
- Function split_timeseries_dataframe only: 
- Elapse time: 44.878s 
- Memory: 8493.35M 
- TSDataset.from_pandas(with_split=True): 
- Elapse time: 98.389s 
- Memory: 10129.09M
> Enhance tsdataset split function

- pyzoo/zoo/orca/learn/dl_cluster.py
> disable cpu binding in mac os

- scala/common/spark-version/2.0/pom.xml
- scala/common/utils/pom.xml
- scala/common/utils/src/test/scala/com/intel/analytics/bigdl/utils/EngineSpec.scala
- scala/common/utils/src/test/scala/com/intel/analytics/bigdl/utils/ThreadPoolSpec.scala
- scala/dllib/pom.xml
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/feature/dataset/MiniBatch.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/feature/dataset/Transformer.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/keras/KerasLayer.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/keras/Topology.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/optim/Optimizer.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/python/api/PythonBigDLKeras.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/python/api/PythonBigDLOnnx.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/python/api/PythonBigDLValidator.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/serializer/ModuleSerializable.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/serializer/ModuleSerializer.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/serializer/Types.scala
- scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/utils/serializer/converters/DataConverter.scala
- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/nn/DynamicGraphSpec.scala
- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/nn/ops/TensorArraySplitSpec.scala
- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/nn/tf/ControlOpsSpec.scala
- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/utils/serializer/DataConverterSpec.scala
- scala/scalastyle_config.xml
- scala/scripts/deploy-spark2.sh
- scala/scripts/deploy-spark3.sh
artifact: 
```
<bigdl.artifactId>bigdl-dllib-SPARK_2.4</bigdl.artifactId>
<dependency>
<groupId>com.intel.analytics.bigdl</groupId>
<artifactId>${bigdl.artifactId}</artifactId>
<version>${bigdl.version}</version>
<scope>${bigdl-scope}</scope>
</dependency>
```
> deploy dllib 

- ppml/trusted-realtime-ml/scala/docker-graphene/Dockerfile
- ppml/trusted-realtime-ml/scala/docker-graphene/bash.manifest.template
- ppml/trusted-realtime-ml/scala/docker-graphene/init-redis.sh
- ppml/trusted-realtime-ml/scala/docker-graphene/java.Makefile
- ppml/trusted-realtime-ml/scala/docker-graphene/java.manifest.template
- ppml/trusted-realtime-ml/scala/docker-graphene/redis.Makefile
- ppml/trusted-realtime-ml/scala/docker-graphene/start-flink-jobmanager.sh
- ppml/trusted-realtime-ml/scala/docker-graphene/start-redis.sh
init-redis already verified, changing from bash
Need to changing java entrypoint (in java.manifest) to bash (follow change in scala)
> Update Redis, Java entrypoint not changing yet

- pyzoo/test/zoo/friesian/feature/test_table.py
- pyzoo/zoo/friesian/feature/table.py
> Friesian table add cache support

- pyzoo/zoo/orca/learn/tf2/estimator.py
Current stategy does not work in some cases on k8s. Make default to false first.
> disable cpu binding by default

- python/nano/example/tensorflow/transfer_learning/transfer_learning.py
Add original code of a transfer learning example based on tensorflow.
> Original Tensorflow Transfer Learning Example

- docs/readthedocs/source/doc/Chronos/QuickStart/chronos-autotsest-quickstart.md
- docs/readthedocs/source/index.rst
related to #4187
preview on: https://junweitestdoc.readthedocs.io/en/autotsest-quickstart/doc/Chronos/QuickStart/chronos-autotsest-quickstart.html
> Chronos: add AutoTSEstimator quickstart to doc

- pyzoo/test/zoo/chronos/autots/model/test_auto_prophet.py
- pyzoo/zoo/chronos/use-case/fsi/stock_prediction_prophet.ipynb
> Chronos:  fix Prophet on jenkins (MAC-ONLY)

- docs/docs/ProgrammingGuide/visualization.md
- docs/readthedocs/source/doc/UserGuide/hadoop.md
* Modify CDH document based on comments
> Fix #4481 CDH doc

- python/nano/example/tensorflow/transfer_learning/Readme.md
- python/nano/example/tensorflow/transfer_learning/transfer_learning.py
Modified Tensorflow Transfer Leaning example from stock tensorflow to bigdl nano.
> Modifications on Transfer Learning Example

- scripts/cluster-serving/overall-correctness-check.py
**already done**: 
build zoo package
-> install zoo package
-> install and start Redis and Flink
-> start cluster serving(still having problem of "org.apache.flink.client.program.ProgramInvocationException: Error while opening jar file 'analytics-zoo/dist/bin/cluster-serving/zoo.jar'") 
-> predict with one image
**need further work**: install imagenet dataset and predict all data
> all round test script

- pyzoo/zoo/automl/model/base_pytorch_model.py
> fix bug in pytorch base model error message

- pyzoo/zoo/automl/search/parameters.py
- pyzoo/zoo/automl/search/ray_tune_search_engine.py
- pyzoo/zoo/chronos/pipeline/parameters.py
- pyzoo/zoo/chronos/pipeline/time_sequence.py
This PR finished below tasks mentioned in issue #4626
> refactor automl/common/parameters.py

- python/nano/example/tensorflow/lenet/lenet.py
Add original code of lenet tensorflow example.
> Add Original Code of Lenet TensorFlow Example

- pyzoo/zoo/chronos/use-case/fsi/stock_prediction_prophet.ipynb
> fix recipe import in autoprophet notebook

- python/nano/src/bigdl/nano/pytorch/accelerators/ipex_torchfunctional.py
`from torch import Tensor`
This line tries to fix some typecheck issue in jenkins.
> Bigdl-Nano: Add description to ipex_torchfunctional

- docker/hyperzoo/Dockerfile
> delete tensorflow 1.15.0

- heyang_pr_test
- ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/taskmanager-deployment.yaml.back
- ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/templates/jobmanager-deployment.yaml
- ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/templates/taskmanager-statefulset.yaml
- ppml/trusted-realtime-ml/scala/docker-graphene/start-flink-taskmanager.sh
> Apply the TM-JM-fix.patch

- docs/docs/ClusterServingGuide/DebugGuide.md
* Add troubleshooting for cluster serving debug guide
* Add 2 error and fixes
> Add troubleshooting for cluster serving debug guide

- ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/taskmanager-deployment.yaml.back
Fix the mistake in real-time cluster serving
> Replace with the latest init.sh in taskmanager-deployment.yaml.back

- docs/readthedocs/source/doc/UserGuide/python.md
> Add pypandoc to Known Issues

- python/orca/src/bigdl/orca/__init__.py
- python/orca/test/dev/prepare_env.sh
> Fix ray tfpark ut

- python/nano/dev/release.sh
- python/nano/setup.py
> deploy nano 0.14.0.dev0 to PyPI

- pyzoo/zoo/ray/utils.py
Fix #4791 
The issue is brought from #4571
> Fix ray import psutil

- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/feature/FeatureSpec.scala
- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/nn/keras/nn/KerasStyleSpec.scala
- scala/dllib/src/test/scala/com/intel/analytics/bigdl/dllib/utils/EngineSpec.scala
We have some ut failed on both local and jenkins. We need to fix these later.
> fix scala ut on jenkins

- docs/readthedocs/source/doc/PPML/trusted-serving-on-k8s-guide.md
- ppml/trusted-realtime-ml/scala/docker-graphene/kubernetes/taskmanager-deployment.yaml.back
1. Update docker image name in doc
2. Fix indentation issue in `taskmanager-deployment.yaml.back`
> [PPML] graphene serving update

- docs/readthedocs/source/doc/Chronos/Overview/chronos.md
https://junweitestdoc.readthedocs.io/en/simulator-on-ug/doc/Chronos/Overview/chronos.html#generate-synthetic-data
> Chronos: add simulator to user guide

- pyzoo/zoo/examples/friesian/feature/dien/dien_preprocessing.py
1, add add_value_features into scala version
2, cache
3, stops before padding to have same data as recdp
4, read meta data from csv
5, have a choice to keep last seq of history
6, other minor change
now it is 4x faster than the original implementation on almaren.
> dien performance

- pyzoo/setup.py
https://pypi.org/project/BigDL/0.14.0.dev3/
> release a nightly analytics-zoo with bigdl 0.14.0.dev3

- zoo/pom.xml
Reverts intel-analytics/analytics-zoo#5066
> Revert "update bigdl version to 0.14.0-SNAPSHOT"

- pyzoo/setup.py
Reverts intel-analytics/analytics-zoo#5065
> Revert "release a nightly analytics-zoo with bigdl 0.14.0.dev3"

- pyzoo/zoo/orca/learn/pytorch/training_operator.py
Backport https://github.com/intel-analytics/BigDL/pull/3626
> [Backport]Fix pytorch estimator hang due to uneven number of batches

- apps/model-inference-examples/recommendation-inference/pom.xml
- apps/model-inference-examples/text-classification-inference/pom.xml
- apps/model-inference-examples/text-classification-training/pom.xml
- ppml/pom.xml
- zoo/pom.xml
update BigDL components version
> update BigDL components version

- docs/readthedocs/requirements-doc.txt
- docs/readthedocs/requirements-rtd.txt
- zoo/pom.xml
1. upgrade python components version
2. upgrade log4j version to 2.17.1
> upgrade analytics-zoo components version

- apps/model-inference-examples/recommendation-inference/pom.xml
- apps/model-inference-examples/text-classification-inference/pom.xml
- apps/model-inference-examples/text-classification-training/pom.xml
> upgrade spark_core version

- pyzoo/setup.py
use PYSPARK_VERSION variable to replace pyspark version
> use PYSPARK_VERSION variable to replace pyspark version

- python/orca/src/bigdl/orca/ray/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch bigdl-2.0
> bigdl-2.0: remove hardcode redis password in raycontext

- pyzoo/zoo/ray/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from -ppml4g1.2rc1
> branch-ppml4g1.2rc1: remove hardcode redis password in raycontext

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
- pyzoo/zoo/ray/util/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch-0.7
> branch-0.7: remove hardcode redis password in raycontext

- pyzoo/zoo/ray/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch bigdl-0.8
> branch-0.8: remove hardcode redis password in raycontext

- pyzoo/zoo/ray/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch bigdl-0.9
> branch-0.9: remove hardcode redis password in raycontext

- apps/run-app-tests-pip.sh
- apps/run-app-tests.sh
- pyzoo/zoo/ray/util/raycontext.py
This submission removes hardcoded redis_password from raycontext.py from branch-0.6
> branch-0.6: remove hardcode redis password in raycontext

- apps/model-inference-examples/recommendation-inference/pom.xml
- apps/model-inference-examples/text-classification-inference/pom.xml
- apps/model-inference-examples/text-classification-training/pom.xml
change spark_core version to variable
> change spark_core version to variable

- .github/workflows/BiWeekly_docker.yml
- .github/workflows/chronos-nb-python-spark31.yml
- .github/workflows/chronos-notebook-python-spark31.yml
- .github/workflows/license-scan.yml
- .github/workflows/llm-c-evaluation.yml
- .github/workflows/llm-harness-evaluation.yml
- .github/workflows/llm-nightly-test.yml
- .github/workflows/llm-ppl-evaluation.yml
- .github/workflows/llm-whisper-evaluation.yml
- .github/workflows/llm_performance_tests.yml
- .github/workflows/mac_nightly_test.yml
- .github/workflows/nano-nightly-test.yml
- .github/workflows/nightly-build-example-tests-ppml.yaml
- .github/workflows/nightly_build.yml
- .github/workflows/nightly_test.yml
- .github/workflows/performance-regression-test.yml
- .github/workflows/python-style-check.yml
- .github/workflows/scala-style-check.yml
- .github/workflows/sdl_snyk_docker.yml
- .github/workflows/sdl_snyk_python.yml
- .github/workflows/sdl_snyk_scala.yml
- .github/workflows/sdl_virus-malware.yml
- .github/workflows/stable-diffusion-winlog.yml
- .github/workflows/url-auto-merge.yml
- .github/workflows/weekly_test.yml
This submission disables workflow's scheduled event so that workflows won't run every night.
> disable workflows' schedule event

- .github/workflows/scorecard.yml
update ossf/scorecard-action to fix TUF invalid key bug: https://github.com/ossf/scorecard-action/issues/998
> Bump ossf/scorecard-action to v2.3.1

- ppml/tdx/docker/trusted-bigdl-llm/inference/Dockerfile
- ppml/tdx/docker/trusted-bigdl-llm/inference/requirements.txt
- python/llm/example/CPU/Speculative-Decoding/baichuan2/README.md
- python/llm/example/CPU/Speculative-Decoding/baichuan2/requirements.txt
- python/llm/example/CPU/Speculative-Decoding/vicuna/requirements.txt
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/498
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/499
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/497
> Fix transformers version dependabot issues

- python/nano/setup.py
- python/requirements/nano/requirements.txt
- Dependency1 
- Dependency2
- ...
- Dependency1 and license1
- Dependency2 and license2
- ...
> Fix dependabot issues

- python/requirements/nano/requirements_torch.txt
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/505
> fix dependabot issue

- scripts/requirements.txt
Fix https://github.com/intel-analytics/BigDL-2.x/security/dependabot/506
> unpin keras version to fix dependabot issue

- scripts/requirements.txt
Fix https://github.com/intel-analytics/BigDL-2.x/security/dependabot/506
> update keras version to fix dependabot issue

- python/requirements/nano/requirements_torch.txt
Fix Dependabot Alerts:
https://github.com/intel-analytics/BigDL-2.x/security/dependabot/511
> fix dependabot alerts

- ppml/tdx/docker/trusted-bigdl-llm/inference/requirements.txt
Fix https://github.com/intel-analytics/BigDL-2.x/security/dependabot/520
- Dependency1 
- Dependency2
- ...
- Dependency1 and license1
- Dependency2 and license2
- ...
> fix dependabot alert

- python/llm/test/run-llm-windows-tests.sh
Fix https://github.com/intel/BigDL/security/secret-scanning/2
- Dependency1 
- Dependency2
- ...
- Dependency1 and license1
- Dependency2 and license2
- ...
> remove secret from run-llm-windows-tests.sh
